// Code generated by tools/genschema from the NGFW OpenAPI document (NGFW API 0.1.0); DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ = attr.Value(nil)
	_ = booldefault.StaticBool
	_ = int64default.StaticInt64
	_ = listdefault.StaticValue
	_ = mapdefault.StaticValue
	_ = stringdefault.StaticString
	_ = types.StringType
)

// interfaceGeneratedAttributes are the attributes of one entry of /interfaces (InterfacesConfig item).
func interfaceGeneratedAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"adl": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "Allow/deny list (ADL) — source allow-list on the device input path (physical ports); off unless ipv4 or ipv6 is checked", Attributes: map[string]schema.Attribute{
			"allow_vrf":     schema.StringAttribute{Optional: true, MarkdownDescription: "Allow-list VRF — VRF whose table holds the allowed source prefixes as local (receive) entries; required when a family is checked"},
			"default_allow": schema.BoolAttribute{Optional: true, MarkdownDescription: "Pass non-IP frames — ARP and other non-IP frames are not checked (the engine cannot filter them)", Computed: true, Default: booldefault.StaticBool(true)},
			"ipv4":          schema.BoolAttribute{Optional: true, MarkdownDescription: "Check IPv4 sources — drop IPv4 packets whose source is not in the allow-list VRF", Computed: true, Default: booldefault.StaticBool(false)},
			"ipv6":          schema.BoolAttribute{Optional: true, MarkdownDescription: "Check IPv6 sources — drop IPv6 packets whose source is not in the allow-list VRF", Computed: true, Default: booldefault.StaticBool(false)},
		}},
		"bond": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "Bond — make this interface (BondEthernet<id>) a link aggregation of the member interfaces", Attributes: map[string]schema.Attribute{
			"id":           schema.Int64Attribute{Optional: true, MarkdownDescription: "Bond ID — Engine bond id; absent = the number in the interface name (BondEthernet<id>)"},
			"load_balance": schema.StringAttribute{Optional: true, MarkdownDescription: "Load balance — xor and lacp only: transmit hash over l2 (MAC), l23 (MAC+IP) or l34 (IP+port); absent = l2 (one of `l2`, `l23`, `l34`)"},
			"members":      schema.MapNestedAttribute{Optional: true, MarkdownDescription: "Members — member interfaces keyed by name; each needs its own entry in interfaces (enabled, no addresses)", NestedObject: genifaceBondMembersValueObject(), Computed: true, Default: mapdefault.StaticValue(types.MapValueMust(genifaceBondMembersValueObject().Type(), map[string]attr.Value{}))},
			"mode":         schema.StringAttribute{Required: true, MarkdownDescription: "Mode — lacp (802.3ad), xor, round-robin or active-backup; changing it re-creates the bond (one of `lacp`, `xor`, `round-robin`, `active-backup`)"},
			"numa_only":    schema.BoolAttribute{Optional: true, MarkdownDescription: "NUMA-local members only — transmit only on members attached to the bond’s NUMA node", Computed: true, Default: booldefault.StaticBool(false)},
		}},
		"description": schema.StringAttribute{Optional: true, MarkdownDescription: "Description"},
		"dhcp_client": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "DHCP client — obtain an IPv4 address by DHCP; cannot be combined with unnumbered", Attributes: map[string]schema.Attribute{
			"client_id":          schema.StringAttribute{Optional: true, MarkdownDescription: "Client identifier — option 61; absent = the interface MAC address"},
			"hostname":           schema.StringAttribute{Optional: true, MarkdownDescription: "Hostname — sent in option 12; absent = the system hostname"},
			"set_broadcast_flag": schema.BoolAttribute{Optional: true, MarkdownDescription: "Broadcast flag — ask the server to broadcast its replies", Computed: true, Default: booldefault.StaticBool(false)},
		}},
		"enabled": schema.BoolAttribute{Optional: true, MarkdownDescription: "Enabled — admin state; interfaces stay down until enabled", Computed: true, Default: booldefault.StaticBool(false)},
		"gso":     schema.BoolAttribute{Optional: true, MarkdownDescription: "GSO — software generic segmentation offload on output (engine gso feature); absent = off"},
		"ipv4":    schema.ListAttribute{Optional: true, MarkdownDescription: "IPv4 addresses — addresses with prefix length, e.g. 10.0.0.1/24", ElementType: types.StringType, Computed: true, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{}))},
		"ipv6":    schema.ListAttribute{Optional: true, MarkdownDescription: "IPv6 addresses — addresses with prefix length, e.g. 2001:db8::1/64", ElementType: types.StringType, Computed: true, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{}))},
		"ipv6_ra": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "IPv6 router advertisements — absent = engine defaults (RAs suppressed); the interface needs an IPv6 address", Attributes: map[string]schema.Attribute{
			"lifetime_sec":     schema.Int64Attribute{Optional: true, MarkdownDescription: "Router lifetime (s) — 0 = not a default router; otherwise greater than the maximum interval, at most 9000", Computed: true, Default: int64default.StaticInt64(600)},
			"managed":          schema.BoolAttribute{Optional: true, MarkdownDescription: "Managed flag (M) — hosts obtain addresses by DHCPv6", Computed: true, Default: booldefault.StaticBool(false)},
			"max_interval_sec": schema.Int64Attribute{Optional: true, MarkdownDescription: "Maximum interval (s) — between unsolicited RAs, 4–1800", Computed: true, Default: int64default.StaticInt64(200)},
			"min_interval_sec": schema.Int64Attribute{Optional: true, MarkdownDescription: "Minimum interval (s) — at least 3 and at most 0.75 × the maximum interval", Computed: true, Default: int64default.StaticInt64(150)},
			"other":            schema.BoolAttribute{Optional: true, MarkdownDescription: "Other configuration flag (O) — hosts obtain other settings (DNS …) by DHCPv6", Computed: true, Default: booldefault.StaticBool(false)},
			"prefixes":         schema.MapNestedAttribute{Optional: true, MarkdownDescription: "Advertised prefixes — prefix-information options keyed by prefix, e.g. 2001:db8:1::/64 (SLAAC needs a /64)", NestedObject: genifaceIpv6RaPrefixesValueObject(), Computed: true, Default: mapdefault.StaticValue(types.MapValueMust(genifaceIpv6RaPrefixesValueObject().Type(), map[string]attr.Value{}))},
			"suppress":         schema.BoolAttribute{Optional: true, MarkdownDescription: "Suppress router advertisements — untick to send RAs on this interface (the engine suppresses them by default)", Computed: true, Default: booldefault.StaticBool(true)},
		}},
		"l2": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "L2 switching — bridge-domain membership, VLAN tag rewrite and MAC filter of this interface", Attributes: map[string]schema.Attribute{
			"bridge_domain": schema.StringAttribute{Optional: true, MarkdownDescription: "Bridge domain — name of the bridge domain (routing.l2.bridgeDomains) this interface is a member of; absent = not bridged"},
			"bvi":           schema.BoolAttribute{Optional: true, MarkdownDescription: "BVI — bridge virtual interface: the routed (L3) port of the bridge domain; a loopback, one per domain", Computed: true, Default: booldefault.StaticBool(false)},
			"mac_filter":    schema.BoolAttribute{Optional: true, MarkdownDescription: "Time-range MAC filter — run the mactime filter (routing.l2.macFilters) on frames received here; parent interfaces only", Computed: true, Default: booldefault.StaticBool(false)},
			"shg":           schema.Int64Attribute{Optional: true, MarkdownDescription: "Split-horizon group — 0 = none; members of the same group never forward to each other", Computed: true, Default: int64default.StaticInt64(0)},
			"tag_rewrite": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "VLAN tag rewrite — on a bridge member or an L2 cross-connect rx", Attributes: map[string]schema.Attribute{
				"dot1ad": schema.BoolAttribute{Optional: true, MarkdownDescription: "802.1ad outer tag — pushed outer tag uses 0x88a8 instead of 0x8100 (push and translate only)", Computed: true, Default: booldefault.StaticBool(false)},
				"op":     schema.StringAttribute{Required: true, MarkdownDescription: "Operation — push-1/2 add tags, pop-1/2 remove tags, translate-N-M replace N tags by M tags (one of `push-1`, `push-2`, `pop-1`, `pop-2`, `translate-1-1`, `translate-1-2`, `translate-2-1`, `translate-2-2`)"},
				"tag1":   schema.Int64Attribute{Optional: true, MarkdownDescription: "Tag 1 — outer VLAN id written by push / translate"},
				"tag2":   schema.Int64Attribute{Optional: true, MarkdownDescription: "Tag 2 — inner VLAN id written by push-2 / translate-1-2 / translate-2-2"},
			}},
			"uu_fwd": schema.BoolAttribute{Optional: true, MarkdownDescription: "Unknown-unicast forwarder — send unknown-unicast frames to this member only (uu-fwd port)", Computed: true, Default: booldefault.StaticBool(false)},
		}},
		"lcp": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "Linux pair (linux-cp) — mirror the interface into Linux so FRR can run routing protocols on it", Attributes: map[string]schema.Attribute{
			"host_if_name": schema.StringAttribute{Optional: true, MarkdownDescription: "Linux interface name — name of the host tap; default: the engine name when it is a valid Linux name (max 15 characters)"},
			"host_if_type": schema.StringAttribute{Optional: true, MarkdownDescription: "Host interface type — tap (Ethernet, default) or tun (L3 only, point-to-point links) (one of `tap`, `tun`)", Computed: true, Default: stringdefault.StaticString("tap")},
			"netns":        schema.StringAttribute{Optional: true, MarkdownDescription: "Network namespace — namespace of the host tap; default: the linux-cp default namespace (where FRR runs)"},
		}},
		"mac":    schema.StringAttribute{Optional: true, MarkdownDescription: "MAC address — override the hardware address; absent = keep the burned-in MAC"},
		"mirror": schema.ListNestedAttribute{Optional: true, MarkdownDescription: "Port mirroring — mirror sessions with this interface as the source (SPAN; ERSPAN through a GRE erspan tunnel)", NestedObject: genifaceMirrorItemObject()},
		"mtu":    schema.Int64Attribute{Optional: true, MarkdownDescription: "MTU — L3 MTU in bytes (68–9216); absent = keep the driver default"},
		"pppoe": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "PPPoE client — dial an ISP over PPPoE and use the assigned address on this interface; absent = off", Attributes: map[string]schema.Attribute{
			"default_route": schema.BoolAttribute{Optional: true, MarkdownDescription: "Default route from peer — install a default route via the session (the ISP is the gateway)", Computed: true, Default: booldefault.StaticBool(true)},
			"dns_from_peer": schema.BoolAttribute{Optional: true, MarkdownDescription: "Use peer DNS — use the DNS servers the ISP sends (IPCP) as the system resolvers", Computed: true, Default: booldefault.StaticBool(false)},
			"enabled":       schema.BoolAttribute{Optional: true, MarkdownDescription: "Enabled — dial the session; disable to keep the settings but stay offline", Computed: true, Default: booldefault.StaticBool(true)},
			"ipv6":          schema.StringAttribute{Optional: true, MarkdownDescription: "IPv6 — off; slaac (accept a /64 via RA over the link); dhcpv6 (request a prefix via DHCPv6-PD) (one of `off`, `slaac`, `dhcpv6`)", Computed: true, Default: stringdefault.StaticString("off")},
			"mss_clamp":     schema.BoolAttribute{Optional: true, MarkdownDescription: "Clamp TCP MSS — rewrite the TCP MSS of forwarded SYNs to fit the PPPoE MTU (avoids black-holed large packets)", Computed: true, Default: booldefault.StaticBool(true)},
			"mtu":           schema.Int64Attribute{Optional: true, MarkdownDescription: "MTU — PPPoE payload MTU; 1492 is the Ethernet default (1500 − 8 for the PPPoE/PPP headers)", Computed: true, Default: int64default.StaticInt64(1492)},
			"parent":        schema.StringAttribute{Optional: true, MarkdownDescription: "Dial over interface — engine interface the session runs over; default = this interface (set for a VLAN sub-interface WAN)"},
			"password_ref":  schema.StringAttribute{Required: true, MarkdownDescription: "Password — reference to a stored password secret (password/<name>); never the password itself", Sensitive: true},
			"reconnect": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "Reconnect — what to do when the session drops", Attributes: map[string]schema.Attribute{
				"holdoff_sec": schema.Int64Attribute{Optional: true, MarkdownDescription: "Hold-off (seconds) — wait this long before redialling after the session goes down", Computed: true, Default: int64default.StaticInt64(5)},
				"max_fail":    schema.Int64Attribute{Optional: true, MarkdownDescription: "Max consecutive failures — give up after this many failed dials in a row; 0 = keep trying forever", Computed: true, Default: int64default.StaticInt64(0)},
			}},
			"service_name": schema.StringAttribute{Optional: true, MarkdownDescription: "Service name — RFC 2516 Service-Name to request; leave empty to accept any AC"},
			"username":     schema.StringAttribute{Required: true, MarkdownDescription: "Username — PPP username (PAP/CHAP) from the ISP"},
		}},
		"promiscuous":   schema.BoolAttribute{Optional: true, MarkdownDescription: "Promiscuous — accept frames for any destination MAC", Computed: true, Default: booldefault.StaticBool(false)},
		"proxy_arp":     schema.BoolAttribute{Optional: true, MarkdownDescription: "Proxy ARP — answer ARP for the proxy-ARP ranges of this interface’s VRF; absent = off"},
		"proxy_nd":      schema.ListAttribute{Optional: true, MarkdownDescription: "Proxy ND addresses (experimental) — experimental and off by default: applied only by an agent started with NGFW_DF2_PROXY_ND=1 (V12)", ElementType: types.StringType},
		"rx_mode":       schema.StringAttribute{Optional: true, MarkdownDescription: "RX mode — polling (default for DPDK), interrupt or adaptive (one of `polling`, `interrupt`, `adaptive`)"},
		"subinterfaces": schema.MapNestedAttribute{Optional: true, MarkdownDescription: "Sub-interfaces — 802.1Q / QinQ sub-interfaces keyed by sub-interface id (usually the VLAN id)", NestedObject: genifaceSubinterfacesValueObject(), Computed: true, Default: mapdefault.StaticValue(types.MapValueMust(genifaceSubinterfacesValueObject().Type(), map[string]attr.Value{}))},
		"unnumbered":    schema.StringAttribute{Optional: true, MarkdownDescription: "IP unnumbered — borrow the addresses of this interface (e.g. loop0); ipv4/ipv6 must then be empty"},
		"urpf": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "Unicast RPF — reverse-path check of the source address; absent = off", Attributes: map[string]schema.Attribute{
			"direction": schema.StringAttribute{Optional: true, MarkdownDescription: "Direction — rx checks packets received on the interface, tx packets sent out of it (one of `rx`, `tx`)", Computed: true, Default: stringdefault.StaticString("rx")},
			"ipv4":      schema.StringAttribute{Optional: true, MarkdownDescription: "IPv4 check — loose: the source must be routable; strict: routable through this interface; absent = no check (one of `loose`, `strict`)"},
			"ipv6":      schema.StringAttribute{Optional: true, MarkdownDescription: "IPv6 check — loose: the source must be routable; strict: routable through this interface; absent = no check (one of `loose`, `strict`)"},
		}},
		"vrf": schema.StringAttribute{Optional: true, MarkdownDescription: "VRF — routing table this interface belongs to", Computed: true, Default: stringdefault.StaticString("default")},
	}
}

func genifaceBondMembersValueObject() schema.NestedAttributeObject {
	return schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
		"long_timeout": schema.BoolAttribute{Optional: true, MarkdownDescription: "Long timeout — LACP only: 90 s partner timeout (slow LACPDUs) instead of 3 s", Computed: true, Default: booldefault.StaticBool(false)},
		"passive":      schema.BoolAttribute{Optional: true, MarkdownDescription: "Passive — LACP only: do not initiate LACP; the partner must be active", Computed: true, Default: booldefault.StaticBool(false)},
		"weight":       schema.Int64Attribute{Optional: true, MarkdownDescription: "Weight — active-backup only: the up member with the highest weight is the active one (1–255); absent = engine default"},
	}}
}

func genifaceIpv6RaPrefixesValueObject() schema.NestedAttributeObject {
	return schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
		"no_autoconfig": schema.BoolAttribute{Optional: true, MarkdownDescription: "No autoconfiguration — clear the autonomous (A) flag: hosts do not form SLAAC addresses from this prefix", Computed: true, Default: booldefault.StaticBool(false)},
		"off_link":      schema.BoolAttribute{Optional: true, MarkdownDescription: "Off-link — clear the on-link (L) flag", Computed: true, Default: booldefault.StaticBool(false)},
		"preferred_sec": schema.Int64Attribute{Optional: true, MarkdownDescription: "Preferred lifetime (s) — preferred lifetime, at least 1; must not exceed the valid lifetime", Computed: true, Default: int64default.StaticInt64(604800)},
		"valid_sec":     schema.Int64Attribute{Optional: true, MarkdownDescription: "Valid lifetime (s) — valid lifetime advertised for the prefix, at least 1; 4294967295 = infinite", Computed: true, Default: int64default.StaticInt64(2592000)},
	}}
}

func genifaceMirrorItemObject() schema.NestedAttributeObject {
	return schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
		"destination": schema.StringAttribute{Required: true, MarkdownDescription: "Destination — interface that transmits the copies — a monitor port, or a GRE tunnel of type erspan for ERSPAN"},
		"direction":   schema.StringAttribute{Optional: true, MarkdownDescription: "Direction — received (rx), transmitted (tx) or both (one of `rx`, `tx`, `both`)", Computed: true, Default: stringdefault.StaticString("both")},
		"level":       schema.StringAttribute{Optional: true, MarkdownDescription: "Level — device: every frame of the interface; l2: only frames in the L2 path (bridge member or cross-connect) (one of `device`, `l2`)", Computed: true, Default: stringdefault.StaticString("device")},
	}}
}

func genifaceSubinterfacesValueIpv6RaPrefixesValueObject() schema.NestedAttributeObject {
	return schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
		"no_autoconfig": schema.BoolAttribute{Optional: true, MarkdownDescription: "No autoconfiguration — clear the autonomous (A) flag: hosts do not form SLAAC addresses from this prefix", Computed: true, Default: booldefault.StaticBool(false)},
		"off_link":      schema.BoolAttribute{Optional: true, MarkdownDescription: "Off-link — clear the on-link (L) flag", Computed: true, Default: booldefault.StaticBool(false)},
		"preferred_sec": schema.Int64Attribute{Optional: true, MarkdownDescription: "Preferred lifetime (s) — preferred lifetime, at least 1; must not exceed the valid lifetime", Computed: true, Default: int64default.StaticInt64(604800)},
		"valid_sec":     schema.Int64Attribute{Optional: true, MarkdownDescription: "Valid lifetime (s) — valid lifetime advertised for the prefix, at least 1; 4294967295 = infinite", Computed: true, Default: int64default.StaticInt64(2592000)},
	}}
}

func genifaceSubinterfacesValueObject() schema.NestedAttributeObject {
	return schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
		"description": schema.StringAttribute{Optional: true, MarkdownDescription: "Description"},
		"dhcp_client": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "DHCP client — obtain an IPv4 address by DHCP; cannot be combined with unnumbered", Attributes: map[string]schema.Attribute{
			"client_id":          schema.StringAttribute{Optional: true, MarkdownDescription: "Client identifier — option 61; absent = the interface MAC address"},
			"hostname":           schema.StringAttribute{Optional: true, MarkdownDescription: "Hostname — sent in option 12; absent = the system hostname"},
			"set_broadcast_flag": schema.BoolAttribute{Optional: true, MarkdownDescription: "Broadcast flag — ask the server to broadcast its replies", Computed: true, Default: booldefault.StaticBool(false)},
		}},
		"dot1ad":        schema.BoolAttribute{Optional: true, MarkdownDescription: "802.1ad outer tag — use an 802.1ad (0x88a8) outer tag instead of 802.1Q (0x8100)", Computed: true, Default: booldefault.StaticBool(false)},
		"enabled":       schema.BoolAttribute{Optional: true, MarkdownDescription: "Enabled — admin state; interfaces stay down until enabled", Computed: true, Default: booldefault.StaticBool(false)},
		"inner_vlan_id": schema.Int64Attribute{Optional: true, MarkdownDescription: "Inner VLAN ID — inner tag for QinQ (two-tag) sub-interfaces"},
		"ipv4":          schema.ListAttribute{Optional: true, MarkdownDescription: "IPv4 addresses — addresses with prefix length, e.g. 10.0.0.1/24", ElementType: types.StringType, Computed: true, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{}))},
		"ipv6":          schema.ListAttribute{Optional: true, MarkdownDescription: "IPv6 addresses — addresses with prefix length, e.g. 2001:db8::1/64", ElementType: types.StringType, Computed: true, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{}))},
		"ipv6_ra": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "IPv6 router advertisements — absent = engine defaults (RAs suppressed); the interface needs an IPv6 address", Attributes: map[string]schema.Attribute{
			"lifetime_sec":     schema.Int64Attribute{Optional: true, MarkdownDescription: "Router lifetime (s) — 0 = not a default router; otherwise greater than the maximum interval, at most 9000", Computed: true, Default: int64default.StaticInt64(600)},
			"managed":          schema.BoolAttribute{Optional: true, MarkdownDescription: "Managed flag (M) — hosts obtain addresses by DHCPv6", Computed: true, Default: booldefault.StaticBool(false)},
			"max_interval_sec": schema.Int64Attribute{Optional: true, MarkdownDescription: "Maximum interval (s) — between unsolicited RAs, 4–1800", Computed: true, Default: int64default.StaticInt64(200)},
			"min_interval_sec": schema.Int64Attribute{Optional: true, MarkdownDescription: "Minimum interval (s) — at least 3 and at most 0.75 × the maximum interval", Computed: true, Default: int64default.StaticInt64(150)},
			"other":            schema.BoolAttribute{Optional: true, MarkdownDescription: "Other configuration flag (O) — hosts obtain other settings (DNS …) by DHCPv6", Computed: true, Default: booldefault.StaticBool(false)},
			"prefixes":         schema.MapNestedAttribute{Optional: true, MarkdownDescription: "Advertised prefixes — prefix-information options keyed by prefix, e.g. 2001:db8:1::/64 (SLAAC needs a /64)", NestedObject: genifaceSubinterfacesValueIpv6RaPrefixesValueObject(), Computed: true, Default: mapdefault.StaticValue(types.MapValueMust(genifaceSubinterfacesValueIpv6RaPrefixesValueObject().Type(), map[string]attr.Value{}))},
			"suppress":         schema.BoolAttribute{Optional: true, MarkdownDescription: "Suppress router advertisements — untick to send RAs on this interface (the engine suppresses them by default)", Computed: true, Default: booldefault.StaticBool(true)},
		}},
		"l2": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "L2 switching — bridge-domain membership and VLAN tag rewrite of this sub-interface", Attributes: map[string]schema.Attribute{
			"bridge_domain": schema.StringAttribute{Optional: true, MarkdownDescription: "Bridge domain — name of the bridge domain (routing.l2.bridgeDomains) this interface is a member of; absent = not bridged"},
			"bvi":           schema.BoolAttribute{Optional: true, MarkdownDescription: "BVI — bridge virtual interface: the routed (L3) port of the bridge domain; a loopback, one per domain", Computed: true, Default: booldefault.StaticBool(false)},
			"mac_filter":    schema.BoolAttribute{Optional: true, MarkdownDescription: "Time-range MAC filter — run the mactime filter (routing.l2.macFilters) on frames received here; parent interfaces only", Computed: true, Default: booldefault.StaticBool(false)},
			"shg":           schema.Int64Attribute{Optional: true, MarkdownDescription: "Split-horizon group — 0 = none; members of the same group never forward to each other", Computed: true, Default: int64default.StaticInt64(0)},
			"tag_rewrite": schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "VLAN tag rewrite — on a bridge member or an L2 cross-connect rx", Attributes: map[string]schema.Attribute{
				"dot1ad": schema.BoolAttribute{Optional: true, MarkdownDescription: "802.1ad outer tag — pushed outer tag uses 0x88a8 instead of 0x8100 (push and translate only)", Computed: true, Default: booldefault.StaticBool(false)},
				"op":     schema.StringAttribute{Required: true, MarkdownDescription: "Operation — push-1/2 add tags, pop-1/2 remove tags, translate-N-M replace N tags by M tags (one of `push-1`, `push-2`, `pop-1`, `pop-2`, `translate-1-1`, `translate-1-2`, `translate-2-1`, `translate-2-2`)"},
				"tag1":   schema.Int64Attribute{Optional: true, MarkdownDescription: "Tag 1 — outer VLAN id written by push / translate"},
				"tag2":   schema.Int64Attribute{Optional: true, MarkdownDescription: "Tag 2 — inner VLAN id written by push-2 / translate-1-2 / translate-2-2"},
			}},
			"uu_fwd": schema.BoolAttribute{Optional: true, MarkdownDescription: "Unknown-unicast forwarder — send unknown-unicast frames to this member only (uu-fwd port)", Computed: true, Default: booldefault.StaticBool(false)},
		}},
		"mtu":        schema.Int64Attribute{Optional: true, MarkdownDescription: "MTU — L3 MTU in bytes (68–9216); absent = keep the driver default"},
		"proxy_arp":  schema.BoolAttribute{Optional: true, MarkdownDescription: "Proxy ARP — answer ARP for the proxy-ARP ranges of this interface’s VRF; absent = off"},
		"proxy_nd":   schema.ListAttribute{Optional: true, MarkdownDescription: "Proxy ND addresses (experimental) — experimental and off by default: applied only by an agent started with NGFW_DF2_PROXY_ND=1 (V12)", ElementType: types.StringType},
		"unnumbered": schema.StringAttribute{Optional: true, MarkdownDescription: "IP unnumbered — borrow the addresses of this interface (e.g. loop0); ipv4/ipv6 must then be empty"},
		"vlan_id":    schema.Int64Attribute{Required: true, MarkdownDescription: "VLAN ID — outer 802.1Q (or 802.1ad) tag"},
		"vrf":        schema.StringAttribute{Optional: true, MarkdownDescription: "VRF — routing table this interface belongs to", Computed: true, Default: stringdefault.StaticString("default")},
	}}
}

// interfaceJSONNames maps attribute names (any depth) to the JSON member names of the API document.
var interfaceJSONNames = map[string]string{
	"allow_vrf":          "allowVrf",
	"bridge_domain":      "bridgeDomain",
	"client_id":          "clientId",
	"default_allow":      "defaultAllow",
	"default_route":      "defaultRoute",
	"dhcp_client":        "dhcpClient",
	"dns_from_peer":      "dnsFromPeer",
	"holdoff_sec":        "holdoffSec",
	"host_if_name":       "hostIfName",
	"host_if_type":       "hostIfType",
	"inner_vlan_id":      "innerVlanId",
	"ipv6_ra":            "ipv6Ra",
	"lifetime_sec":       "lifetimeSec",
	"load_balance":       "loadBalance",
	"long_timeout":       "longTimeout",
	"mac_filter":         "macFilter",
	"max_fail":           "maxFail",
	"max_interval_sec":   "maxIntervalSec",
	"min_interval_sec":   "minIntervalSec",
	"mss_clamp":          "mssClamp",
	"no_autoconfig":      "noAutoconfig",
	"numa_only":          "numaOnly",
	"off_link":           "offLink",
	"password_ref":       "passwordRef",
	"preferred_sec":      "preferredSec",
	"proxy_arp":          "proxyArp",
	"proxy_nd":           "proxyNd",
	"rx_mode":            "rxMode",
	"service_name":       "serviceName",
	"set_broadcast_flag": "setBroadcastFlag",
	"tag_rewrite":        "tagRewrite",
	"uu_fwd":             "uuFwd",
	"valid_sec":          "validSec",
	"vlan_id":            "vlanId",
}

// interfaceSensitiveAttributes are the attribute paths holding secret references or write-only values.
var interfaceSensitiveAttributes = []string{
	"pppoe.password_ref",
}
