// Code generated by tools/genschema from the VRX OpenAPI document (VRX API 0.1.0); DO NOT EDIT.

package provider

// writeOnlyPointers: write-only leaves of the configuration document (D-046); `*` = one key or index.
var writeOnlyPointers = []string{
	"/management/users/*/passwordHash",
}

// secretRefPointers: secret references `<kind>/<name>` (D-051) — names, not values.
var secretRefPointers = []string{
	"/ha/cluster/secretRef",
	"/management/aaa/radius/servers/*/secretRef",
	"/management/aaa/tacacs/servers/*/secretRef",
	"/management/tls/certificateRef",
	"/management/tls/privateKeyRef",
	"/routing/bgp/neighbors/*/passwordRef",
	"/routing/bgp/peerGroups/*/passwordRef",
	"/services/ntp/ntsServer/certificateRef",
	"/services/ntp/ntsServer/keyRef",
	"/services/ntp/servers/*/keyRef",
	"/services/snmp/communities/*/secretRef",
	"/services/snmp/v3Users/*/authRef",
	"/services/snmp/v3Users/*/privRef",
	"/vpn/ipsec/tunnels/*/auth/secretRef",
	"/vpn/pki/cas/*/certificateRef",
	"/vpn/pki/certificates/*/certificateRef",
	"/vpn/pki/certificates/*/privateKeyRef",
	"/vpn/pki/hsm/pinRef",
	"/vpn/remoteAccess/*/radius/servers/*/secretRef",
	"/vpn/remoteAccess/*/users/*/passwordRef",
	"/vpn/wireguard/interfaces/*/peers/*/presharedKeyRef",
	"/vpn/wireguard/interfaces/*/privateKeyRef",
}

// keyedArrayPointers: arrays whose elements are identified by one member (`x-vrx-ui.itemKey`) —
// sensitive_value elements are matched by that key, never by index.
var keyedArrayPointers = map[string]string{
	"/management/users":                   "username",
	"/routing/bgp/networks":               "prefix",
	"/routing/policy/prefixLists/*/rules": "seq",
	"/routing/policy/routeMaps/*/entries": "seq",
}
