// Desired state of the vxlan_gpe descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: vxlan_gpe/model.proto

package vxlan_gpe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol is the VXLAN-GPE next-protocol of the inner payload.
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_IP4                  Protocol = 1
	Protocol_IP6                  Protocol = 2
	Protocol_ETHERNET             Protocol = 3
	Protocol_NSH                  Protocol = 4
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "IP4",
		2: "IP6",
		3: "ETHERNET",
		4: "NSH",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"IP4":                  1,
		"IP6":                  2,
		"ETHERNET":             3,
		"NSH":                  4,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_vxlan_gpe_model_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_vxlan_gpe_model_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_vxlan_gpe_model_proto_rawDescGZIP(), []int{0}
}

// Tunnel is one VXLAN-GPE tunnel interface (vxlan_gpe_add_del_tunnel_v2 /
// vxlan_gpe_tunnel_v2_dump). VPP names the interface itself; the name field is the object id
// and the owner tag.
type Tunnel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Outer local address (IPv4 or IPv6).
	Local string `protobuf:"bytes,2,opt,name=local,proto3" json:"local,omitempty"`
	// Outer remote address, unicast or multicast group.
	Remote string `protobuf:"bytes,3,opt,name=remote,proto3" json:"remote,omitempty"`
	// UDP ports; 0 = VXLAN-GPE default 4790 (Retrieve canonicalises 4790 back to 0).
	LocalPort  uint32 `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort uint32 `protobuf:"varint,5,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	// Interface for the multicast group (mandatory iff remote is multicast).
	McastInterface string   `protobuf:"bytes,6,opt,name=mcast_interface,json=mcastInterface,proto3" json:"mcast_interface,omitempty"`
	Vni            uint32   `protobuf:"varint,7,opt,name=vni,proto3" json:"vni,omitempty"`
	Protocol       Protocol `protobuf:"varint,8,opt,name=protocol,proto3,enum=ngfw.agent.descriptors.vxlan_gpe.Protocol" json:"protocol,omitempty"`
	// Encap FIB table id (dependency vrf/<id> unless 0).
	EncapVrfId uint32 `protobuf:"varint,9,opt,name=encap_vrf_id,json=encapVrfId,proto3" json:"encap_vrf_id,omitempty"`
	// Decap FIB table id (dependency vrf/<id> unless 0).
	DecapVrfId    uint32 `protobuf:"varint,10,opt,name=decap_vrf_id,json=decapVrfId,proto3" json:"decap_vrf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_vxlan_gpe_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_vxlan_gpe_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_vxlan_gpe_model_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *Tunnel) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *Tunnel) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *Tunnel) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *Tunnel) GetMcastInterface() string {
	if x != nil {
		return x.McastInterface
	}
	return ""
}

func (x *Tunnel) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

func (x *Tunnel) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *Tunnel) GetEncapVrfId() uint32 {
	if x != nil {
		return x.EncapVrfId
	}
	return 0
}

func (x *Tunnel) GetDecapVrfId() uint32 {
	if x != nil {
		return x.DecapVrfId
	}
	return 0
}

// Bypass enables the ip4/ip6-vxlan-gpe-bypass features on an interface
// (sw_interface_set_vxlan_gpe_bypass). Write-only: VPP has no dump for it.
type Bypass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Ipv4          bool                   `protobuf:"varint,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          bool                   `protobuf:"varint,3,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bypass) Reset() {
	*x = Bypass{}
	mi := &file_vxlan_gpe_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bypass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bypass) ProtoMessage() {}

func (x *Bypass) ProtoReflect() protoreflect.Message {
	mi := &file_vxlan_gpe_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bypass.ProtoReflect.Descriptor instead.
func (*Bypass) Descriptor() ([]byte, []int) {
	return file_vxlan_gpe_model_proto_rawDescGZIP(), []int{1}
}

func (x *Bypass) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Bypass) GetIpv4() bool {
	if x != nil {
		return x.Ipv4
	}
	return false
}

func (x *Bypass) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

var File_vxlan_gpe_model_proto protoreflect.FileDescriptor

const file_vxlan_gpe_model_proto_rawDesc = "" +
	"\n" +
	"\x15vxlan_gpe/model.proto\x12 ngfw.agent.descriptors.vxlan_gpe\"\xd1\x02\n" +
	"\x06Tunnel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05local\x18\x02 \x01(\tR\x05local\x12\x16\n" +
	"\x06remote\x18\x03 \x01(\tR\x06remote\x12\x1d\n" +
	"\n" +
	"local_port\x18\x04 \x01(\rR\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x05 \x01(\rR\n" +
	"remotePort\x12'\n" +
	"\x0fmcast_interface\x18\x06 \x01(\tR\x0emcastInterface\x12\x10\n" +
	"\x03vni\x18\a \x01(\rR\x03vni\x12F\n" +
	"\bprotocol\x18\b \x01(\x0e2*.ngfw.agent.descriptors.vxlan_gpe.ProtocolR\bprotocol\x12 \n" +
	"\fencap_vrf_id\x18\t \x01(\rR\n" +
	"encapVrfId\x12 \n" +
	"\fdecap_vrf_id\x18\n" +
	" \x01(\rR\n" +
	"decapVrfId\"N\n" +
	"\x06Bypass\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x12\n" +
	"\x04ipv4\x18\x02 \x01(\bR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x03 \x01(\bR\x04ipv6*M\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03IP4\x10\x01\x12\a\n" +
	"\x03IP6\x10\x02\x12\f\n" +
	"\bETHERNET\x10\x03\x12\a\n" +
	"\x03NSH\x10\x04B5Z3ngfw/agent/internal/descriptors/vxlan_gpe;vxlan_gpeb\x06proto3"

var (
	file_vxlan_gpe_model_proto_rawDescOnce sync.Once
	file_vxlan_gpe_model_proto_rawDescData []byte
)

func file_vxlan_gpe_model_proto_rawDescGZIP() []byte {
	file_vxlan_gpe_model_proto_rawDescOnce.Do(func() {
		file_vxlan_gpe_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vxlan_gpe_model_proto_rawDesc), len(file_vxlan_gpe_model_proto_rawDesc)))
	})
	return file_vxlan_gpe_model_proto_rawDescData
}

var file_vxlan_gpe_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vxlan_gpe_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vxlan_gpe_model_proto_goTypes = []any{
	(Protocol)(0),  // 0: ngfw.agent.descriptors.vxlan_gpe.Protocol
	(*Tunnel)(nil), // 1: ngfw.agent.descriptors.vxlan_gpe.Tunnel
	(*Bypass)(nil), // 2: ngfw.agent.descriptors.vxlan_gpe.Bypass
}
var file_vxlan_gpe_model_proto_depIdxs = []int32{
	0, // 0: ngfw.agent.descriptors.vxlan_gpe.Tunnel.protocol:type_name -> ngfw.agent.descriptors.vxlan_gpe.Protocol
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vxlan_gpe_model_proto_init() }
func file_vxlan_gpe_model_proto_init() {
	if File_vxlan_gpe_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vxlan_gpe_model_proto_rawDesc), len(file_vxlan_gpe_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vxlan_gpe_model_proto_goTypes,
		DependencyIndexes: file_vxlan_gpe_model_proto_depIdxs,
		EnumInfos:         file_vxlan_gpe_model_proto_enumTypes,
		MessageInfos:      file_vxlan_gpe_model_proto_msgTypes,
	}.Build()
	File_vxlan_gpe_model_proto = out.File
	file_vxlan_gpe_model_proto_goTypes = nil
	file_vxlan_gpe_model_proto_depIdxs = nil
}
