// Desired-state model of the interface-attribute and sub-interface descriptors (task DF-1).
// Agent-internal: these types are the Value of scheduler.KV for the interface.* descriptors.
// P08 promotes them to packages/proto when the API starts sending desired state (contract PR).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: model.proto

package iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RxModeKind int32

const (
	RxModeKind_RX_MODE_KIND_UNSPECIFIED RxModeKind = 0
	RxModeKind_RX_MODE_KIND_POLLING     RxModeKind = 1
	RxModeKind_RX_MODE_KIND_INTERRUPT   RxModeKind = 2
	RxModeKind_RX_MODE_KIND_ADAPTIVE    RxModeKind = 3
)

// Enum value maps for RxModeKind.
var (
	RxModeKind_name = map[int32]string{
		0: "RX_MODE_KIND_UNSPECIFIED",
		1: "RX_MODE_KIND_POLLING",
		2: "RX_MODE_KIND_INTERRUPT",
		3: "RX_MODE_KIND_ADAPTIVE",
	}
	RxModeKind_value = map[string]int32{
		"RX_MODE_KIND_UNSPECIFIED": 0,
		"RX_MODE_KIND_POLLING":     1,
		"RX_MODE_KIND_INTERRUPT":   2,
		"RX_MODE_KIND_ADAPTIVE":    3,
	}
)

func (x RxModeKind) Enum() *RxModeKind {
	p := new(RxModeKind)
	*p = x
	return p
}

func (x RxModeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RxModeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[0].Descriptor()
}

func (RxModeKind) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[0]
}

func (x RxModeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RxModeKind.Descriptor instead.
func (RxModeKind) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

// AdminState marks an interface administratively UP. Presence of the object means "up";
// deleting it sets the interface down (interface.admin-state).
type AdminState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full scheduler key of the interface, e.g. "interface.loopback/loop201".
	Interface     string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminState) Reset() {
	*x = AdminState{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminState) ProtoMessage() {}

func (x *AdminState) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminState.ProtoReflect.Descriptor instead.
func (*AdminState) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *AdminState) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

// Mtu is the per-protocol MTU set (sw_interface_set_mtu). 0 = not set (VPP inherits the link MTU).
type Mtu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Mtu           uint32                 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"` // L3 (default) MTU
	Ip4           uint32                 `protobuf:"varint,3,opt,name=ip4,proto3" json:"ip4,omitempty"`
	Ip6           uint32                 `protobuf:"varint,4,opt,name=ip6,proto3" json:"ip6,omitempty"`
	Mpls          uint32                 `protobuf:"varint,5,opt,name=mpls,proto3" json:"mpls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mtu) Reset() {
	*x = Mtu{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mtu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mtu) ProtoMessage() {}

func (x *Mtu) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mtu.ProtoReflect.Descriptor instead.
func (*Mtu) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *Mtu) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Mtu) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *Mtu) GetIp4() uint32 {
	if x != nil {
		return x.Ip4
	}
	return 0
}

func (x *Mtu) GetIp6() uint32 {
	if x != nil {
		return x.Ip6
	}
	return 0
}

func (x *Mtu) GetMpls() uint32 {
	if x != nil {
		return x.Mpls
	}
	return 0
}

// MacAddress sets the interface's L2 address (sw_interface_set_mac_address), lower-case "aa:bb:cc:dd:ee:ff".
type MacAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MacAddress) Reset() {
	*x = MacAddress{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MacAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacAddress) ProtoMessage() {}

func (x *MacAddress) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacAddress.ProtoReflect.Descriptor instead.
func (*MacAddress) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *MacAddress) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *MacAddress) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

// Promisc enables promiscuous mode (sw_interface_set_promisc). Presence = on.
type Promisc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promisc) Reset() {
	*x = Promisc{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promisc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promisc) ProtoMessage() {}

func (x *Promisc) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promisc.ProtoReflect.Descriptor instead.
func (*Promisc) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *Promisc) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

// RxMode sets the rx mode of every rx queue of an interface (sw_interface_set_rx_mode). The
// object exists only for non-polling modes: polling is VPP's default and is what Delete restores.
type RxMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Mode          RxModeKind             `protobuf:"varint,2,opt,name=mode,proto3,enum=vrx.agent.iface.RxModeKind" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RxMode) Reset() {
	*x = RxMode{}
	mi := &file_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RxMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RxMode) ProtoMessage() {}

func (x *RxMode) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RxMode.ProtoReflect.Descriptor instead.
func (*RxMode) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *RxMode) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RxMode) GetMode() RxModeKind {
	if x != nil {
		return x.Mode
	}
	return RxModeKind_RX_MODE_KIND_UNSPECIFIED
}

// RxPlacement pins one rx queue to a worker thread (sw_interface_set_rx_placement). worker is the
// 0-based worker number (worker 0 = VPP thread 1). Queues on the main thread have no object.
type RxPlacement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Queue         uint32                 `protobuf:"varint,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Worker        uint32                 `protobuf:"varint,3,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RxPlacement) Reset() {
	*x = RxPlacement{}
	mi := &file_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RxPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RxPlacement) ProtoMessage() {}

func (x *RxPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RxPlacement.ProtoReflect.Descriptor instead.
func (*RxPlacement) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5}
}

func (x *RxPlacement) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RxPlacement) GetQueue() uint32 {
	if x != nil {
		return x.Queue
	}
	return 0
}

func (x *RxPlacement) GetWorker() uint32 {
	if x != nil {
		return x.Worker
	}
	return 0
}

// Subinterface is a create_subif sub-interface. Its id is "<parent id>.<sub_id>", which is also
// how VPP names it. Tags: untagged/default_subif → 0 tags; inner_vlan or inner_vlan_any → 2 tags;
// otherwise 1 tag.
type Subinterface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full scheduler key of the parent interface.
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	SubId         uint32 `protobuf:"varint,2,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	OuterVlan     uint32 `protobuf:"varint,3,opt,name=outer_vlan,json=outerVlan,proto3" json:"outer_vlan,omitempty"`
	InnerVlan     uint32 `protobuf:"varint,4,opt,name=inner_vlan,json=innerVlan,proto3" json:"inner_vlan,omitempty"`
	Dot1Ad        bool   `protobuf:"varint,5,opt,name=dot1ad,proto3" json:"dot1ad,omitempty"`
	ExactMatch    bool   `protobuf:"varint,6,opt,name=exact_match,json=exactMatch,proto3" json:"exact_match,omitempty"`
	DefaultSubif  bool   `protobuf:"varint,7,opt,name=default_subif,json=defaultSubif,proto3" json:"default_subif,omitempty"`
	Untagged      bool   `protobuf:"varint,8,opt,name=untagged,proto3" json:"untagged,omitempty"`
	OuterVlanAny  bool   `protobuf:"varint,9,opt,name=outer_vlan_any,json=outerVlanAny,proto3" json:"outer_vlan_any,omitempty"`
	InnerVlanAny  bool   `protobuf:"varint,10,opt,name=inner_vlan_any,json=innerVlanAny,proto3" json:"inner_vlan_any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subinterface) Reset() {
	*x = Subinterface{}
	mi := &file_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subinterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subinterface) ProtoMessage() {}

func (x *Subinterface) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subinterface.ProtoReflect.Descriptor instead.
func (*Subinterface) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6}
}

func (x *Subinterface) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Subinterface) GetSubId() uint32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *Subinterface) GetOuterVlan() uint32 {
	if x != nil {
		return x.OuterVlan
	}
	return 0
}

func (x *Subinterface) GetInnerVlan() uint32 {
	if x != nil {
		return x.InnerVlan
	}
	return 0
}

func (x *Subinterface) GetDot1Ad() bool {
	if x != nil {
		return x.Dot1Ad
	}
	return false
}

func (x *Subinterface) GetExactMatch() bool {
	if x != nil {
		return x.ExactMatch
	}
	return false
}

func (x *Subinterface) GetDefaultSubif() bool {
	if x != nil {
		return x.DefaultSubif
	}
	return false
}

func (x *Subinterface) GetUntagged() bool {
	if x != nil {
		return x.Untagged
	}
	return false
}

func (x *Subinterface) GetOuterVlanAny() bool {
	if x != nil {
		return x.OuterVlanAny
	}
	return false
}

func (x *Subinterface) GetInnerVlanAny() bool {
	if x != nil {
		return x.InnerVlanAny
	}
	return false
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\x0fvrx.agent.iface\"*\n" +
	"\n" +
	"AdminState\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\"m\n" +
	"\x03Mtu\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\rR\x03mtu\x12\x10\n" +
	"\x03ip4\x18\x03 \x01(\rR\x03ip4\x12\x10\n" +
	"\x03ip6\x18\x04 \x01(\rR\x03ip6\x12\x12\n" +
	"\x04mpls\x18\x05 \x01(\rR\x04mpls\"<\n" +
	"\n" +
	"MacAddress\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\"'\n" +
	"\aPromisc\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\"W\n" +
	"\x06RxMode\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12/\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1b.vrx.agent.iface.RxModeKindR\x04mode\"Y\n" +
	"\vRxPlacement\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\rR\x05queue\x12\x16\n" +
	"\x06worker\x18\x03 \x01(\rR\x06worker\"\xc1\x02\n" +
	"\fSubinterface\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x15\n" +
	"\x06sub_id\x18\x02 \x01(\rR\x05subId\x12\x1d\n" +
	"\n" +
	"outer_vlan\x18\x03 \x01(\rR\touterVlan\x12\x1d\n" +
	"\n" +
	"inner_vlan\x18\x04 \x01(\rR\tinnerVlan\x12\x16\n" +
	"\x06dot1ad\x18\x05 \x01(\bR\x06dot1ad\x12\x1f\n" +
	"\vexact_match\x18\x06 \x01(\bR\n" +
	"exactMatch\x12#\n" +
	"\rdefault_subif\x18\a \x01(\bR\fdefaultSubif\x12\x1a\n" +
	"\buntagged\x18\b \x01(\bR\buntagged\x12$\n" +
	"\x0eouter_vlan_any\x18\t \x01(\bR\fouterVlanAny\x12$\n" +
	"\x0einner_vlan_any\x18\n" +
	" \x01(\bR\finnerVlanAny*{\n" +
	"\n" +
	"RxModeKind\x12\x1c\n" +
	"\x18RX_MODE_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RX_MODE_KIND_POLLING\x10\x01\x12\x1a\n" +
	"\x16RX_MODE_KIND_INTERRUPT\x10\x02\x12\x19\n" +
	"\x15RX_MODE_KIND_ADAPTIVE\x10\x03B1Z/ngfw/agent/internal/descriptors/interface;ifaceb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_model_proto_goTypes = []any{
	(RxModeKind)(0),      // 0: vrx.agent.iface.RxModeKind
	(*AdminState)(nil),   // 1: vrx.agent.iface.AdminState
	(*Mtu)(nil),          // 2: vrx.agent.iface.Mtu
	(*MacAddress)(nil),   // 3: vrx.agent.iface.MacAddress
	(*Promisc)(nil),      // 4: vrx.agent.iface.Promisc
	(*RxMode)(nil),       // 5: vrx.agent.iface.RxMode
	(*RxPlacement)(nil),  // 6: vrx.agent.iface.RxPlacement
	(*Subinterface)(nil), // 7: vrx.agent.iface.Subinterface
}
var file_model_proto_depIdxs = []int32{
	0, // 0: vrx.agent.iface.RxMode.mode:type_name -> vrx.agent.iface.RxModeKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		EnumInfos:         file_model_proto_enumTypes,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
