// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: unnumbered_model.proto

package iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Unnumbered borrows both address families from the donor interface.
type Unnumbered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Donor         string                 `protobuf:"bytes,2,opt,name=donor,proto3" json:"donor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unnumbered) Reset() {
	*x = Unnumbered{}
	mi := &file_unnumbered_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unnumbered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unnumbered) ProtoMessage() {}

func (x *Unnumbered) ProtoReflect() protoreflect.Message {
	mi := &file_unnumbered_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unnumbered.ProtoReflect.Descriptor instead.
func (*Unnumbered) Descriptor() ([]byte, []int) {
	return file_unnumbered_model_proto_rawDescGZIP(), []int{0}
}

func (x *Unnumbered) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Unnumbered) GetDonor() string {
	if x != nil {
		return x.Donor
	}
	return ""
}

var File_unnumbered_model_proto protoreflect.FileDescriptor

const file_unnumbered_model_proto_rawDesc = "" +
	"\n" +
	"\x16unnumbered_model.proto\x12\x10ngfw.agent.iface\"@\n" +
	"\n" +
	"Unnumbered\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x14\n" +
	"\x05donor\x18\x02 \x01(\tR\x05donorB1Z/ngfw/agent/internal/descriptors/interface;ifaceb\x06proto3"

var (
	file_unnumbered_model_proto_rawDescOnce sync.Once
	file_unnumbered_model_proto_rawDescData []byte
)

func file_unnumbered_model_proto_rawDescGZIP() []byte {
	file_unnumbered_model_proto_rawDescOnce.Do(func() {
		file_unnumbered_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unnumbered_model_proto_rawDesc), len(file_unnumbered_model_proto_rawDesc)))
	})
	return file_unnumbered_model_proto_rawDescData
}

var file_unnumbered_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_unnumbered_model_proto_goTypes = []any{
	(*Unnumbered)(nil), // 0: ngfw.agent.iface.Unnumbered
}
var file_unnumbered_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unnumbered_model_proto_init() }
func file_unnumbered_model_proto_init() {
	if File_unnumbered_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unnumbered_model_proto_rawDesc), len(file_unnumbered_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unnumbered_model_proto_goTypes,
		DependencyIndexes: file_unnumbered_model_proto_depIdxs,
		MessageInfos:      file_unnumbered_model_proto_msgTypes,
	}.Build()
	File_unnumbered_model_proto = out.File
	file_unnumbered_model_proto_goTypes = nil
	file_unnumbered_model_proto_depIdxs = nil
}
