// Desired state of the urpf descriptor (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: urpf/model.proto

package urpf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	df2 "ngfw/agent/internal/descriptors/df2"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode mirrors urpf.urpf_mode.
type Interface_Mode int32

const (
	Interface_OFF    Interface_Mode = 0
	Interface_LOOSE  Interface_Mode = 1
	Interface_STRICT Interface_Mode = 2
)

// Enum value maps for Interface_Mode.
var (
	Interface_Mode_name = map[int32]string{
		0: "OFF",
		1: "LOOSE",
		2: "STRICT",
	}
	Interface_Mode_value = map[string]int32{
		"OFF":    0,
		"LOOSE":  1,
		"STRICT": 2,
	}
)

func (x Interface_Mode) Enum() *Interface_Mode {
	p := new(Interface_Mode)
	*p = x
	return p
}

func (x Interface_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interface_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_urpf_model_proto_enumTypes[0].Descriptor()
}

func (Interface_Mode) Type() protoreflect.EnumType {
	return &file_urpf_model_proto_enumTypes[0]
}

func (x Interface_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interface_Mode.Descriptor instead.
func (Interface_Mode) EnumDescriptor() ([]byte, []int) {
	return file_urpf_model_proto_rawDescGZIP(), []int{0, 0}
}

// Direction of the check.
type Interface_Direction int32

const (
	Interface_RX Interface_Direction = 0
	Interface_TX Interface_Direction = 1
)

// Enum value maps for Interface_Direction.
var (
	Interface_Direction_name = map[int32]string{
		0: "RX",
		1: "TX",
	}
	Interface_Direction_value = map[string]int32{
		"RX": 0,
		"TX": 1,
	}
)

func (x Interface_Direction) Enum() *Interface_Direction {
	p := new(Interface_Direction)
	*p = x
	return p
}

func (x Interface_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interface_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_urpf_model_proto_enumTypes[1].Descriptor()
}

func (Interface_Direction) Type() protoreflect.EnumType {
	return &file_urpf_model_proto_enumTypes[1]
}

func (x Interface_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interface_Direction.Descriptor instead.
func (Interface_Direction) EnumDescriptor() ([]byte, []int) {
	return file_urpf_model_proto_rawDescGZIP(), []int{0, 1}
}

// Interface is one uRPF check on an interface, per address family and direction
// (urpf_update_v2). Mode OFF is never desired: it is what Delete sends.
type Interface struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Interface string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Af        df2.AddressFamily      `protobuf:"varint,2,opt,name=af,proto3,enum=ngfw.agent.descriptors.df2.AddressFamily" json:"af,omitempty"`
	Direction Interface_Direction    `protobuf:"varint,3,opt,name=direction,proto3,enum=ngfw.agent.descriptors.urpf.Interface_Direction" json:"direction,omitempty"`
	Mode      Interface_Mode         `protobuf:"varint,4,opt,name=mode,proto3,enum=ngfw.agent.descriptors.urpf.Interface_Mode" json:"mode,omitempty"`
	// FIB table used for the lookup (VPP reports the resolved table, so it is explicit here:
	// 0 = default table; the API layer fills the interface's VRF).
	TableId       uint32 `protobuf:"varint,5,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_urpf_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_urpf_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_urpf_model_proto_rawDescGZIP(), []int{0}
}

func (x *Interface) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Interface) GetAf() df2.AddressFamily {
	if x != nil {
		return x.Af
	}
	return df2.AddressFamily(0)
}

func (x *Interface) GetDirection() Interface_Direction {
	if x != nil {
		return x.Direction
	}
	return Interface_RX
}

func (x *Interface) GetMode() Interface_Mode {
	if x != nil {
		return x.Mode
	}
	return Interface_OFF
}

func (x *Interface) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

var File_urpf_model_proto protoreflect.FileDescriptor

const file_urpf_model_proto_rawDesc = "" +
	"\n" +
	"\x10urpf/model.proto\x12\x1bngfw.agent.descriptors.urpf\x1a\rdf2/df2.proto\"\xd5\x02\n" +
	"\tInterface\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x129\n" +
	"\x02af\x18\x02 \x01(\x0e2).ngfw.agent.descriptors.df2.AddressFamilyR\x02af\x12N\n" +
	"\tdirection\x18\x03 \x01(\x0e20.ngfw.agent.descriptors.urpf.Interface.DirectionR\tdirection\x12?\n" +
	"\x04mode\x18\x04 \x01(\x0e2+.ngfw.agent.descriptors.urpf.Interface.ModeR\x04mode\x12\x19\n" +
	"\btable_id\x18\x05 \x01(\rR\atableId\"&\n" +
	"\x04Mode\x12\a\n" +
	"\x03OFF\x10\x00\x12\t\n" +
	"\x05LOOSE\x10\x01\x12\n" +
	"\n" +
	"\x06STRICT\x10\x02\"\x1b\n" +
	"\tDirection\x12\x06\n" +
	"\x02RX\x10\x00\x12\x06\n" +
	"\x02TX\x10\x01B+Z)ngfw/agent/internal/descriptors/urpf;urpfb\x06proto3"

var (
	file_urpf_model_proto_rawDescOnce sync.Once
	file_urpf_model_proto_rawDescData []byte
)

func file_urpf_model_proto_rawDescGZIP() []byte {
	file_urpf_model_proto_rawDescOnce.Do(func() {
		file_urpf_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urpf_model_proto_rawDesc), len(file_urpf_model_proto_rawDesc)))
	})
	return file_urpf_model_proto_rawDescData
}

var file_urpf_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_urpf_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_urpf_model_proto_goTypes = []any{
	(Interface_Mode)(0),      // 0: ngfw.agent.descriptors.urpf.Interface.Mode
	(Interface_Direction)(0), // 1: ngfw.agent.descriptors.urpf.Interface.Direction
	(*Interface)(nil),        // 2: ngfw.agent.descriptors.urpf.Interface
	(df2.AddressFamily)(0),   // 3: ngfw.agent.descriptors.df2.AddressFamily
}
var file_urpf_model_proto_depIdxs = []int32{
	3, // 0: ngfw.agent.descriptors.urpf.Interface.af:type_name -> ngfw.agent.descriptors.df2.AddressFamily
	1, // 1: ngfw.agent.descriptors.urpf.Interface.direction:type_name -> ngfw.agent.descriptors.urpf.Interface.Direction
	0, // 2: ngfw.agent.descriptors.urpf.Interface.mode:type_name -> ngfw.agent.descriptors.urpf.Interface.Mode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_urpf_model_proto_init() }
func file_urpf_model_proto_init() {
	if File_urpf_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urpf_model_proto_rawDesc), len(file_urpf_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_urpf_model_proto_goTypes,
		DependencyIndexes: file_urpf_model_proto_depIdxs,
		EnumInfos:         file_urpf_model_proto_enumTypes,
		MessageInfos:      file_urpf_model_proto_msgTypes,
	}.Build()
	File_urpf_model_proto = out.File
	file_urpf_model_proto_goTypes = nil
	file_urpf_model_proto_depIdxs = nil
}
