// Desired state of the ip_neighbor descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ip_neighbor/model.proto

package ipneighbor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	df2 "ngfw/agent/internal/descriptors/df2"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Neighbor is one static ARP / ND entry (ip_neighbor_add_del). Configured neighbours are
// always static; VPP's learned entries are never part of desired or retrieved state.
type Neighbor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VPP interface name (dependency interface/<name>).
	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// IPv4 or IPv6 address, canonical netip text.
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Lower-case colon-separated MAC.
	MacAddress string `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// IP_API_NEIGHBOR_FLAG_NO_FIB_ENTRY: do not add the /32 or /128 adjacency FIB entry.
	NoFibEntry    bool `protobuf:"varint,4,opt,name=no_fib_entry,json=noFibEntry,proto3" json:"no_fib_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Neighbor) Reset() {
	*x = Neighbor{}
	mi := &file_ip_neighbor_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Neighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbor) ProtoMessage() {}

func (x *Neighbor) ProtoReflect() protoreflect.Message {
	mi := &file_ip_neighbor_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbor.ProtoReflect.Descriptor instead.
func (*Neighbor) Descriptor() ([]byte, []int) {
	return file_ip_neighbor_model_proto_rawDescGZIP(), []int{0}
}

func (x *Neighbor) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Neighbor) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Neighbor) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Neighbor) GetNoFibEntry() bool {
	if x != nil {
		return x.NoFibEntry
	}
	return false
}

// Config is the per-address-family neighbour database configuration (ip_neighbor_config).
// It is a singleton per AF: it always exists in VPP, so Retrieve always returns both
// families and Delete restores the VPP defaults.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Af    df2.AddressFamily      `protobuf:"varint,1,opt,name=af,proto3,enum=ngfw.agent.descriptors.df2.AddressFamily" json:"af,omitempty"`
	// Maximum number of entries (VPP default 50000).
	MaxNumber uint32 `protobuf:"varint,2,opt,name=max_number,json=maxNumber,proto3" json:"max_number,omitempty"`
	// Maximum age in seconds, 0 = never age out (VPP default 0).
	MaxAge uint32 `protobuf:"varint,3,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	// Recycle the oldest entry when the limit is reached (VPP default false).
	Recycle       bool `protobuf:"varint,4,opt,name=recycle,proto3" json:"recycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_ip_neighbor_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_ip_neighbor_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_ip_neighbor_model_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetAf() df2.AddressFamily {
	if x != nil {
		return x.Af
	}
	return df2.AddressFamily(0)
}

func (x *Config) GetMaxNumber() uint32 {
	if x != nil {
		return x.MaxNumber
	}
	return 0
}

func (x *Config) GetMaxAge() uint32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Config) GetRecycle() bool {
	if x != nil {
		return x.Recycle
	}
	return false
}

var File_ip_neighbor_model_proto protoreflect.FileDescriptor

const file_ip_neighbor_model_proto_rawDesc = "" +
	"\n" +
	"\x17ip_neighbor/model.proto\x12!ngfw.agent.descriptors.ipneighbor\x1a\rdf2/df2.proto\"\x8a\x01\n" +
	"\bNeighbor\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12 \n" +
	"\fno_fib_entry\x18\x04 \x01(\bR\n" +
	"noFibEntry\"\x95\x01\n" +
	"\x06Config\x129\n" +
	"\x02af\x18\x01 \x01(\x0e2).ngfw.agent.descriptors.df2.AddressFamilyR\x02af\x12\x1d\n" +
	"\n" +
	"max_number\x18\x02 \x01(\rR\tmaxNumber\x12\x17\n" +
	"\amax_age\x18\x03 \x01(\rR\x06maxAge\x12\x18\n" +
	"\arecycle\x18\x04 \x01(\bR\arecycleB8Z6ngfw/agent/internal/descriptors/ip_neighbor;ipneighborb\x06proto3"

var (
	file_ip_neighbor_model_proto_rawDescOnce sync.Once
	file_ip_neighbor_model_proto_rawDescData []byte
)

func file_ip_neighbor_model_proto_rawDescGZIP() []byte {
	file_ip_neighbor_model_proto_rawDescOnce.Do(func() {
		file_ip_neighbor_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ip_neighbor_model_proto_rawDesc), len(file_ip_neighbor_model_proto_rawDesc)))
	})
	return file_ip_neighbor_model_proto_rawDescData
}

var file_ip_neighbor_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ip_neighbor_model_proto_goTypes = []any{
	(*Neighbor)(nil),       // 0: ngfw.agent.descriptors.ipneighbor.Neighbor
	(*Config)(nil),         // 1: ngfw.agent.descriptors.ipneighbor.Config
	(df2.AddressFamily)(0), // 2: ngfw.agent.descriptors.df2.AddressFamily
}
var file_ip_neighbor_model_proto_depIdxs = []int32{
	2, // 0: ngfw.agent.descriptors.ipneighbor.Config.af:type_name -> ngfw.agent.descriptors.df2.AddressFamily
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ip_neighbor_model_proto_init() }
func file_ip_neighbor_model_proto_init() {
	if File_ip_neighbor_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ip_neighbor_model_proto_rawDesc), len(file_ip_neighbor_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ip_neighbor_model_proto_goTypes,
		DependencyIndexes: file_ip_neighbor_model_proto_depIdxs,
		MessageInfos:      file_ip_neighbor_model_proto_msgTypes,
	}.Build()
	File_ip_neighbor_model_proto = out.File
	file_ip_neighbor_model_proto_goTypes = nil
	file_ip_neighbor_model_proto_depIdxs = nil
}
