// Desired state of the arp (proxy ARP) descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: arp/model.proto

package arp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProxyRange is one proxy-ARP address range in a FIB table (proxy_arp_add_del).
type ProxyRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FIB table id (dependency vrf/<id> unless 0).
	TableId uint32 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// First IPv4 address of the range.
	Low string `protobuf:"bytes,2,opt,name=low,proto3" json:"low,omitempty"`
	// Last IPv4 address of the range.
	High          string `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRange) Reset() {
	*x = ProxyRange{}
	mi := &file_arp_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRange) ProtoMessage() {}

func (x *ProxyRange) ProtoReflect() protoreflect.Message {
	mi := &file_arp_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRange.ProtoReflect.Descriptor instead.
func (*ProxyRange) Descriptor() ([]byte, []int) {
	return file_arp_model_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyRange) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *ProxyRange) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *ProxyRange) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

// ProxyInterface enables proxy ARP on an interface (proxy_arp_intfc_enable_disable).
type ProxyInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyInterface) Reset() {
	*x = ProxyInterface{}
	mi := &file_arp_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyInterface) ProtoMessage() {}

func (x *ProxyInterface) ProtoReflect() protoreflect.Message {
	mi := &file_arp_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyInterface.ProtoReflect.Descriptor instead.
func (*ProxyInterface) Descriptor() ([]byte, []int) {
	return file_arp_model_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyInterface) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

var File_arp_model_proto protoreflect.FileDescriptor

const file_arp_model_proto_rawDesc = "" +
	"\n" +
	"\x0farp/model.proto\x12\x1angfw.agent.descriptors.arp\"M\n" +
	"\n" +
	"ProxyRange\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\rR\atableId\x12\x10\n" +
	"\x03low\x18\x02 \x01(\tR\x03low\x12\x12\n" +
	"\x04high\x18\x03 \x01(\tR\x04high\".\n" +
	"\x0eProxyInterface\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterfaceB)Z'ngfw/agent/internal/descriptors/arp;arpb\x06proto3"

var (
	file_arp_model_proto_rawDescOnce sync.Once
	file_arp_model_proto_rawDescData []byte
)

func file_arp_model_proto_rawDescGZIP() []byte {
	file_arp_model_proto_rawDescOnce.Do(func() {
		file_arp_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arp_model_proto_rawDesc), len(file_arp_model_proto_rawDesc)))
	})
	return file_arp_model_proto_rawDescData
}

var file_arp_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_arp_model_proto_goTypes = []any{
	(*ProxyRange)(nil),     // 0: ngfw.agent.descriptors.arp.ProxyRange
	(*ProxyInterface)(nil), // 1: ngfw.agent.descriptors.arp.ProxyInterface
}
var file_arp_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arp_model_proto_init() }
func file_arp_model_proto_init() {
	if File_arp_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arp_model_proto_rawDesc), len(file_arp_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arp_model_proto_goTypes,
		DependencyIndexes: file_arp_model_proto_depIdxs,
		MessageInfos:      file_arp_model_proto_msgTypes,
	}.Build()
	File_arp_model_proto = out.File
	file_arp_model_proto_goTypes = nil
	file_arp_model_proto_depIdxs = nil
}
