// Desired state of the pppoe descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pppoe/model.proto

package pppoe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session is one PPPoE session interface (pppoe_add_del_session / pppoe_session_dump). The
// object id is "<client_mac>/<session_id>", which is also the owner tag.
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PPPoE session id (1–65535).
	SessionId uint32 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Client IP address (IPv4 or IPv6).
	ClientIp string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// Client MAC address (canonical lower-case colon form).
	ClientMac string `protobuf:"bytes,3,opt,name=client_mac,json=clientMac,proto3" json:"client_mac,omitempty"`
	// Decap FIB table id (dependency vrf/<id> unless 0).
	DecapVrfId    uint32 `protobuf:"varint,4,opt,name=decap_vrf_id,json=decapVrfId,proto3" json:"decap_vrf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_pppoe_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_pppoe_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_pppoe_model_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Session) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *Session) GetClientMac() string {
	if x != nil {
		return x.ClientMac
	}
	return ""
}

func (x *Session) GetDecapVrfId() uint32 {
	if x != nil {
		return x.DecapVrfId
	}
	return 0
}

// Cp punts PPPoE control-plane packets (discovery, LCP, …) to an interface
// (pppoe_add_del_cp). Write-only: VPP has no dump for it.
type Cp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cp) Reset() {
	*x = Cp{}
	mi := &file_pppoe_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cp) ProtoMessage() {}

func (x *Cp) ProtoReflect() protoreflect.Message {
	mi := &file_pppoe_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cp.ProtoReflect.Descriptor instead.
func (*Cp) Descriptor() ([]byte, []int) {
	return file_pppoe_model_proto_rawDescGZIP(), []int{1}
}

func (x *Cp) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

var File_pppoe_model_proto protoreflect.FileDescriptor

const file_pppoe_model_proto_rawDesc = "" +
	"\n" +
	"\x11pppoe/model.proto\x12\x1cngfw.agent.descriptors.pppoe\"\x86\x01\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"client_mac\x18\x03 \x01(\tR\tclientMac\x12 \n" +
	"\fdecap_vrf_id\x18\x04 \x01(\rR\n" +
	"decapVrfId\"\"\n" +
	"\x02Cp\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterfaceB-Z+ngfw/agent/internal/descriptors/pppoe;pppoeb\x06proto3"

var (
	file_pppoe_model_proto_rawDescOnce sync.Once
	file_pppoe_model_proto_rawDescData []byte
)

func file_pppoe_model_proto_rawDescGZIP() []byte {
	file_pppoe_model_proto_rawDescOnce.Do(func() {
		file_pppoe_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pppoe_model_proto_rawDesc), len(file_pppoe_model_proto_rawDesc)))
	})
	return file_pppoe_model_proto_rawDescData
}

var file_pppoe_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pppoe_model_proto_goTypes = []any{
	(*Session)(nil), // 0: ngfw.agent.descriptors.pppoe.Session
	(*Cp)(nil),      // 1: ngfw.agent.descriptors.pppoe.Cp
}
var file_pppoe_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pppoe_model_proto_init() }
func file_pppoe_model_proto_init() {
	if File_pppoe_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pppoe_model_proto_rawDesc), len(file_pppoe_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pppoe_model_proto_goTypes,
		DependencyIndexes: file_pppoe_model_proto_depIdxs,
		MessageInfos:      file_pppoe_model_proto_msgTypes,
	}.Build()
	File_pppoe_model_proto = out.File
	file_pppoe_model_proto_goTypes = nil
	file_pppoe_model_proto_depIdxs = nil
}
