#!/usr/bin/env python3
"""Generate the `vrx._generated` package of the Python SDK from the VRX OpenAPI document (stdlib only).

    python3 tools/gen.py <openapi.json> [<out dir>]     (default out dir: vrx/_generated next to this script's parent)

Output (deterministic — `sdk/gen.sh --check` compares it with the committed tree; never hand-edit):
  operations.py  one method per operationId on the `Operations` mixin + the `OPERATIONS` table
  models.py      TypedDicts for every component schema and every request/response body (functional syntax, so
                 any JSON key works); maps are `dict[str, …]`, enums/consts are `Literal[…]`
  secrets.py     RFC 6901 pointer patterns (`*` = any key/index) of write-only leaves (`writeOnly: true`, D-046)
                 and of secret references (`<kind>/<name>`, D-051) inside RootConfig — the SDK's redaction source
New schema domains, fields or operations need no hand-written client code: re-run `sdk/gen.sh`.
"""
from __future__ import annotations

import json
import keyword
import re
import sys
from pathlib import Path

HEADER = "# GENERATED by sdk/python/tools/gen.py from the VRX OpenAPI document ({title} {version}) — never edit.\n"
# every OpenAPI-provided string reaches the output only as a repr()/json literal, a clean() comment, or an ident()
_KIND = r"(?:psk|key|cert|password|token)"
SECRET_REF_RE = re.compile(r"^\^\(\?:" + _KIND + r"(?:\|" + _KIND + r")*\)\\?/")


IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class GenError(Exception):
    """The OpenAPI document cannot be rendered safely (a name that is not an identifier, …)."""


def clean(text: object, limit: int = 110) -> str:
    """An OpenAPI string made safe for a `#` comment: printable, one line, no backslashes, bounded."""
    out = "".join(ch if ch.isprintable() and ch not in "\\\u2028\u2029" else " " for ch in str(text))
    return out[:limit]


def ident(name: str, what: str) -> str:
    if not IDENT.match(name) or keyword.iskeyword(name):
        raise GenError(f"{what} {name!r} is not a safe Python identifier")
    return name


def snake(name: str) -> str:
    s = re.sub(r"[^0-9A-Za-z]+", "_", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower().strip("_")
    s = re.sub(r"_+", "_", s)
    return s + "_" if keyword.iskeyword(s) else s


def pascal(name: str) -> str:
    parts = re.split(r"[^0-9A-Za-z]+", name)
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    return out if out and not out[0].isdigit() else "N" + out


class Models:
    """JSON Schema (OpenAPI 3.1 dialect) → TypedDict source. Inline objects get names from their position."""

    def __init__(self, components: dict):
        self.components = components
        self.defs: dict[str, str] = {}  # name → source line(s)
        self.order: list[str] = []

    def ref_name(self, ref: str) -> str:
        return ident(pascal(ref.rsplit("/", 1)[-1]), "schema name")

    def type_of(self, s: object, name: str) -> str:
        if s is True or s == {} or s is None:
            return "Any"
        if not isinstance(s, dict):
            return "Any"
        if "$ref" in s:
            return f'"{self.ref_name(s["$ref"])}"'
        if "const" in s:
            return f"Literal[{s['const']!r}]"
        if "enum" in s:
            vals = [v for v in s["enum"] if v is not None]
            lit = f"Literal[{', '.join(repr(v) for v in vals)}]" if vals else "None"
            return f"Optional[{lit}]" if None in s["enum"] and vals else lit
        for comb in ("anyOf", "oneOf"):
            if comb in s:
                alts: list[str] = []
                for i, alt in enumerate(s[comb]):
                    t = self.type_of(alt, f"{name}{i + 1}" if len(s[comb]) > 1 else name)
                    if t not in alts:
                        alts.append(t)
                return alts[0] if len(alts) == 1 else f"Union[{', '.join(alts)}]"
        if "allOf" in s:
            return self.type_of(s["allOf"][0], name) if len(s["allOf"]) == 1 else "dict[str, Any]"
        t = s.get("type")
        if isinstance(t, list):
            alts = [self.type_of({**s, "type": x}, name) for x in t]
            return f"Union[{', '.join(dict.fromkeys(alts))}]"
        if t == "string":
            return "str"
        if t == "integer":
            return "int"
        if t == "number":
            return "float"
        if t == "boolean":
            return "bool"
        if t == "null":
            return "None"
        if t == "array":
            return f"list[{self.type_of(s.get('items'), name + 'Item')}]"
        if t == "object" or "properties" in s or "additionalProperties" in s:
            props = s.get("properties") or {}
            ap = s.get("additionalProperties")
            if not props:
                if isinstance(ap, dict) and ap:
                    return f"dict[str, {self.type_of(ap, name + 'Value')}]"
                return "dict[str, Any]"
            self.typed_dict(name, s)
            return f'"{name}"'
        return "Any"

    def typed_dict(self, name: str, s: dict) -> None:
        ident(name, "model name")
        if name in self.defs:
            return
        self.defs[name] = ""  # reserve (recursion)
        req = set(s.get("required") or [])
        fields = []
        for key in sorted(s.get("properties") or {}):
            t = self.type_of(s["properties"][key], name + pascal(key))
            fields.append(f"        {json.dumps(key)}: {'Required' if key in req else 'NotRequired'}[{t}],")
        doc = (s.get("description") or s.get("title") or "").replace("\\", "\\\\").replace('"""', "'''")
        src = f"{name} = TypedDict(\n    {json.dumps(name)},\n    {{\n" + "\n".join(fields) + "\n    },\n)\n"
        if doc:
            src = f"# {clean(doc.splitlines()[0] if doc.splitlines() else doc)}\n" + src
        self.defs[name] = src
        self.order.append(name)

    def alias(self, name: str, s: dict) -> None:
        t = self.type_of(s, name)
        if t != f'"{name}"' and name not in self.defs:
            self.defs[name] = f"{name} = {t.strip(chr(34)) if t.startswith(chr(34)) and t.endswith(chr(34)) else t}\n"
            self.order.append(name)


def secret_patterns(root: dict, components: dict) -> tuple[list[str], list[str]]:
    write_only: set[str] = set()
    refs: set[str] = set()

    def walk(s: object, ptr: str, depth: int, seen: frozenset) -> None:
        if not isinstance(s, dict) or depth > 40:
            return
        if "$ref" in s:
            name = s["$ref"].rsplit("/", 1)[-1]
            if name in seen:
                return
            walk(components.get(name), ptr, depth + 1, seen | {name})
            return
        if s.get("writeOnly") or (isinstance(s.get("x-vrx-ui"), dict) and s["x-vrx-ui"].get("secret")):
            write_only.add(ptr)
        if s.get("type") == "string" and isinstance(s.get("pattern"), str) and SECRET_REF_RE.search(s["pattern"]):
            refs.add(ptr)
        for comb in ("anyOf", "oneOf", "allOf"):
            for alt in s.get(comb) or []:
                walk(alt, ptr, depth + 1, seen)
        for k, v in (s.get("properties") or {}).items():
            walk(v, f"{ptr}/{k.replace('~', '~0').replace('/', '~1')}", depth + 1, seen)
        if isinstance(s.get("additionalProperties"), dict):
            walk(s["additionalProperties"], ptr + "/*", depth + 1, seen)
        if isinstance(s.get("items"), dict):
            walk(s["items"], ptr + "/*", depth + 1, seen)

    walk(root, "", 0, frozenset())
    return sorted(write_only), sorted(refs)


def body_schema(obj: dict | None) -> dict | None:
    if not obj:
        return None
    content = obj.get("content") or {}
    for ct in ("application/json", "application/problem+json"):
        if ct in content:
            return content[ct].get("schema", {})
    return None


def main() -> None:
    src = Path(sys.argv[1])
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / "vrx" / "_generated"
    doc = json.loads(src.read_text())
    comps = doc.get("components", {}).get("schemas", {})
    head = HEADER.format(title=clean(doc["info"].get("title"), 60), version=clean(doc["info"].get("version"), 30))
    models = Models(comps)
    for name in sorted(comps):
        models.alias(ident(pascal(name), "schema name"), comps[name])

    ops = []
    for path in sorted(doc["paths"]):
        for method in ("get", "post", "put", "patch", "delete"):
            op = doc["paths"][path].get(method)
            if not op:
                continue
            oid = op.get("operationId") or f"{method}_{path}"
            params = [p for p in op.get("parameters", []) if p.get("in") in ("path", "query")]
            req = body_schema(op.get("requestBody"))
            ok = next((c for c in ("200", "201", "204") if c in op.get("responses", {})), None)
            resp = body_schema(op["responses"].get(ok)) if ok else None
            ident(oid, "operationId")  # the raw name, not a sanitised one: silent renames could collide
            base = ident(pascal(oid), "operationId")
            ident(snake(oid), "operationId")
            for prm in params:
                ident(prm["name"], "parameter name")
                ident(snake(prm["name"]), "parameter name")
            if method.upper() not in ("GET", "POST", "PUT", "PATCH", "DELETE"):
                raise GenError(f"method {method!r}")
            req_t = models.type_of(req, base + "Body") if req is not None else None
            resp_t = "None" if ok == "204" else (models.type_of(resp, base + "Response") if resp is not None else "Any")
            ops.append((oid, method.upper(), path, op, params, req_t, resp_t))

    # ---- models.py
    lines = [head, "from __future__ import annotations\n",
             "from typing import Any, Literal, NotRequired, Optional, Required, TypedDict, Union\n\n",
             "__all__ = [\n" + "".join(f"    {json.dumps(n)},\n" for n in sorted(models.order)) + "]\n\n"]
    for n in models.order:
        lines.append(models.defs[n] + "\n")
    (out / "models.py").write_text("".join(lines).rstrip() + "\n")

    # ---- operations.py
    o = [head, "from __future__ import annotations\n\n", "from typing import TYPE_CHECKING, Any\n\n",
         "if TYPE_CHECKING:\n    from .models import *  # noqa: F403\n\n",
         "# operationId → (HTTP method, path template, path params, query params, has JSON body)\n",
         "OPERATIONS: dict[str, tuple[str, str, tuple[str, ...], tuple[str, ...], bool]] = {\n"]
    for oid, m, path, op, params, req_t, _ in ops:
        pp = tuple(p["name"] for p in params if p["in"] == "path")
        qp = tuple(p["name"] for p in params if p["in"] == "query")
        o.append(f"    {json.dumps(oid)}: ({json.dumps(m)}, {json.dumps(path)}, {pp!r}, {qp!r}, {req_t is not None}),\n")
    o.append("}\n\n\nclass Operations:\n")
    o.append('    """One method per API operation (generated). Transport, auth and errors come from `VrxSession._call`."""\n\n')
    o.append("    def _call(self, operation_id: str, path_params: dict[str, Any], query: dict[str, Any], body: Any = ...) -> Any:\n")
    o.append("        raise NotImplementedError\n")
    for oid, m, path, op, params, req_t, resp_t in ops:
        args = ["self"]
        pnames = {}
        for p in params:
            if p["in"] == "path":
                pnames[p["name"]] = snake(p["name"])
                args.append(f"{snake(p['name'])}: {'str' if p.get('schema', {}).get('type') != 'integer' else 'int'}")
        if req_t is not None:
            args.append(f"body: {req_t}")
        q = [p for p in params if p["in"] == "query"]
        if q:
            args.append("*")
            for p in q:
                pnames[p["name"]] = snake(p["name"])
                t = {"integer": "int", "boolean": "bool", "number": "float"}.get(p.get("schema", {}).get("type"), "str")
                args.append(f"{snake(p['name'])}: {t} | None = None")
        summary = str(op.get("summary") or oid)
        o.append(f"\n    def {snake(oid)}({', '.join(args)}) -> {resp_t}:\n")
        o.append(f"        {(m + ' ' + path + ' — ' + summary)!r}\n")  # docstring as a repr() literal (injection-safe)
        pp = ", ".join(f"{json.dumps(p['name'])}: {pnames[p['name']]}" for p in params if p["in"] == "path")
        qq = ", ".join(f"{json.dumps(p['name'])}: {pnames[p['name']]}" for p in q)
        call = f"self._call({json.dumps(oid)}, {{{pp}}}, {{{qq}}}" + (", body" if req_t is not None else "") + ")"
        o.append(f"        return {call}  # type: ignore[no-any-return]\n")
    (out / "operations.py").write_text("".join(o))

    # ---- secrets.py
    root_name = "RootConfig"
    wo, refs = secret_patterns(comps.get(root_name, {}), comps) if root_name in comps else ([], [])
    s = [head, '"""Pointer patterns into the configuration document (`*` matches one key or index)."""\n\n',
         "# write-only leaves (D-046): never returned by the API; the SDK never logs or reprs them\n",
         "WRITE_ONLY_POINTERS: tuple[str, ...] = (\n" + "".join(f"    {json.dumps(p)},\n" for p in wo) + ")\n\n",
         "# secret references `<kind>/<name>` (D-051): names, not values — treated as sensitive by the clients\n",
         "SECRET_REF_POINTERS: tuple[str, ...] = (\n" + "".join(f"    {json.dumps(p)},\n" for p in refs) + ")\n"]
    (out / "secrets.py").write_text("".join(s))
    (out / "__init__.py").write_text(head + '"""Generated from the OpenAPI document by sdk/python/tools/gen.py."""\n')
    verify(out, set(models.order))
    print(f"python sdk: {len(ops)} operations, {len(models.order)} models, {len(wo)} write-only + {len(refs)} secret-ref pointer patterns → {out}")


def verify(out: Path, model_names: set[str]) -> None:
    """Parse every generated module and require exactly the expected top-level names — a crafted document that
    slipped something past the escaping would show up here as an extra statement."""
    import ast

    def top(path: Path) -> tuple[set[str], list[str]]:
        tree = ast.parse(path.read_text())
        names: set[str] = set()
        other: list[str] = []
        for node in tree.body:
            if isinstance(node, (ast.Assign, ast.AnnAssign)):
                targets = node.targets if isinstance(node, ast.Assign) else [node.target]
                names |= {t.id for t in targets if isinstance(t, ast.Name)}
            elif isinstance(node, ast.ClassDef):
                names.add(node.name)
                for b in node.body[1:] if isinstance(node.body[0], ast.Expr) else node.body:
                    if not isinstance(b, ast.FunctionDef):
                        other.append(f"{node.name}: {type(b).__name__}")
                    elif any(not isinstance(x, (ast.Expr, ast.Return, ast.Raise)) for x in b.body):
                        other.append(f"{node.name}.{b.name}: unexpected statement")
            elif isinstance(node, (ast.ImportFrom, ast.Import, ast.If)) or (
                    isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant)):
                continue
            else:
                other.append(type(node).__name__)
        return names, other

    expect = {
        "models.py": model_names | {"__all__"},
        "operations.py": {"OPERATIONS", "Operations"},
        "secrets.py": {"WRITE_ONLY_POINTERS", "SECRET_REF_POINTERS"},
    }
    for fname, want in expect.items():
        names, other = top(out / fname)
        if names != want or other:
            raise GenError(f"{fname}: unexpected top-level content {sorted(names ^ want)} {other}")


if __name__ == "__main__":
    try:
        main()
    except GenError as e:
        sys.exit(f"gen.py: {e}")
