[Unit]
Requires=vrx-firewall-bootstrap.service
After=vrx-firewall-bootstrap.service

[Service]
ExecStart=
ExecStart=/usr/sbin/nft -f /etc/nftables.d/vrx-base.nft
ExecReload=
ExecReload=/usr/sbin/nft -f /etc/nftables.d/vrx-base.nft
ExecStop=
