// Value of the host-acl.nftables descriptor (scheduler.KV.Value), agent-internal (F-host-acl-nftables).
// The builder (Build) produces it from acl.host* + the expanded objects; Retrieve produces it from the
// kernel (`nft -j list table inet <table>`) plus the agent's store of the last applied value. proto.Equal
// on it is the scheduler's diff. Regenerate: see README.md ("Generated code").

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: nftables_model.proto

package nftables

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "ngfw/agent/gen/vrx/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HostTable is the whole host firewall table of one owner: the configuration it was rendered from and
// the rendered sets and chains.
type HostTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The applied configuration: only acl.host, acl.host_attachments and acl.host_settings are set.
	// Desired: from the document. Retrieve: from the agent's store (the value last applied).
	Config *v1.AclConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Named sets referenced by the rules, sorted by name. Retrieve: from the kernel.
	Sets []*Set `protobuf:"bytes,2,rep,name=sets,proto3" json:"sets,omitempty"`
	// Base chains in evaluation order (hook input, output, forward; then priority; then name).
	// Retrieve: from the kernel, in the same order.
	Chains        []*Chain `protobuf:"bytes,3,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostTable) Reset() {
	*x = HostTable{}
	mi := &file_nftables_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTable) ProtoMessage() {}

func (x *HostTable) ProtoReflect() protoreflect.Message {
	mi := &file_nftables_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostTable.ProtoReflect.Descriptor instead.
func (*HostTable) Descriptor() ([]byte, []int) {
	return file_nftables_model_proto_rawDescGZIP(), []int{0}
}

func (x *HostTable) GetConfig() *v1.AclConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *HostTable) GetSets() []*Set {
	if x != nil {
		return x.Sets
	}
	return nil
}

func (x *HostTable) GetChains() []*Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

// Set is one named interval set of addresses (an expanded address object or group).
type Set struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "a4_<object>" (ipv4_addr) or "a6_<object>" (ipv6_addr).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// "ipv4_addr" | "ipv6_addr".
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Elements as canonical (masked) prefixes, sorted in address order.
	Elements      []string `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Set) Reset() {
	*x = Set{}
	mi := &file_nftables_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_nftables_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_nftables_model_proto_rawDescGZIP(), []int{1}
}

func (x *Set) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Set) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Set) GetElements() []string {
	if x != nil {
		return x.Elements
	}
	return nil
}

// Chain is one base chain (one per enabled attachment).
type Chain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "in_<list>" | "out_<list>" | "fwd_<list>".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// "input" | "output" | "forward".
	Hook string `protobuf:"bytes,2,opt,name=hook,proto3" json:"hook,omitempty"`
	// -500..500.
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// "accept" | "drop".
	Policy string `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	// Rules in order.
	Rules         []*Rule `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_nftables_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_nftables_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_nftables_model_proto_rawDescGZIP(), []int{2}
}

func (x *Chain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chain) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *Chain) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Chain) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *Chain) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// Rule is one nftables rule. Its identity is the comment, which ends in a hash of `text`, so the kernel's
// own re-printing of the rule never matters: Retrieve reads the comment from the kernel and takes the
// annotations (text, kind, list, sequence, pointer, verdict) from the store entry with the same comment.
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "vrx:<id>/<n>:<hash8>"; <id> = "<list>:<sequence>" or "@established" | "@loopback" | "@icmp" |
	// "@anti-lockout"; <n> = index of the nft rule within that id; <hash8> = sha256(text)[:8].
	Comment string `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	// The rule as rendered, without counter and comment.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// "established" | "loopback" | "icmp" | "anti-lockout" | "rule" ("unknown" only on Retrieve).
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// kind=rule: the host list and the rule's sequence.
	List     string `protobuf:"bytes,4,opt,name=list,proto3" json:"list,omitempty"`
	Sequence uint32 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// kind=rule: JSON pointer of the rule in the document (/acl/host/<list>/rules/<i>).
	Pointer string `protobuf:"bytes,6,opt,name=pointer,proto3" json:"pointer,omitempty"`
	// "accept" | "drop" | "reject".
	Verdict       string `protobuf:"bytes,7,opt,name=verdict,proto3" json:"verdict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_nftables_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_nftables_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_nftables_model_proto_rawDescGZIP(), []int{3}
}

func (x *Rule) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Rule) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Rule) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Rule) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *Rule) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Rule) GetPointer() string {
	if x != nil {
		return x.Pointer
	}
	return ""
}

func (x *Rule) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

var File_nftables_model_proto protoreflect.FileDescriptor

const file_nftables_model_proto_rawDesc = "" +
	"\n" +
	"\x14nftables_model.proto\x12\x12vrx.agent.nftables\x1a\x16vrx/v1/dataplane.proto\"\x96\x01\n" +
	"\tHostTable\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.vrx.v1.AclConfigR\x06config\x12+\n" +
	"\x04sets\x18\x02 \x03(\v2\x17.vrx.agent.nftables.SetR\x04sets\x121\n" +
	"\x06chains\x18\x03 \x03(\v2\x19.vrx.agent.nftables.ChainR\x06chains\"I\n" +
	"\x03Set\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\belements\x18\x03 \x03(\tR\belements\"\x93\x01\n" +
	"\x05Chain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04hook\x18\x02 \x01(\tR\x04hook\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06policy\x18\x04 \x01(\tR\x06policy\x12.\n" +
	"\x05rules\x18\x05 \x03(\v2\x18.vrx.agent.nftables.RuleR\x05rules\"\xac\x01\n" +
	"\x04Rule\x12\x18\n" +
	"\acomment\x18\x01 \x01(\tR\acomment\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04list\x18\x04 \x01(\tR\x04list\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\rR\bsequence\x12\x18\n" +
	"\apointer\x18\x06 \x01(\tR\apointer\x12\x18\n" +
	"\averdict\x18\a \x01(\tR\averdictB1Z/ngfw/agent/internal/renderers/nftables;nftablesb\x06proto3"

var (
	file_nftables_model_proto_rawDescOnce sync.Once
	file_nftables_model_proto_rawDescData []byte
)

func file_nftables_model_proto_rawDescGZIP() []byte {
	file_nftables_model_proto_rawDescOnce.Do(func() {
		file_nftables_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nftables_model_proto_rawDesc), len(file_nftables_model_proto_rawDesc)))
	})
	return file_nftables_model_proto_rawDescData
}

var file_nftables_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nftables_model_proto_goTypes = []any{
	(*HostTable)(nil),    // 0: vrx.agent.nftables.HostTable
	(*Set)(nil),          // 1: vrx.agent.nftables.Set
	(*Chain)(nil),        // 2: vrx.agent.nftables.Chain
	(*Rule)(nil),         // 3: vrx.agent.nftables.Rule
	(*v1.AclConfig)(nil), // 4: vrx.v1.AclConfig
}
var file_nftables_model_proto_depIdxs = []int32{
	4, // 0: vrx.agent.nftables.HostTable.config:type_name -> vrx.v1.AclConfig
	1, // 1: vrx.agent.nftables.HostTable.sets:type_name -> vrx.agent.nftables.Set
	2, // 2: vrx.agent.nftables.HostTable.chains:type_name -> vrx.agent.nftables.Chain
	3, // 3: vrx.agent.nftables.Chain.rules:type_name -> vrx.agent.nftables.Rule
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nftables_model_proto_init() }
func file_nftables_model_proto_init() {
	if File_nftables_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nftables_model_proto_rawDesc), len(file_nftables_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nftables_model_proto_goTypes,
		DependencyIndexes: file_nftables_model_proto_depIdxs,
		MessageInfos:      file_nftables_model_proto_msgTypes,
	}.Build()
	File_nftables_model_proto = out.File
	file_nftables_model_proto_goTypes = nil
	file_nftables_model_proto_depIdxs = nil
}
