// Desired state of the ip6_nd descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ip6_nd/model.proto

package ip6nd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RaConfig is the router-advertisement configuration of one interface
// (sw_interface_ip6nd_ra_config). Numeric fields carry the effective values VPP reports;
// use NormalizeRaConfig to fill zeros with the VPP defaults before diffing.
type RaConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Interface string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// Do not send router advertisements (VPP: send_radv = 0).
	Suppress bool `protobuf:"varint,2,opt,name=suppress,proto3" json:"suppress,omitempty"`
	// Managed address configuration flag (M).
	Managed bool `protobuf:"varint,3,opt,name=managed,proto3" json:"managed,omitempty"`
	// Other configuration flag (O).
	Other bool `protobuf:"varint,4,opt,name=other,proto3" json:"other,omitempty"`
	// Suppress the source link-layer address option (API ll_option).
	SuppressLinkLayerOption bool `protobuf:"varint,5,opt,name=suppress_link_layer_option,json=suppressLinkLayerOption,proto3" json:"suppress_link_layer_option,omitempty"`
	// Answer solicitations with unicast RAs.
	SendUnicast bool `protobuf:"varint,6,opt,name=send_unicast,json=sendUnicast,proto3" json:"send_unicast,omitempty"`
	// Cease sending RAs (send final RA with lifetime 0).
	Cease bool `protobuf:"varint,7,opt,name=cease,proto3" json:"cease,omitempty"`
	// Router lifetime in seconds; 0 = not a default router. VPP default 600.
	RouterLifetime uint32 `protobuf:"varint,8,opt,name=router_lifetime,json=routerLifetime,proto3" json:"router_lifetime,omitempty"`
	// Max/min interval between unsolicited RAs in seconds (defaults 600 / 0.75*max).
	MaxInterval uint32 `protobuf:"varint,9,opt,name=max_interval,json=maxInterval,proto3" json:"max_interval,omitempty"`
	MinInterval uint32 `protobuf:"varint,10,opt,name=min_interval,json=minInterval,proto3" json:"min_interval,omitempty"`
	// Initial burst: count (default 3) and interval in seconds (default 16).
	InitialCount    uint32 `protobuf:"varint,11,opt,name=initial_count,json=initialCount,proto3" json:"initial_count,omitempty"`
	InitialInterval uint32 `protobuf:"varint,12,opt,name=initial_interval,json=initialInterval,proto3" json:"initial_interval,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RaConfig) Reset() {
	*x = RaConfig{}
	mi := &file_ip6_nd_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaConfig) ProtoMessage() {}

func (x *RaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ip6_nd_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaConfig.ProtoReflect.Descriptor instead.
func (*RaConfig) Descriptor() ([]byte, []int) {
	return file_ip6_nd_model_proto_rawDescGZIP(), []int{0}
}

func (x *RaConfig) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RaConfig) GetSuppress() bool {
	if x != nil {
		return x.Suppress
	}
	return false
}

func (x *RaConfig) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *RaConfig) GetOther() bool {
	if x != nil {
		return x.Other
	}
	return false
}

func (x *RaConfig) GetSuppressLinkLayerOption() bool {
	if x != nil {
		return x.SuppressLinkLayerOption
	}
	return false
}

func (x *RaConfig) GetSendUnicast() bool {
	if x != nil {
		return x.SendUnicast
	}
	return false
}

func (x *RaConfig) GetCease() bool {
	if x != nil {
		return x.Cease
	}
	return false
}

func (x *RaConfig) GetRouterLifetime() uint32 {
	if x != nil {
		return x.RouterLifetime
	}
	return 0
}

func (x *RaConfig) GetMaxInterval() uint32 {
	if x != nil {
		return x.MaxInterval
	}
	return 0
}

func (x *RaConfig) GetMinInterval() uint32 {
	if x != nil {
		return x.MinInterval
	}
	return 0
}

func (x *RaConfig) GetInitialCount() uint32 {
	if x != nil {
		return x.InitialCount
	}
	return 0
}

func (x *RaConfig) GetInitialInterval() uint32 {
	if x != nil {
		return x.InitialInterval
	}
	return 0
}

// RaPrefix is one prefix-information option advertised on an interface
// (sw_interface_ip6nd_ra_prefix).
type RaPrefix struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Interface string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// IPv6 prefix, canonical netip text.
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Lifetimes in seconds; 0 is normalised to the VPP defaults 2592000 / 604800.
	ValidLifetime     uint32 `protobuf:"varint,3,opt,name=valid_lifetime,json=validLifetime,proto3" json:"valid_lifetime,omitempty"`
	PreferredLifetime uint32 `protobuf:"varint,4,opt,name=preferred_lifetime,json=preferredLifetime,proto3" json:"preferred_lifetime,omitempty"`
	// Keep the prefix configured but do not advertise it.
	NoAdvertise bool `protobuf:"varint,5,opt,name=no_advertise,json=noAdvertise,proto3" json:"no_advertise,omitempty"`
	// Clear the on-link (L) flag.
	OffLink bool `protobuf:"varint,6,opt,name=off_link,json=offLink,proto3" json:"off_link,omitempty"`
	// Clear the autonomous address-configuration (A) flag.
	NoAutoconfig  bool `protobuf:"varint,7,opt,name=no_autoconfig,json=noAutoconfig,proto3" json:"no_autoconfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaPrefix) Reset() {
	*x = RaPrefix{}
	mi := &file_ip6_nd_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaPrefix) ProtoMessage() {}

func (x *RaPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_ip6_nd_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaPrefix.ProtoReflect.Descriptor instead.
func (*RaPrefix) Descriptor() ([]byte, []int) {
	return file_ip6_nd_model_proto_rawDescGZIP(), []int{1}
}

func (x *RaPrefix) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RaPrefix) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *RaPrefix) GetValidLifetime() uint32 {
	if x != nil {
		return x.ValidLifetime
	}
	return 0
}

func (x *RaPrefix) GetPreferredLifetime() uint32 {
	if x != nil {
		return x.PreferredLifetime
	}
	return 0
}

func (x *RaPrefix) GetNoAdvertise() bool {
	if x != nil {
		return x.NoAdvertise
	}
	return false
}

func (x *RaPrefix) GetOffLink() bool {
	if x != nil {
		return x.OffLink
	}
	return false
}

func (x *RaPrefix) GetNoAutoconfig() bool {
	if x != nil {
		return x.NoAutoconfig
	}
	return false
}

// ProxyNd proxies neighbour discovery for one address on an interface
// (ip6nd_proxy_enable_disable + ip6nd_proxy_add_del).
type ProxyNd struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Interface string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// Proxied IPv6 address.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyNd) Reset() {
	*x = ProxyNd{}
	mi := &file_ip6_nd_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyNd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyNd) ProtoMessage() {}

func (x *ProxyNd) ProtoReflect() protoreflect.Message {
	mi := &file_ip6_nd_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyNd.ProtoReflect.Descriptor instead.
func (*ProxyNd) Descriptor() ([]byte, []int) {
	return file_ip6_nd_model_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyNd) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *ProxyNd) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Dad is the global duplicate-address-detection configuration of the ip6_dad_autoremove
// plugin (ip6_dad_enable_disable). Presence means enabled.
type Dad struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of DAD probes (VPP default 1).
	Transmits uint32 `protobuf:"varint,1,opt,name=transmits,proto3" json:"transmits,omitempty"`
	// Delay between probes in seconds (VPP default 1).
	RetransmitDelay float64 `protobuf:"fixed64,2,opt,name=retransmit_delay,json=retransmitDelay,proto3" json:"retransmit_delay,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Dad) Reset() {
	*x = Dad{}
	mi := &file_ip6_nd_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dad) ProtoMessage() {}

func (x *Dad) ProtoReflect() protoreflect.Message {
	mi := &file_ip6_nd_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dad.ProtoReflect.Descriptor instead.
func (*Dad) Descriptor() ([]byte, []int) {
	return file_ip6_nd_model_proto_rawDescGZIP(), []int{3}
}

func (x *Dad) GetTransmits() uint32 {
	if x != nil {
		return x.Transmits
	}
	return 0
}

func (x *Dad) GetRetransmitDelay() float64 {
	if x != nil {
		return x.RetransmitDelay
	}
	return 0
}

var File_ip6_nd_model_proto protoreflect.FileDescriptor

const file_ip6_nd_model_proto_rawDesc = "" +
	"\n" +
	"\x12ip6_nd/model.proto\x12\x1cngfw.agent.descriptors.ip6nd\"\xa9\x03\n" +
	"\bRaConfig\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1a\n" +
	"\bsuppress\x18\x02 \x01(\bR\bsuppress\x12\x18\n" +
	"\amanaged\x18\x03 \x01(\bR\amanaged\x12\x14\n" +
	"\x05other\x18\x04 \x01(\bR\x05other\x12;\n" +
	"\x1asuppress_link_layer_option\x18\x05 \x01(\bR\x17suppressLinkLayerOption\x12!\n" +
	"\fsend_unicast\x18\x06 \x01(\bR\vsendUnicast\x12\x14\n" +
	"\x05cease\x18\a \x01(\bR\x05cease\x12'\n" +
	"\x0frouter_lifetime\x18\b \x01(\rR\x0erouterLifetime\x12!\n" +
	"\fmax_interval\x18\t \x01(\rR\vmaxInterval\x12!\n" +
	"\fmin_interval\x18\n" +
	" \x01(\rR\vminInterval\x12#\n" +
	"\rinitial_count\x18\v \x01(\rR\finitialCount\x12)\n" +
	"\x10initial_interval\x18\f \x01(\rR\x0finitialInterval\"\xf9\x01\n" +
	"\bRaPrefix\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12%\n" +
	"\x0evalid_lifetime\x18\x03 \x01(\rR\rvalidLifetime\x12-\n" +
	"\x12preferred_lifetime\x18\x04 \x01(\rR\x11preferredLifetime\x12!\n" +
	"\fno_advertise\x18\x05 \x01(\bR\vnoAdvertise\x12\x19\n" +
	"\boff_link\x18\x06 \x01(\bR\aoffLink\x12#\n" +
	"\rno_autoconfig\x18\a \x01(\bR\fnoAutoconfig\"A\n" +
	"\aProxyNd\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"N\n" +
	"\x03Dad\x12\x1c\n" +
	"\ttransmits\x18\x01 \x01(\rR\ttransmits\x12)\n" +
	"\x10retransmit_delay\x18\x02 \x01(\x01R\x0fretransmitDelayB.Z,ngfw/agent/internal/descriptors/ip6_nd;ip6ndb\x06proto3"

var (
	file_ip6_nd_model_proto_rawDescOnce sync.Once
	file_ip6_nd_model_proto_rawDescData []byte
)

func file_ip6_nd_model_proto_rawDescGZIP() []byte {
	file_ip6_nd_model_proto_rawDescOnce.Do(func() {
		file_ip6_nd_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ip6_nd_model_proto_rawDesc), len(file_ip6_nd_model_proto_rawDesc)))
	})
	return file_ip6_nd_model_proto_rawDescData
}

var file_ip6_nd_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ip6_nd_model_proto_goTypes = []any{
	(*RaConfig)(nil), // 0: ngfw.agent.descriptors.ip6nd.RaConfig
	(*RaPrefix)(nil), // 1: ngfw.agent.descriptors.ip6nd.RaPrefix
	(*ProxyNd)(nil),  // 2: ngfw.agent.descriptors.ip6nd.ProxyNd
	(*Dad)(nil),      // 3: ngfw.agent.descriptors.ip6nd.Dad
}
var file_ip6_nd_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ip6_nd_model_proto_init() }
func file_ip6_nd_model_proto_init() {
	if File_ip6_nd_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ip6_nd_model_proto_rawDesc), len(file_ip6_nd_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ip6_nd_model_proto_goTypes,
		DependencyIndexes: file_ip6_nd_model_proto_depIdxs,
		MessageInfos:      file_ip6_nd_model_proto_msgTypes,
	}.Build()
	File_ip6_nd_model_proto = out.File
	file_ip6_nd_model_proto_goTypes = nil
	file_ip6_nd_model_proto_depIdxs = nil
}
