// Desired-state model of the af_packet descriptor (task DF-1). Agent-internal, see interface/model.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: model.proto

package afpacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	Mode_MODE_ETHERNET Mode = 0
	Mode_MODE_IP       Mode = 1
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_ETHERNET",
		1: "MODE_IP",
	}
	Mode_value = map[string]int32{
		"MODE_ETHERNET": 0,
		"MODE_IP":       1,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

// HostInterface is af_packet_create_v3 on an existing Linux netdev. Flags and frame sizes are
// create-only in VPP 26.06 (af_packet_details returns host_if_name only) and are not modelled.
type HostInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HostIfName    string                 `protobuf:"bytes,2,opt,name=host_if_name,json=hostIfName,proto3" json:"host_if_name,omitempty"`
	Mode          Mode                   `protobuf:"varint,3,opt,name=mode,proto3,enum=vrx.agent.afpacket.Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInterface) Reset() {
	*x = HostInterface{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInterface) ProtoMessage() {}

func (x *HostInterface) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInterface.ProtoReflect.Descriptor instead.
func (*HostInterface) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *HostInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostInterface) GetHostIfName() string {
	if x != nil {
		return x.HostIfName
	}
	return ""
}

func (x *HostInterface) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_ETHERNET
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\x12vrx.agent.afpacket\"s\n" +
	"\rHostInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\fhost_if_name\x18\x02 \x01(\tR\n" +
	"hostIfName\x12,\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x18.vrx.agent.afpacket.ModeR\x04mode*&\n" +
	"\x04Mode\x12\x11\n" +
	"\rMODE_ETHERNET\x10\x00\x12\v\n" +
	"\aMODE_IP\x10\x01B4Z2ngfw/agent/internal/descriptors/af_packet;afpacketb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_proto_goTypes = []any{
	(Mode)(0),             // 0: vrx.agent.afpacket.Mode
	(*HostInterface)(nil), // 1: vrx.agent.afpacket.HostInterface
}
var file_model_proto_depIdxs = []int32{
	0, // 0: vrx.agent.afpacket.HostInterface.mode:type_name -> vrx.agent.afpacket.Mode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		EnumInfos:         file_model_proto_enumTypes,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
