// Desired state of the abf (ACL-based forwarding) descriptors (agent-internal until moved to
// packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: abf/model.proto

package abf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	df2 "ngfw/agent/internal/descriptors/df2"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Policy is one ABF policy: packets matching the ACL are forwarded over paths
// (abf_policy_add_del).
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy id chosen by the operator (tests: the slot's table range).
	PolicyId uint32 `protobuf:"varint,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Name of the ACL (dependency acl/<name>; resolved through its owner tag).
	Acl string `protobuf:"bytes,2,opt,name=acl,proto3" json:"acl,omitempty"`
	// Forwarding paths, canonicalised with df2.NormalizePaths.
	Paths         []*df2.FibPath `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_abf_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_abf_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_abf_model_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetPolicyId() uint32 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

func (x *Policy) GetAcl() string {
	if x != nil {
		return x.Acl
	}
	return ""
}

func (x *Policy) GetPaths() []*df2.FibPath {
	if x != nil {
		return x.Paths
	}
	return nil
}

// Attach binds a policy to an interface (abf_itf_attach_add_del).
type Attach struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PolicyId  uint32                 `protobuf:"varint,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Interface string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	// Evaluation order among policies on the interface (lower first).
	Priority uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Attach to the IPv6 (true) or IPv4 (false) feature arc.
	Ipv6          bool `protobuf:"varint,4,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attach) Reset() {
	*x = Attach{}
	mi := &file_abf_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attach) ProtoMessage() {}

func (x *Attach) ProtoReflect() protoreflect.Message {
	mi := &file_abf_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attach.ProtoReflect.Descriptor instead.
func (*Attach) Descriptor() ([]byte, []int) {
	return file_abf_model_proto_rawDescGZIP(), []int{1}
}

func (x *Attach) GetPolicyId() uint32 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

func (x *Attach) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Attach) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Attach) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

var File_abf_model_proto protoreflect.FileDescriptor

const file_abf_model_proto_rawDesc = "" +
	"\n" +
	"\x0fabf/model.proto\x12\x1angfw.agent.descriptors.abf\x1a\rdf2/df2.proto\"r\n" +
	"\x06Policy\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\rR\bpolicyId\x12\x10\n" +
	"\x03acl\x18\x02 \x01(\tR\x03acl\x129\n" +
	"\x05paths\x18\x03 \x03(\v2#.ngfw.agent.descriptors.df2.FibPathR\x05paths\"s\n" +
	"\x06Attach\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\rR\bpolicyId\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\x12\x12\n" +
	"\x04ipv6\x18\x04 \x01(\bR\x04ipv6B)Z'ngfw/agent/internal/descriptors/abf;abfb\x06proto3"

var (
	file_abf_model_proto_rawDescOnce sync.Once
	file_abf_model_proto_rawDescData []byte
)

func file_abf_model_proto_rawDescGZIP() []byte {
	file_abf_model_proto_rawDescOnce.Do(func() {
		file_abf_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abf_model_proto_rawDesc), len(file_abf_model_proto_rawDesc)))
	})
	return file_abf_model_proto_rawDescData
}

var file_abf_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_abf_model_proto_goTypes = []any{
	(*Policy)(nil),      // 0: ngfw.agent.descriptors.abf.Policy
	(*Attach)(nil),      // 1: ngfw.agent.descriptors.abf.Attach
	(*df2.FibPath)(nil), // 2: ngfw.agent.descriptors.df2.FibPath
}
var file_abf_model_proto_depIdxs = []int32{
	2, // 0: ngfw.agent.descriptors.abf.Policy.paths:type_name -> ngfw.agent.descriptors.df2.FibPath
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_abf_model_proto_init() }
func file_abf_model_proto_init() {
	if File_abf_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abf_model_proto_rawDesc), len(file_abf_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abf_model_proto_goTypes,
		DependencyIndexes: file_abf_model_proto_depIdxs,
		MessageInfos:      file_abf_model_proto_msgTypes,
	}.Build()
	File_abf_model_proto = out.File
	file_abf_model_proto_goTypes = nil
	file_abf_model_proto_depIdxs = nil
}
