// Values of the P05 core descriptors (scheduler.KV.Value). Agent-internal: the agent projects
// vrx.v1.DesiredState (packages/proto) onto these objects and back (internal/agent/projection.go).
// Canonical form (what Retrieve returns and what the projection produces) is documented per field;
// proto.Equal on these messages is the scheduler's diff.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: core_model.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Loopback is one loopback interface (create_loopback_instance with a fixed user instance).
// Key: "interface.loopback/<name>" (consumers depend on DF-1's alias "interface/<name>", D-065).
type Loopback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VPP interface name "loop<instance>", e.g. "loop701". The owner tag is "<owner>:<name>".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// User instance parsed from the name (701).
	Instance      uint32 `protobuf:"varint,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loopback) Reset() {
	*x = Loopback{}
	mi := &file_core_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loopback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loopback) ProtoMessage() {}

func (x *Loopback) ProtoReflect() protoreflect.Message {
	mi := &file_core_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loopback.ProtoReflect.Descriptor instead.
func (*Loopback) Descriptor() ([]byte, []int) {
	return file_core_model_proto_rawDescGZIP(), []int{0}
}

func (x *Loopback) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Loopback) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

// InterfaceAddress is one address on an owned interface (sw_interface_add_del_address).
// Key: "interface-ip/<interface>/<prefix>".
type InterfaceAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Interface name (its owner-tag id; for loopbacks the VPP name).
	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// Address with prefix length, canonical netip form ("10.7.1.1/24", "2001:db8::1/64").
	Prefix        string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceAddress) Reset() {
	*x = InterfaceAddress{}
	mi := &file_core_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceAddress) ProtoMessage() {}

func (x *InterfaceAddress) ProtoReflect() protoreflect.Message {
	mi := &file_core_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceAddress.ProtoReflect.Descriptor instead.
func (*InterfaceAddress) Descriptor() ([]byte, []int) {
	return file_core_model_proto_rawDescGZIP(), []int{1}
}

func (x *InterfaceAddress) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *InterfaceAddress) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// InterfaceTable binds an owned interface to a FIB table for IPv4 and IPv6 (sw_interface_set_table).
// Absence of the object = table 0. Key: "interface-ip.table/<interface>".
type InterfaceTable struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Interface string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// FIB table id (> 0).
	TableId       uint32 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceTable) Reset() {
	*x = InterfaceTable{}
	mi := &file_core_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceTable) ProtoMessage() {}

func (x *InterfaceTable) ProtoReflect() protoreflect.Message {
	mi := &file_core_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceTable.ProtoReflect.Descriptor instead.
func (*InterfaceTable) Descriptor() ([]byte, []int) {
	return file_core_model_proto_rawDescGZIP(), []int{2}
}

func (x *InterfaceTable) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *InterfaceTable) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

// Table is one VRF: an IPv4 and an IPv6 FIB table with the same id (ip_table_add_del), named
// "<owner>:<vrf>" in VPP. Key: "vrf/<id>".
type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// VRF name from the configuration document (the `vrfs` record key).
	Vrf string `protobuf:"bytes,2,opt,name=vrf,proto3" json:"vrf,omitempty"`
	// Set by Retrieve only: the IPv4 / IPv6 table of this VRF does not exist in VPP (partial loss);
	// never set in desired state, so the diff re-adds the missing family.
	MissingIp4    bool `protobuf:"varint,3,opt,name=missing_ip4,json=missingIp4,proto3" json:"missing_ip4,omitempty"`
	MissingIp6    bool `protobuf:"varint,4,opt,name=missing_ip6,json=missingIp6,proto3" json:"missing_ip6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_core_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_core_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_core_model_proto_rawDescGZIP(), []int{3}
}

func (x *Table) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Table) GetVrf() string {
	if x != nil {
		return x.Vrf
	}
	return ""
}

func (x *Table) GetMissingIp4() bool {
	if x != nil {
		return x.MissingIp4
	}
	return false
}

func (x *Table) GetMissingIp6() bool {
	if x != nil {
		return x.MissingIp6
	}
	return false
}

// Route is one static route (ip_route_add_del). Key: "ip.route/<table id>/<prefix>".
type Route struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TableId uint32                 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Destination prefix, canonical netip form with host bits cleared ("10.7.100.0/24").
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Paths sorted by (address, interface); empty = blackhole (drop).
	Paths []*RoutePath `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	// FIB path preference = administrative distance (0 when unset).
	Preference    uint32 `protobuf:"varint,4,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_core_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_core_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_core_model_proto_rawDescGZIP(), []int{4}
}

func (x *Route) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Route) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Route) GetPaths() []*RoutePath {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Route) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

type RoutePath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Next-hop address, canonical; empty for an interface route.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Egress interface name; empty = resolved through the FIB.
	Interface string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	// ECMP weight (>= 1).
	Weight        uint32 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePath) Reset() {
	*x = RoutePath{}
	mi := &file_core_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePath) ProtoMessage() {}

func (x *RoutePath) ProtoReflect() protoreflect.Message {
	mi := &file_core_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePath.ProtoReflect.Descriptor instead.
func (*RoutePath) Descriptor() ([]byte, []int) {
	return file_core_model_proto_rawDescGZIP(), []int{5}
}

func (x *RoutePath) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RoutePath) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RoutePath) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_core_model_proto protoreflect.FileDescriptor

const file_core_model_proto_rawDesc = "" +
	"\n" +
	"\x10core_model.proto\x12\x0evrx.agent.core\":\n" +
	"\bLoopback\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\rR\binstance\"H\n" +
	"\x10InterfaceAddress\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"I\n" +
	"\x0eInterfaceTable\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\rR\atableId\"k\n" +
	"\x05Table\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03vrf\x18\x02 \x01(\tR\x03vrf\x12\x1f\n" +
	"\vmissing_ip4\x18\x03 \x01(\bR\n" +
	"missingIp4\x12\x1f\n" +
	"\vmissing_ip6\x18\x04 \x01(\bR\n" +
	"missingIp6\"\x8b\x01\n" +
	"\x05Route\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\rR\atableId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12/\n" +
	"\x05paths\x18\x03 \x03(\v2\x19.vrx.agent.core.RoutePathR\x05paths\x12\x1e\n" +
	"\n" +
	"preference\x18\x04 \x01(\rR\n" +
	"preference\"[\n" +
	"\tRoutePath\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weightB+Z)ngfw/agent/internal/descriptors/core;coreb\x06proto3"

var (
	file_core_model_proto_rawDescOnce sync.Once
	file_core_model_proto_rawDescData []byte
)

func file_core_model_proto_rawDescGZIP() []byte {
	file_core_model_proto_rawDescOnce.Do(func() {
		file_core_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_model_proto_rawDesc), len(file_core_model_proto_rawDesc)))
	})
	return file_core_model_proto_rawDescData
}

var file_core_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_model_proto_goTypes = []any{
	(*Loopback)(nil),         // 0: vrx.agent.core.Loopback
	(*InterfaceAddress)(nil), // 1: vrx.agent.core.InterfaceAddress
	(*InterfaceTable)(nil),   // 2: vrx.agent.core.InterfaceTable
	(*Table)(nil),            // 3: vrx.agent.core.Table
	(*Route)(nil),            // 4: vrx.agent.core.Route
	(*RoutePath)(nil),        // 5: vrx.agent.core.RoutePath
}
var file_core_model_proto_depIdxs = []int32{
	5, // 0: vrx.agent.core.Route.paths:type_name -> vrx.agent.core.RoutePath
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_model_proto_init() }
func file_core_model_proto_init() {
	if File_core_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_model_proto_rawDesc), len(file_core_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_model_proto_goTypes,
		DependencyIndexes: file_core_model_proto_depIdxs,
		MessageInfos:      file_core_model_proto_msgTypes,
	}.Build()
	File_core_model_proto = out.File
	file_core_model_proto_goTypes = nil
	file_core_model_proto_depIdxs = nil
}
