#!/usr/bin/env bash
# sdk/python/lock.sh — (re)build the hash-pinned dev lock and the worktree venv for the Python SDK.
#   lock.sh venv   create sdk/python/.venv and install requirements-dev.lock with --require-hashes (the SDK is imported from the tree: pytest pythonpath)
#   lock.sh lock   resolve requirements-dev.in in a throwaway venv and rewrite requirements-dev.lock with sha256 hashes
# The SDK itself has NO runtime dependencies (stdlib only); the lock covers the test tooling (pytest and its deps).
# Only PyPI via pip (the standard package manager); never system-wide installs.
set -euo pipefail
cd "$(dirname "$0")"
PY=${PYTHON:-python3}

case "${1:-venv}" in
  venv)
    [[ -x .venv/bin/python ]] || "$PY" -m venv .venv
    .venv/bin/pip install -q --require-hashes --no-deps -r requirements-dev.lock
    echo "venv ready: sdk/python/.venv ($(.venv/bin/python --version); $(.venv/bin/pytest --version 2>&1))"
    ;;
  lock)
    tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
    "$PY" -m venv "$tmp/v"
    "$tmp/v/bin/pip" install -q -r requirements-dev.in
    "$tmp/v/bin/pip" freeze --exclude-editable | sort -f >"$tmp/pins"
    "$tmp/v/bin/pip" download -q --no-deps --only-binary=:all: -d "$tmp/dl" -r "$tmp/pins"
    {
      echo "# GENERATED by sdk/python/lock.sh lock from requirements-dev.in — install with: pip install --require-hashes -r requirements-dev.lock"
      while read -r pin; do
        name=${pin%%==*}; norm=$(tr 'A-Z-' 'a-z_' <<<"$name")
        f=$(find "$tmp/dl" -iname "${norm}-*" | head -n1)
        [[ -n $f ]] || { echo "no artifact for $pin" >&2; exit 1; }
        echo "$pin \\"
        echo "    --hash=sha256:$(sha256sum "$f" | cut -d' ' -f1)"
      done <"$tmp/pins"
    } >requirements-dev.lock
    echo "wrote requirements-dev.lock ($(grep -c '==' requirements-dev.lock) pins)"
    ;;
  *) sed -n '2,6p' "$0" | sed -E 's/^# ?//'; exit 2 ;;
esac
