// Desired-state model of the l3xc descriptor (task DF-1). Agent-internal, see interface/model.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: l3xc_model.proto

package l3xc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Path is one fib path of the cross-connect. Paths are kept sorted by (next_hop, interface, table).
type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextHop       string                 `protobuf:"bytes,1,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"` // IPv4 or IPv6 address, canonical form; empty for interface-only paths
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`            // full scheduler key of the egress interface; empty for table lookups
	Table         uint32                 `protobuf:"varint,3,opt,name=table,proto3" json:"table,omitempty"`                   // FIB table id (vrf); 0 = default
	Weight        uint32                 `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Preference    uint32                 `protobuf:"varint,5,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_l3xc_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_l3xc_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_l3xc_model_proto_rawDescGZIP(), []int{0}
}

func (x *Path) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *Path) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Path) GetTable() uint32 {
	if x != nil {
		return x.Table
	}
	return 0
}

func (x *Path) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Path) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

// L3xc redirects every packet received on interface into paths (l3xc_update / l3xc_del).
type L3Xc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"` // full scheduler key of the rx interface
	Ipv6          bool                   `protobuf:"varint,2,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Paths         []*Path                `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L3Xc) Reset() {
	*x = L3Xc{}
	mi := &file_l3xc_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L3Xc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L3Xc) ProtoMessage() {}

func (x *L3Xc) ProtoReflect() protoreflect.Message {
	mi := &file_l3xc_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L3Xc.ProtoReflect.Descriptor instead.
func (*L3Xc) Descriptor() ([]byte, []int) {
	return file_l3xc_model_proto_rawDescGZIP(), []int{1}
}

func (x *L3Xc) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *L3Xc) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

func (x *L3Xc) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_l3xc_model_proto protoreflect.FileDescriptor

const file_l3xc_model_proto_rawDesc = "" +
	"\n" +
	"\x10l3xc_model.proto\x12\x0evrx.agent.l3xc\"\x8d\x01\n" +
	"\x04Path\x12\x19\n" +
	"\bnext_hop\x18\x01 \x01(\tR\anextHop\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x14\n" +
	"\x05table\x18\x03 \x01(\rR\x05table\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\rR\x06weight\x12\x1e\n" +
	"\n" +
	"preference\x18\x05 \x01(\rR\n" +
	"preference\"d\n" +
	"\x04L3xc\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x12\n" +
	"\x04ipv6\x18\x02 \x01(\bR\x04ipv6\x12*\n" +
	"\x05paths\x18\x03 \x03(\v2\x14.vrx.agent.l3xc.PathR\x05pathsB+Z)ngfw/agent/internal/descriptors/l3xc;l3xcb\x06proto3"

var (
	file_l3xc_model_proto_rawDescOnce sync.Once
	file_l3xc_model_proto_rawDescData []byte
)

func file_l3xc_model_proto_rawDescGZIP() []byte {
	file_l3xc_model_proto_rawDescOnce.Do(func() {
		file_l3xc_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l3xc_model_proto_rawDesc), len(file_l3xc_model_proto_rawDesc)))
	})
	return file_l3xc_model_proto_rawDescData
}

var file_l3xc_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_l3xc_model_proto_goTypes = []any{
	(*Path)(nil), // 0: vrx.agent.l3xc.Path
	(*L3Xc)(nil), // 1: vrx.agent.l3xc.L3xc
}
var file_l3xc_model_proto_depIdxs = []int32{
	0, // 0: vrx.agent.l3xc.L3xc.paths:type_name -> vrx.agent.l3xc.Path
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_l3xc_model_proto_init() }
func file_l3xc_model_proto_init() {
	if File_l3xc_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l3xc_model_proto_rawDesc), len(file_l3xc_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l3xc_model_proto_goTypes,
		DependencyIndexes: file_l3xc_model_proto_depIdxs,
		MessageInfos:      file_l3xc_model_proto_msgTypes,
	}.Build()
	File_l3xc_model_proto = out.File
	file_l3xc_model_proto_goTypes = nil
	file_l3xc_model_proto_depIdxs = nil
}
