package cli

import (
	"fmt"
	"strings"

	"ngfw/cli/internal/api"
)

// Markdown renders the command reference (docs/user/cli/reference.md) from the command registry, the generated
// operation table and the exit codes — `make -C apps/cli docs` writes it; a unit test keeps it current.
func Markdown() string {
	var b strings.Builder
	b.WriteString(`# vrx CLI — command reference

<!-- GENERATED by apps/cli (go run ./cmd/vrx-docgen) from the command registry and the OpenAPI operation table. Do not edit. -->

` + "`vrx`" + ` is the on-box command line of VRX: operational ` + "`show`" + ` commands and a configuration mode with
candidate → commit/confirm → rollback semantics. It is a thin client of **vrx-api** (` + "`/api/v1`" + `): every command
below lists the REST operations it calls (from the OpenAPI document), and the CLI never talks to vrx-agent or VPP.

## Starting

| invocation | what it does |
|---|---|
| ` + "`vrx`" + ` | interactive shell (terminal): history, Tab completion, ` + "`?`" + ` help |
| ` + "`vrx <command …>`" + ` | one command, then exit (configuration commands work directly: ` + "`vrx set …`" + `, ` + "`vrx commit`" + `) |
| ` + "`vrx configure <command …>`" + ` | one configuration-mode command (e.g. ` + "`vrx configure show interfaces`" + ` shows the candidate) |
| ` + "`vrx --json <command …>`" + ` | machine mode: stdout carries exactly one JSON document (the API's answer); on failure stderr carries one ` + "`{\"error\":{exitCode,status,message,problem}}`" + ` document |
| ` + "`vrx < script`" + ` | commands from stdin, one per line (no prompts); stops at the first failure with its exit code |

### Flags and environment

| flag | env | meaning |
|---|---|---|
| ` + "`--api <url>`" + ` | ` + "`VRX_API_URL`" + ` | API base URL, default ` + "`" + DefaultAPI + "`" + ` |
| ` + "`--api-key-file <path>`" + ` | ` + "`VRX_API_KEY_FILE`" + ` | API key from a file that only its owner can read (0600); ` + "`VRX_API_KEY`" + ` carries the key itself |
| ` + "`--user <name>`" + ` | | log in for this invocation; the password is prompted without echo (or ` + "`--password-file <path>`" + `, 0600) |
| ` + "`--no-session`" + ` | | neither read nor write the session file |
| ` + "`--json`" + ` | | machine mode (see above) |
| ` + "`--debug`" + ` | | method, path, status and duration of every API call on stderr — never headers, bodies or credentials |
| | ` + "`VRX_SESSION_FILE`" + ` | session file, default ` + "`$XDG_RUNTIME_DIR/vrx/session.json`" + ` |
| | ` + "`VRX_HISTORY_FILE`" + ` | REPL history, default ` + "`~/.local/state/vrx/history`" + ` (0600; lines mentioning password/secret/psk/keys are not saved) |

### Credentials

Order: ` + "`--api-key-file`" + ` → ` + "`VRX_API_KEY`" + ` → ` + "`--user`" + ` → session file → (interactive shell) login prompt.
` + "`vrx login`" + ` stores only the 15-minute access token in the 0600 session file; the interactive shell keeps the refresh
token in memory and renews the access token on a 401. Passwords and keys are never echoed, logged or written to
history. ` + "`api-key create … file <path>`" + ` writes a new key to a new 0600 file instead of printing it.

## Paths and values

A configuration path is a list of words; each word is exactly one JSON-pointer segment of the configuration schema
(the mapping is 1:1): ` + "`interfaces TenGigabitEthernet0/0/0 mtu`" + ` ⇔ ` + "`/interfaces/TenGigabitEthernet0~10~10/mtu`" + `.
A single word starting with ` + "`/`" + ` is a JSON pointer itself (absolute, also below an ` + "`edit`" + ` level); ` + "`..`" + ` climbs one level.
Array items are addressed by index (` + "`routing static 0 prefix`" + `).

Values are checked against the live JSON Schema (` + "`GET /api/docs-json`" + `) **before** any request: type, range, enum,
length and pattern. Words are converted by the schema type (` + "`9000`" + ` → integer, ` + "`true`" + ` → boolean); quote a word to keep it
a string; ` + "`{…}`" + ` / ` + "`[…]`" + ` are JSON. On a list of scalars (addresses, names) ` + "`set`" + ` appends one item and
` + "`delete <path> <value>`" + ` removes it. ` + "`merge <path> <json>`" + ` is an RFC 7386 merge patch (` + "`null`" + ` deletes a member).

Output formats of configuration: ` + "`text`" + ` (default: a stable brace hierarchy, keys sorted, one leaf per line), ` + "`set`" + `
(one ` + "`set`" + ` command per leaf — the commands that rebuild it), ` + "`json`" + `. Diffs are printed as ` + "`- set …`" + ` / ` + "`+ set …`" + ` lines.

`)
	for _, mode := range []struct {
		title string
		where int
	}{{"Operational commands", inOp}, {"Configuration-mode commands", inConfig}} {
		fmt.Fprintf(&b, "## %s\n\n| command | description | REST |\n|---|---|---|\n", mode.title)
		for _, c := range Commands() {
			if c.Where&mode.where == 0 || (mode.where == inConfig && c.Where == inBoth) {
				continue
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", mdEscape(strings.TrimSpace(c.Name()+" "+c.Args)), mdEscape(c.Summary), restCell(c))
		}
		if mode.where == inConfig {
			b.WriteString("\nIn configuration mode all commands marked *both* above are available too, `show` means the candidate at the edit level, and `run <command>` runs an operational command.\n")
		}
		b.WriteString("\n")
	}
	b.WriteString("Commands available in both modes are listed under *Operational commands*. Words may be abbreviated to a unique prefix (`sh int` = `show interfaces`).\n\n")
	b.WriteString("## Exit codes\n\n| code | meaning |\n|---|---|\n")
	for _, e := range ExitCodes {
		fmt.Fprintf(&b, "| %d | %s |\n", e.Code, mdEscape(e.Meaning))
	}
	b.WriteString(`
## Not in this release

- Login-shell / SSH wiring and a local unix-socket transport with peer-credential check (P13 out of scope; the API
  listens on TCP only today): the CLI authenticates with a login or an API key.
- ` + "`show bgp summary`" + ` and ` + "`show ipsec sa`" + ` exist but exit 10: the API has no BGP / IPsec SA state endpoints yet.
- ` + "`ping`" + ` / ` + "`traceroute`" + ` call ` + "`POST /api/v1/actions/{action}`" + `, which answers 501 until the agent implements actions.
`)
	return b.String()
}

func restCell(c *Command) string {
	var parts []string
	for _, id := range c.Ops {
		if op, err := api.Lookup(id); err == nil {
			parts = append(parts, fmt.Sprintf("`%s %s`", op.Method, op.Path))
		} else {
			parts = append(parts, "**unknown operation "+id+"**")
		}
	}
	if c.NoREST != "" {
		parts = append(parts, mdEscape(c.NoREST))
	}
	where := "operational"
	switch c.Where {
	case inBoth:
		where = "both"
	case inConfig:
		where = "configuration"
	}
	return strings.Join(parts, "<br>") + " · *" + where + "*"
}

func mdEscape(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
