# GENERATED by sdk/python/tools/gen.py from the VRX OpenAPI document (VRX API 0.1.0) — never edit.
"""Pointer patterns into the configuration document (`*` matches one key or index)."""

# write-only leaves (D-046): never returned by the API; the SDK never logs or reprs them
WRITE_ONLY_POINTERS: tuple[str, ...] = (
    "/management/users/*/passwordHash",
)

# secret references `<kind>/<name>` (D-051): names, not values — treated as sensitive by the clients
SECRET_REF_POINTERS: tuple[str, ...] = (
    "/ha/cluster/secretRef",
    "/management/aaa/radius/servers/*/secretRef",
    "/management/aaa/tacacs/servers/*/secretRef",
    "/management/tls/certificateRef",
    "/management/tls/privateKeyRef",
    "/routing/bgp/neighbors/*/passwordRef",
    "/routing/bgp/peerGroups/*/passwordRef",
    "/services/ntp/ntsServer/certificateRef",
    "/services/ntp/ntsServer/keyRef",
    "/services/ntp/servers/*/keyRef",
    "/services/snmp/communities/*/secretRef",
    "/services/snmp/v3Users/*/authRef",
    "/services/snmp/v3Users/*/privRef",
    "/vpn/ipsec/tunnels/*/auth/secretRef",
    "/vpn/pki/cas/*/certificateRef",
    "/vpn/pki/certificates/*/certificateRef",
    "/vpn/pki/certificates/*/privateKeyRef",
    "/vpn/pki/hsm/pinRef",
    "/vpn/remoteAccess/*/radius/servers/*/secretRef",
    "/vpn/remoteAccess/*/users/*/passwordRef",
    "/vpn/wireguard/interfaces/*/peers/*/presharedKeyRef",
    "/vpn/wireguard/interfaces/*/privateKeyRef",
)
