// Desired-state model of the bond.* descriptors (task DF-1). Agent-internal, see interface/model.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: bond_model.proto

package bond

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode values equal binapi bond.BondMode.
type Mode int32

const (
	Mode_MODE_UNSPECIFIED   Mode = 0
	Mode_MODE_ROUND_ROBIN   Mode = 1
	Mode_MODE_ACTIVE_BACKUP Mode = 2
	Mode_MODE_XOR           Mode = 3
	Mode_MODE_BROADCAST     Mode = 4
	Mode_MODE_LACP          Mode = 5
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_ROUND_ROBIN",
		2: "MODE_ACTIVE_BACKUP",
		3: "MODE_XOR",
		4: "MODE_BROADCAST",
		5: "MODE_LACP",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED":   0,
		"MODE_ROUND_ROBIN":   1,
		"MODE_ACTIVE_BACKUP": 2,
		"MODE_XOR":           3,
		"MODE_BROADCAST":     4,
		"MODE_LACP":          5,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_bond_model_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_bond_model_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_bond_model_proto_rawDescGZIP(), []int{0}
}

// LoadBalance values equal binapi bond.BondLbAlgo. Only XOR and LACP choose freely between
// L2/L23/L34; round-robin, active-backup and broadcast must carry their own value.
type LoadBalance int32

const (
	LoadBalance_LOAD_BALANCE_L2            LoadBalance = 0
	LoadBalance_LOAD_BALANCE_L34           LoadBalance = 1
	LoadBalance_LOAD_BALANCE_L23           LoadBalance = 2
	LoadBalance_LOAD_BALANCE_ROUND_ROBIN   LoadBalance = 3
	LoadBalance_LOAD_BALANCE_BROADCAST     LoadBalance = 4
	LoadBalance_LOAD_BALANCE_ACTIVE_BACKUP LoadBalance = 5
)

// Enum value maps for LoadBalance.
var (
	LoadBalance_name = map[int32]string{
		0: "LOAD_BALANCE_L2",
		1: "LOAD_BALANCE_L34",
		2: "LOAD_BALANCE_L23",
		3: "LOAD_BALANCE_ROUND_ROBIN",
		4: "LOAD_BALANCE_BROADCAST",
		5: "LOAD_BALANCE_ACTIVE_BACKUP",
	}
	LoadBalance_value = map[string]int32{
		"LOAD_BALANCE_L2":            0,
		"LOAD_BALANCE_L34":           1,
		"LOAD_BALANCE_L23":           2,
		"LOAD_BALANCE_ROUND_ROBIN":   3,
		"LOAD_BALANCE_BROADCAST":     4,
		"LOAD_BALANCE_ACTIVE_BACKUP": 5,
	}
)

func (x LoadBalance) Enum() *LoadBalance {
	p := new(LoadBalance)
	*p = x
	return p
}

func (x LoadBalance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalance) Descriptor() protoreflect.EnumDescriptor {
	return file_bond_model_proto_enumTypes[1].Descriptor()
}

func (LoadBalance) Type() protoreflect.EnumType {
	return &file_bond_model_proto_enumTypes[1]
}

func (x LoadBalance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalance.Descriptor instead.
func (LoadBalance) EnumDescriptor() ([]byte, []int) {
	return file_bond_model_proto_rawDescGZIP(), []int{1}
}

// Bond is bond_create2. id is mandatory: VPP names the interface BondEthernet<id>.
type Bond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Mode          Mode                   `protobuf:"varint,3,opt,name=mode,proto3,enum=vrx.agent.bond.Mode" json:"mode,omitempty"`
	Lb            LoadBalance            `protobuf:"varint,4,opt,name=lb,proto3,enum=vrx.agent.bond.LoadBalance" json:"lb,omitempty"`
	NumaOnly      bool                   `protobuf:"varint,5,opt,name=numa_only,json=numaOnly,proto3" json:"numa_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bond) Reset() {
	*x = Bond{}
	mi := &file_bond_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bond) ProtoMessage() {}

func (x *Bond) ProtoReflect() protoreflect.Message {
	mi := &file_bond_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bond.ProtoReflect.Descriptor instead.
func (*Bond) Descriptor() ([]byte, []int) {
	return file_bond_model_proto_rawDescGZIP(), []int{0}
}

func (x *Bond) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bond) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bond) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *Bond) GetLb() LoadBalance {
	if x != nil {
		return x.Lb
	}
	return LoadBalance_LOAD_BALANCE_L2
}

func (x *Bond) GetNumaOnly() bool {
	if x != nil {
		return x.NumaOnly
	}
	return false
}

// Member attaches an interface to a bond (bond_add_member / bond_detach_member).
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bond          string                 `protobuf:"bytes,1,opt,name=bond,proto3" json:"bond,omitempty"`           // full scheduler key of the bond
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"` // full scheduler key of the member interface
	Passive       bool                   `protobuf:"varint,3,opt,name=passive,proto3" json:"passive,omitempty"`
	LongTimeout   bool                   `protobuf:"varint,4,opt,name=long_timeout,json=longTimeout,proto3" json:"long_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_bond_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_bond_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_bond_model_proto_rawDescGZIP(), []int{1}
}

func (x *Member) GetBond() string {
	if x != nil {
		return x.Bond
	}
	return ""
}

func (x *Member) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Member) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *Member) GetLongTimeout() bool {
	if x != nil {
		return x.LongTimeout
	}
	return false
}

var File_bond_model_proto protoreflect.FileDescriptor

const file_bond_model_proto_rawDesc = "" +
	"\n" +
	"\x10bond_model.proto\x12\x0evrx.agent.bond\"\x9e\x01\n" +
	"\x04Bond\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.vrx.agent.bond.ModeR\x04mode\x12+\n" +
	"\x02lb\x18\x04 \x01(\x0e2\x1b.vrx.agent.bond.LoadBalanceR\x02lb\x12\x1b\n" +
	"\tnuma_only\x18\x05 \x01(\bR\bnumaOnly\"w\n" +
	"\x06Member\x12\x12\n" +
	"\x04bond\x18\x01 \x01(\tR\x04bond\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x18\n" +
	"\apassive\x18\x03 \x01(\bR\apassive\x12!\n" +
	"\flong_timeout\x18\x04 \x01(\bR\vlongTimeout*{\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MODE_ROUND_ROBIN\x10\x01\x12\x16\n" +
	"\x12MODE_ACTIVE_BACKUP\x10\x02\x12\f\n" +
	"\bMODE_XOR\x10\x03\x12\x12\n" +
	"\x0eMODE_BROADCAST\x10\x04\x12\r\n" +
	"\tMODE_LACP\x10\x05*\xa8\x01\n" +
	"\vLoadBalance\x12\x13\n" +
	"\x0fLOAD_BALANCE_L2\x10\x00\x12\x14\n" +
	"\x10LOAD_BALANCE_L34\x10\x01\x12\x14\n" +
	"\x10LOAD_BALANCE_L23\x10\x02\x12\x1c\n" +
	"\x18LOAD_BALANCE_ROUND_ROBIN\x10\x03\x12\x1a\n" +
	"\x16LOAD_BALANCE_BROADCAST\x10\x04\x12\x1e\n" +
	"\x1aLOAD_BALANCE_ACTIVE_BACKUP\x10\x05B+Z)ngfw/agent/internal/descriptors/bond;bondb\x06proto3"

var (
	file_bond_model_proto_rawDescOnce sync.Once
	file_bond_model_proto_rawDescData []byte
)

func file_bond_model_proto_rawDescGZIP() []byte {
	file_bond_model_proto_rawDescOnce.Do(func() {
		file_bond_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bond_model_proto_rawDesc), len(file_bond_model_proto_rawDesc)))
	})
	return file_bond_model_proto_rawDescData
}

var file_bond_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bond_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bond_model_proto_goTypes = []any{
	(Mode)(0),        // 0: vrx.agent.bond.Mode
	(LoadBalance)(0), // 1: vrx.agent.bond.LoadBalance
	(*Bond)(nil),     // 2: vrx.agent.bond.Bond
	(*Member)(nil),   // 3: vrx.agent.bond.Member
}
var file_bond_model_proto_depIdxs = []int32{
	0, // 0: vrx.agent.bond.Bond.mode:type_name -> vrx.agent.bond.Mode
	1, // 1: vrx.agent.bond.Bond.lb:type_name -> vrx.agent.bond.LoadBalance
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bond_model_proto_init() }
func file_bond_model_proto_init() {
	if File_bond_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bond_model_proto_rawDesc), len(file_bond_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bond_model_proto_goTypes,
		DependencyIndexes: file_bond_model_proto_depIdxs,
		EnumInfos:         file_bond_model_proto_enumTypes,
		MessageInfos:      file_bond_model_proto_msgTypes,
	}.Build()
	File_bond_model_proto = out.File
	file_bond_model_proto_goTypes = nil
	file_bond_model_proto_depIdxs = nil
}
