// Desired-state model of the l2.* descriptors (task DF-1). Agent-internal, see interface/model.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: l2_model.proto

package l2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortType int32

const (
	PortType_PORT_TYPE_NORMAL PortType = 0
	PortType_PORT_TYPE_BVI    PortType = 1
	PortType_PORT_TYPE_UU_FWD PortType = 2
)

// Enum value maps for PortType.
var (
	PortType_name = map[int32]string{
		0: "PORT_TYPE_NORMAL",
		1: "PORT_TYPE_BVI",
		2: "PORT_TYPE_UU_FWD",
	}
	PortType_value = map[string]int32{
		"PORT_TYPE_NORMAL": 0,
		"PORT_TYPE_BVI":    1,
		"PORT_TYPE_UU_FWD": 2,
	}
)

func (x PortType) Enum() *PortType {
	p := new(PortType)
	*p = x
	return p
}

func (x PortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortType) Descriptor() protoreflect.EnumDescriptor {
	return file_l2_model_proto_enumTypes[0].Descriptor()
}

func (PortType) Type() protoreflect.EnumType {
	return &file_l2_model_proto_enumTypes[0]
}

func (x PortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortType.Descriptor instead.
func (PortType) EnumDescriptor() ([]byte, []int) {
	return file_l2_model_proto_rawDescGZIP(), []int{0}
}

// VtrOp values are VPP's l2_vtr_op_t (src/vnet/l2/l2_vtr.h); 0 is "disabled" and has no object.
type VtrOp int32

const (
	VtrOp_VTR_OP_DISABLED      VtrOp = 0
	VtrOp_VTR_OP_PUSH_1        VtrOp = 1
	VtrOp_VTR_OP_PUSH_2        VtrOp = 2
	VtrOp_VTR_OP_POP_1         VtrOp = 3
	VtrOp_VTR_OP_POP_2         VtrOp = 4
	VtrOp_VTR_OP_TRANSLATE_1_1 VtrOp = 5
	VtrOp_VTR_OP_TRANSLATE_1_2 VtrOp = 6
	VtrOp_VTR_OP_TRANSLATE_2_1 VtrOp = 7
	VtrOp_VTR_OP_TRANSLATE_2_2 VtrOp = 8
)

// Enum value maps for VtrOp.
var (
	VtrOp_name = map[int32]string{
		0: "VTR_OP_DISABLED",
		1: "VTR_OP_PUSH_1",
		2: "VTR_OP_PUSH_2",
		3: "VTR_OP_POP_1",
		4: "VTR_OP_POP_2",
		5: "VTR_OP_TRANSLATE_1_1",
		6: "VTR_OP_TRANSLATE_1_2",
		7: "VTR_OP_TRANSLATE_2_1",
		8: "VTR_OP_TRANSLATE_2_2",
	}
	VtrOp_value = map[string]int32{
		"VTR_OP_DISABLED":      0,
		"VTR_OP_PUSH_1":        1,
		"VTR_OP_PUSH_2":        2,
		"VTR_OP_POP_1":         3,
		"VTR_OP_POP_2":         4,
		"VTR_OP_TRANSLATE_1_1": 5,
		"VTR_OP_TRANSLATE_1_2": 6,
		"VTR_OP_TRANSLATE_2_1": 7,
		"VTR_OP_TRANSLATE_2_2": 8,
	}
)

func (x VtrOp) Enum() *VtrOp {
	p := new(VtrOp)
	*p = x
	return p
}

func (x VtrOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VtrOp) Descriptor() protoreflect.EnumDescriptor {
	return file_l2_model_proto_enumTypes[1].Descriptor()
}

func (VtrOp) Type() protoreflect.EnumType {
	return &file_l2_model_proto_enumTypes[1]
}

func (x VtrOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VtrOp.Descriptor instead.
func (VtrOp) EnumDescriptor() ([]byte, []int) {
	return file_l2_model_proto_rawDescGZIP(), []int{1}
}

// BridgeDomain is bridge_domain_add_del_v2. Ownership: bd_tag = "<owner>:<id>".
type BridgeDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Flood         bool                   `protobuf:"varint,2,opt,name=flood,proto3" json:"flood,omitempty"`
	UuFlood       bool                   `protobuf:"varint,3,opt,name=uu_flood,json=uuFlood,proto3" json:"uu_flood,omitempty"`
	Forward       bool                   `protobuf:"varint,4,opt,name=forward,proto3" json:"forward,omitempty"`
	Learn         bool                   `protobuf:"varint,5,opt,name=learn,proto3" json:"learn,omitempty"`
	ArpTerm       bool                   `protobuf:"varint,6,opt,name=arp_term,json=arpTerm,proto3" json:"arp_term,omitempty"`
	ArpUfwd       bool                   `protobuf:"varint,7,opt,name=arp_ufwd,json=arpUfwd,proto3" json:"arp_ufwd,omitempty"`
	MacAge        uint32                 `protobuf:"varint,8,opt,name=mac_age,json=macAge,proto3" json:"mac_age,omitempty"` // minutes, 0 = disabled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeDomain) Reset() {
	*x = BridgeDomain{}
	mi := &file_l2_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeDomain) ProtoMessage() {}

func (x *BridgeDomain) ProtoReflect() protoreflect.Message {
	mi := &file_l2_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeDomain.ProtoReflect.Descriptor instead.
func (*BridgeDomain) Descriptor() ([]byte, []int) {
	return file_l2_model_proto_rawDescGZIP(), []int{0}
}

func (x *BridgeDomain) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BridgeDomain) GetFlood() bool {
	if x != nil {
		return x.Flood
	}
	return false
}

func (x *BridgeDomain) GetUuFlood() bool {
	if x != nil {
		return x.UuFlood
	}
	return false
}

func (x *BridgeDomain) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

func (x *BridgeDomain) GetLearn() bool {
	if x != nil {
		return x.Learn
	}
	return false
}

func (x *BridgeDomain) GetArpTerm() bool {
	if x != nil {
		return x.ArpTerm
	}
	return false
}

func (x *BridgeDomain) GetArpUfwd() bool {
	if x != nil {
		return x.ArpUfwd
	}
	return false
}

func (x *BridgeDomain) GetMacAge() uint32 {
	if x != nil {
		return x.MacAge
	}
	return 0
}

// BridgeDomainMember binds an interface to a bridge domain (sw_interface_set_l2_bridge).
type BridgeDomainMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BridgeDomain  uint32                 `protobuf:"varint,1,opt,name=bridge_domain,json=bridgeDomain,proto3" json:"bridge_domain,omitempty"`
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"` // full scheduler key of the interface
	PortType      PortType               `protobuf:"varint,3,opt,name=port_type,json=portType,proto3,enum=vrx.agent.l2.PortType" json:"port_type,omitempty"`
	Shg           uint32                 `protobuf:"varint,4,opt,name=shg,proto3" json:"shg,omitempty"` // split-horizon group, 0 = none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeDomainMember) Reset() {
	*x = BridgeDomainMember{}
	mi := &file_l2_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeDomainMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeDomainMember) ProtoMessage() {}

func (x *BridgeDomainMember) ProtoReflect() protoreflect.Message {
	mi := &file_l2_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeDomainMember.ProtoReflect.Descriptor instead.
func (*BridgeDomainMember) Descriptor() ([]byte, []int) {
	return file_l2_model_proto_rawDescGZIP(), []int{1}
}

func (x *BridgeDomainMember) GetBridgeDomain() uint32 {
	if x != nil {
		return x.BridgeDomain
	}
	return 0
}

func (x *BridgeDomainMember) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *BridgeDomainMember) GetPortType() PortType {
	if x != nil {
		return x.PortType
	}
	return PortType_PORT_TYPE_NORMAL
}

func (x *BridgeDomainMember) GetShg() uint32 {
	if x != nil {
		return x.Shg
	}
	return 0
}

// Xconnect is one direction of an L2 cross-connect (sw_interface_set_l2_xconnect): rx → tx.
// A bidirectional cross-connect is two objects.
type Xconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rx            string                 `protobuf:"bytes,1,opt,name=rx,proto3" json:"rx,omitempty"` // full scheduler key
	Tx            string                 `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"` // full scheduler key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Xconnect) Reset() {
	*x = Xconnect{}
	mi := &file_l2_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xconnect) ProtoMessage() {}

func (x *Xconnect) ProtoReflect() protoreflect.Message {
	mi := &file_l2_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xconnect.ProtoReflect.Descriptor instead.
func (*Xconnect) Descriptor() ([]byte, []int) {
	return file_l2_model_proto_rawDescGZIP(), []int{2}
}

func (x *Xconnect) GetRx() string {
	if x != nil {
		return x.Rx
	}
	return ""
}

func (x *Xconnect) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

// FibEntry is a static / filter / BVI L2 FIB entry (l2fib_add_del). Learned entries are never
// part of the desired or retrieved state.
type FibEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BridgeDomain  uint32                 `protobuf:"varint,1,opt,name=bridge_domain,json=bridgeDomain,proto3" json:"bridge_domain,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`             // lower-case
	Interface     string                 `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"` // full scheduler key; empty for filter entries
	Static        bool                   `protobuf:"varint,4,opt,name=static,proto3" json:"static,omitempty"`
	Filter        bool                   `protobuf:"varint,5,opt,name=filter,proto3" json:"filter,omitempty"`
	Bvi           bool                   `protobuf:"varint,6,opt,name=bvi,proto3" json:"bvi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibEntry) Reset() {
	*x = FibEntry{}
	mi := &file_l2_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibEntry) ProtoMessage() {}

func (x *FibEntry) ProtoReflect() protoreflect.Message {
	mi := &file_l2_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibEntry.ProtoReflect.Descriptor instead.
func (*FibEntry) Descriptor() ([]byte, []int) {
	return file_l2_model_proto_rawDescGZIP(), []int{3}
}

func (x *FibEntry) GetBridgeDomain() uint32 {
	if x != nil {
		return x.BridgeDomain
	}
	return 0
}

func (x *FibEntry) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *FibEntry) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *FibEntry) GetStatic() bool {
	if x != nil {
		return x.Static
	}
	return false
}

func (x *FibEntry) GetFilter() bool {
	if x != nil {
		return x.Filter
	}
	return false
}

func (x *FibEntry) GetBvi() bool {
	if x != nil {
		return x.Bvi
	}
	return false
}

// Flags overrides the L2 input feature flags of a bridge member (l2_interface_feat_flags_set).
// The object exists only while the flags differ from the bridge domain's own flags.
type Flags struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Interface string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Learn     bool                   `protobuf:"varint,2,opt,name=learn,proto3" json:"learn,omitempty"`
	Forward   bool                   `protobuf:"varint,3,opt,name=forward,proto3" json:"forward,omitempty"`
	Flood     bool                   `protobuf:"varint,4,opt,name=flood,proto3" json:"flood,omitempty"`
	UuFlood   bool                   `protobuf:"varint,5,opt,name=uu_flood,json=uuFlood,proto3" json:"uu_flood,omitempty"`
	ArpTerm   bool                   `protobuf:"varint,6,opt,name=arp_term,json=arpTerm,proto3" json:"arp_term,omitempty"`
	ArpUfwd   bool                   `protobuf:"varint,7,opt,name=arp_ufwd,json=arpUfwd,proto3" json:"arp_ufwd,omitempty"`
	// Bridge domain the interface is a member of. Mandatory: the flags only exist while the interface
	// is a member, so the object depends on l2.bridge-domain-member/<bridge_domain>/<interface id> and
	// is re-created with it (review M5).
	BridgeDomain  uint32 `protobuf:"varint,8,opt,name=bridge_domain,json=bridgeDomain,proto3" json:"bridge_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flags) Reset() {
	*x = Flags{}
	mi := &file_l2_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flags) ProtoMessage() {}

func (x *Flags) ProtoReflect() protoreflect.Message {
	mi := &file_l2_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flags.ProtoReflect.Descriptor instead.
func (*Flags) Descriptor() ([]byte, []int) {
	return file_l2_model_proto_rawDescGZIP(), []int{4}
}

func (x *Flags) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Flags) GetLearn() bool {
	if x != nil {
		return x.Learn
	}
	return false
}

func (x *Flags) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

func (x *Flags) GetFlood() bool {
	if x != nil {
		return x.Flood
	}
	return false
}

func (x *Flags) GetUuFlood() bool {
	if x != nil {
		return x.UuFlood
	}
	return false
}

func (x *Flags) GetArpTerm() bool {
	if x != nil {
		return x.ArpTerm
	}
	return false
}

func (x *Flags) GetArpUfwd() bool {
	if x != nil {
		return x.ArpUfwd
	}
	return false
}

func (x *Flags) GetBridgeDomain() uint32 {
	if x != nil {
		return x.BridgeDomain
	}
	return 0
}

// VlanTagRewrite is l2_interface_vlan_tag_rewrite on a (sub-)interface.
type VlanTagRewrite struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Interface string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Op        VtrOp                  `protobuf:"varint,2,opt,name=op,proto3,enum=vrx.agent.l2.VtrOp" json:"op,omitempty"`
	PushDot1Q bool                   `protobuf:"varint,3,opt,name=push_dot1q,json=pushDot1q,proto3" json:"push_dot1q,omitempty"` // pushed tags are 802.1q (true) or 802.1ad (false)
	Tag1      uint32                 `protobuf:"varint,4,opt,name=tag1,proto3" json:"tag1,omitempty"`
	Tag2      uint32                 `protobuf:"varint,5,opt,name=tag2,proto3" json:"tag2,omitempty"`
	// L2 mode of the interface (review M5): leaving/re-joining a bridge or an xconnect resets the
	// rewrite in VPP, so the object depends on that membership and is re-created with it. Both must
	// match the interface's actual mode (0/false = not in a bridge / not an xconnect rx).
	BridgeDomain  uint32 `protobuf:"varint,6,opt,name=bridge_domain,json=bridgeDomain,proto3" json:"bridge_domain,omitempty"`
	Xconnect      bool   `protobuf:"varint,7,opt,name=xconnect,proto3" json:"xconnect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlanTagRewrite) Reset() {
	*x = VlanTagRewrite{}
	mi := &file_l2_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanTagRewrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanTagRewrite) ProtoMessage() {}

func (x *VlanTagRewrite) ProtoReflect() protoreflect.Message {
	mi := &file_l2_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanTagRewrite.ProtoReflect.Descriptor instead.
func (*VlanTagRewrite) Descriptor() ([]byte, []int) {
	return file_l2_model_proto_rawDescGZIP(), []int{5}
}

func (x *VlanTagRewrite) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *VlanTagRewrite) GetOp() VtrOp {
	if x != nil {
		return x.Op
	}
	return VtrOp_VTR_OP_DISABLED
}

func (x *VlanTagRewrite) GetPushDot1Q() bool {
	if x != nil {
		return x.PushDot1Q
	}
	return false
}

func (x *VlanTagRewrite) GetTag1() uint32 {
	if x != nil {
		return x.Tag1
	}
	return 0
}

func (x *VlanTagRewrite) GetTag2() uint32 {
	if x != nil {
		return x.Tag2
	}
	return 0
}

func (x *VlanTagRewrite) GetBridgeDomain() uint32 {
	if x != nil {
		return x.BridgeDomain
	}
	return 0
}

func (x *VlanTagRewrite) GetXconnect() bool {
	if x != nil {
		return x.Xconnect
	}
	return false
}

var File_l2_model_proto protoreflect.FileDescriptor

const file_l2_model_proto_rawDesc = "" +
	"\n" +
	"\x0el2_model.proto\x12\fvrx.agent.l2\"\xce\x01\n" +
	"\fBridgeDomain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05flood\x18\x02 \x01(\bR\x05flood\x12\x19\n" +
	"\buu_flood\x18\x03 \x01(\bR\auuFlood\x12\x18\n" +
	"\aforward\x18\x04 \x01(\bR\aforward\x12\x14\n" +
	"\x05learn\x18\x05 \x01(\bR\x05learn\x12\x19\n" +
	"\barp_term\x18\x06 \x01(\bR\aarpTerm\x12\x19\n" +
	"\barp_ufwd\x18\a \x01(\bR\aarpUfwd\x12\x17\n" +
	"\amac_age\x18\b \x01(\rR\x06macAge\"\x9e\x01\n" +
	"\x12BridgeDomainMember\x12#\n" +
	"\rbridge_domain\x18\x01 \x01(\rR\fbridgeDomain\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x123\n" +
	"\tport_type\x18\x03 \x01(\x0e2\x16.vrx.agent.l2.PortTypeR\bportType\x12\x10\n" +
	"\x03shg\x18\x04 \x01(\rR\x03shg\"*\n" +
	"\bXconnect\x12\x0e\n" +
	"\x02rx\x18\x01 \x01(\tR\x02rx\x12\x0e\n" +
	"\x02tx\x18\x02 \x01(\tR\x02tx\"\xa1\x01\n" +
	"\bFibEntry\x12#\n" +
	"\rbridge_domain\x18\x01 \x01(\rR\fbridgeDomain\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x1c\n" +
	"\tinterface\x18\x03 \x01(\tR\tinterface\x12\x16\n" +
	"\x06static\x18\x04 \x01(\bR\x06static\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\bR\x06filter\x12\x10\n" +
	"\x03bvi\x18\x06 \x01(\bR\x03bvi\"\xe1\x01\n" +
	"\x05Flags\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x14\n" +
	"\x05learn\x18\x02 \x01(\bR\x05learn\x12\x18\n" +
	"\aforward\x18\x03 \x01(\bR\aforward\x12\x14\n" +
	"\x05flood\x18\x04 \x01(\bR\x05flood\x12\x19\n" +
	"\buu_flood\x18\x05 \x01(\bR\auuFlood\x12\x19\n" +
	"\barp_term\x18\x06 \x01(\bR\aarpTerm\x12\x19\n" +
	"\barp_ufwd\x18\a \x01(\bR\aarpUfwd\x12#\n" +
	"\rbridge_domain\x18\b \x01(\rR\fbridgeDomain\"\xdb\x01\n" +
	"\x0eVlanTagRewrite\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12#\n" +
	"\x02op\x18\x02 \x01(\x0e2\x13.vrx.agent.l2.VtrOpR\x02op\x12\x1d\n" +
	"\n" +
	"push_dot1q\x18\x03 \x01(\bR\tpushDot1q\x12\x12\n" +
	"\x04tag1\x18\x04 \x01(\rR\x04tag1\x12\x12\n" +
	"\x04tag2\x18\x05 \x01(\rR\x04tag2\x12#\n" +
	"\rbridge_domain\x18\x06 \x01(\rR\fbridgeDomain\x12\x1a\n" +
	"\bxconnect\x18\a \x01(\bR\bxconnect*I\n" +
	"\bPortType\x12\x14\n" +
	"\x10PORT_TYPE_NORMAL\x10\x00\x12\x11\n" +
	"\rPORT_TYPE_BVI\x10\x01\x12\x14\n" +
	"\x10PORT_TYPE_UU_FWD\x10\x02*\xce\x01\n" +
	"\x05VtrOp\x12\x13\n" +
	"\x0fVTR_OP_DISABLED\x10\x00\x12\x11\n" +
	"\rVTR_OP_PUSH_1\x10\x01\x12\x11\n" +
	"\rVTR_OP_PUSH_2\x10\x02\x12\x10\n" +
	"\fVTR_OP_POP_1\x10\x03\x12\x10\n" +
	"\fVTR_OP_POP_2\x10\x04\x12\x18\n" +
	"\x14VTR_OP_TRANSLATE_1_1\x10\x05\x12\x18\n" +
	"\x14VTR_OP_TRANSLATE_1_2\x10\x06\x12\x18\n" +
	"\x14VTR_OP_TRANSLATE_2_1\x10\a\x12\x18\n" +
	"\x14VTR_OP_TRANSLATE_2_2\x10\bB'Z%ngfw/agent/internal/descriptors/l2;l2b\x06proto3"

var (
	file_l2_model_proto_rawDescOnce sync.Once
	file_l2_model_proto_rawDescData []byte
)

func file_l2_model_proto_rawDescGZIP() []byte {
	file_l2_model_proto_rawDescOnce.Do(func() {
		file_l2_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l2_model_proto_rawDesc), len(file_l2_model_proto_rawDesc)))
	})
	return file_l2_model_proto_rawDescData
}

var file_l2_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_l2_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_l2_model_proto_goTypes = []any{
	(PortType)(0),              // 0: vrx.agent.l2.PortType
	(VtrOp)(0),                 // 1: vrx.agent.l2.VtrOp
	(*BridgeDomain)(nil),       // 2: vrx.agent.l2.BridgeDomain
	(*BridgeDomainMember)(nil), // 3: vrx.agent.l2.BridgeDomainMember
	(*Xconnect)(nil),           // 4: vrx.agent.l2.Xconnect
	(*FibEntry)(nil),           // 5: vrx.agent.l2.FibEntry
	(*Flags)(nil),              // 6: vrx.agent.l2.Flags
	(*VlanTagRewrite)(nil),     // 7: vrx.agent.l2.VlanTagRewrite
}
var file_l2_model_proto_depIdxs = []int32{
	0, // 0: vrx.agent.l2.BridgeDomainMember.port_type:type_name -> vrx.agent.l2.PortType
	1, // 1: vrx.agent.l2.VlanTagRewrite.op:type_name -> vrx.agent.l2.VtrOp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_l2_model_proto_init() }
func file_l2_model_proto_init() {
	if File_l2_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l2_model_proto_rawDesc), len(file_l2_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l2_model_proto_goTypes,
		DependencyIndexes: file_l2_model_proto_depIdxs,
		EnumInfos:         file_l2_model_proto_enumTypes,
		MessageInfos:      file_l2_model_proto_msgTypes,
	}.Build()
	File_l2_model_proto = out.File
	file_l2_model_proto_goTypes = nil
	file_l2_model_proto_depIdxs = nil
}
