// Desired state of the gtpu descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: gtpu/model.proto

package gtpu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecapNext mirrors gtpu_decap_next_type: where decapsulated packets go.
type DecapNext int32

const (
	DecapNext_DROP DecapNext = 0
	DecapNext_L2   DecapNext = 1
	DecapNext_IP4  DecapNext = 2
	DecapNext_IP6  DecapNext = 3
)

// Enum value maps for DecapNext.
var (
	DecapNext_name = map[int32]string{
		0: "DROP",
		1: "L2",
		2: "IP4",
		3: "IP6",
	}
	DecapNext_value = map[string]int32{
		"DROP": 0,
		"L2":   1,
		"IP4":  2,
		"IP6":  3,
	}
)

func (x DecapNext) Enum() *DecapNext {
	p := new(DecapNext)
	*p = x
	return p
}

func (x DecapNext) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecapNext) Descriptor() protoreflect.EnumDescriptor {
	return file_gtpu_model_proto_enumTypes[0].Descriptor()
}

func (DecapNext) Type() protoreflect.EnumType {
	return &file_gtpu_model_proto_enumTypes[0]
}

func (x DecapNext) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecapNext.Descriptor instead.
func (DecapNext) EnumDescriptor() ([]byte, []int) {
	return file_gtpu_model_proto_rawDescGZIP(), []int{0}
}

// Tunnel is one GTP-U tunnel interface (gtpu_add_del_tunnel_v2 / gtpu_tunnel_v2_dump). VPP
// names the interface itself; name is the object id and the owner tag. Only tteid changes in
// place (gtpu_tunnel_update_tteid); everything else recreates.
type Tunnel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Src   string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// Unicast or multicast destination.
	Dst string `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	// Interface for the multicast group (mandatory iff dst is multicast).
	McastInterface string `protobuf:"bytes,4,opt,name=mcast_interface,json=mcastInterface,proto3" json:"mcast_interface,omitempty"`
	// Encap FIB table id (dependency vrf/<id> unless 0).
	EncapVrfId uint32    `protobuf:"varint,5,opt,name=encap_vrf_id,json=encapVrfId,proto3" json:"encap_vrf_id,omitempty"`
	DecapNext  DecapNext `protobuf:"varint,6,opt,name=decap_next,json=decapNext,proto3,enum=ngfw.agent.descriptors.gtpu.DecapNext" json:"decap_next,omitempty"`
	// Local (receive) TEID.
	Teid uint32 `protobuf:"varint,7,opt,name=teid,proto3" json:"teid,omitempty"`
	// Remote (transmit) TEID; 0 = same as teid semantics of VPP (unset).
	Tteid uint32 `protobuf:"varint,8,opt,name=tteid,proto3" json:"tteid,omitempty"`
	// Add the PDU session container extension header with this QFI (0–63).
	PduExtension  bool   `protobuf:"varint,9,opt,name=pdu_extension,json=pduExtension,proto3" json:"pdu_extension,omitempty"`
	Qfi           uint32 `protobuf:"varint,10,opt,name=qfi,proto3" json:"qfi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_gtpu_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_gtpu_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_gtpu_model_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Tunnel) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Tunnel) GetMcastInterface() string {
	if x != nil {
		return x.McastInterface
	}
	return ""
}

func (x *Tunnel) GetEncapVrfId() uint32 {
	if x != nil {
		return x.EncapVrfId
	}
	return 0
}

func (x *Tunnel) GetDecapNext() DecapNext {
	if x != nil {
		return x.DecapNext
	}
	return DecapNext_DROP
}

func (x *Tunnel) GetTeid() uint32 {
	if x != nil {
		return x.Teid
	}
	return 0
}

func (x *Tunnel) GetTteid() uint32 {
	if x != nil {
		return x.Tteid
	}
	return 0
}

func (x *Tunnel) GetPduExtension() bool {
	if x != nil {
		return x.PduExtension
	}
	return false
}

func (x *Tunnel) GetQfi() uint32 {
	if x != nil {
		return x.Qfi
	}
	return 0
}

// Forward is a GTP-U forwarding entry (gtpu_add_del_forward): packets that match no tunnel
// (bad header / unknown TEID / unknown type, a bitmask of gtpu_forwarding_type) are forwarded
// to dst. VPP represents it as a tunnel interface; name is the object id and owner tag.
type Forward struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dst   string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	// gtpu_forwarding_type bitmask: 1 = bad header, 2 = unknown TEID, 4 = unknown type.
	ForwardingType uint32    `protobuf:"varint,3,opt,name=forwarding_type,json=forwardingType,proto3" json:"forwarding_type,omitempty"`
	EncapVrfId     uint32    `protobuf:"varint,4,opt,name=encap_vrf_id,json=encapVrfId,proto3" json:"encap_vrf_id,omitempty"`
	DecapNext      DecapNext `protobuf:"varint,5,opt,name=decap_next,json=decapNext,proto3,enum=ngfw.agent.descriptors.gtpu.DecapNext" json:"decap_next,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Forward) Reset() {
	*x = Forward{}
	mi := &file_gtpu_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forward) ProtoMessage() {}

func (x *Forward) ProtoReflect() protoreflect.Message {
	mi := &file_gtpu_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forward.ProtoReflect.Descriptor instead.
func (*Forward) Descriptor() ([]byte, []int) {
	return file_gtpu_model_proto_rawDescGZIP(), []int{1}
}

func (x *Forward) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Forward) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Forward) GetForwardingType() uint32 {
	if x != nil {
		return x.ForwardingType
	}
	return 0
}

func (x *Forward) GetEncapVrfId() uint32 {
	if x != nil {
		return x.EncapVrfId
	}
	return 0
}

func (x *Forward) GetDecapNext() DecapNext {
	if x != nil {
		return x.DecapNext
	}
	return DecapNext_DROP
}

// Bypass enables the ip4/ip6-gtpu-bypass features on an interface
// (sw_interface_set_gtpu_bypass). Write-only: VPP has no dump for it.
type Bypass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Ipv4          bool                   `protobuf:"varint,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          bool                   `protobuf:"varint,3,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bypass) Reset() {
	*x = Bypass{}
	mi := &file_gtpu_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bypass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bypass) ProtoMessage() {}

func (x *Bypass) ProtoReflect() protoreflect.Message {
	mi := &file_gtpu_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bypass.ProtoReflect.Descriptor instead.
func (*Bypass) Descriptor() ([]byte, []int) {
	return file_gtpu_model_proto_rawDescGZIP(), []int{2}
}

func (x *Bypass) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Bypass) GetIpv4() bool {
	if x != nil {
		return x.Ipv4
	}
	return false
}

func (x *Bypass) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

var File_gtpu_model_proto protoreflect.FileDescriptor

const file_gtpu_model_proto_rawDesc = "" +
	"\n" +
	"\x10gtpu/model.proto\x12\x1bngfw.agent.descriptors.gtpu\"\xb3\x02\n" +
	"\x06Tunnel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\tR\x03dst\x12'\n" +
	"\x0fmcast_interface\x18\x04 \x01(\tR\x0emcastInterface\x12 \n" +
	"\fencap_vrf_id\x18\x05 \x01(\rR\n" +
	"encapVrfId\x12E\n" +
	"\n" +
	"decap_next\x18\x06 \x01(\x0e2&.ngfw.agent.descriptors.gtpu.DecapNextR\tdecapNext\x12\x12\n" +
	"\x04teid\x18\a \x01(\rR\x04teid\x12\x14\n" +
	"\x05tteid\x18\b \x01(\rR\x05tteid\x12#\n" +
	"\rpdu_extension\x18\t \x01(\bR\fpduExtension\x12\x10\n" +
	"\x03qfi\x18\n" +
	" \x01(\rR\x03qfi\"\xc1\x01\n" +
	"\aForward\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12'\n" +
	"\x0fforwarding_type\x18\x03 \x01(\rR\x0eforwardingType\x12 \n" +
	"\fencap_vrf_id\x18\x04 \x01(\rR\n" +
	"encapVrfId\x12E\n" +
	"\n" +
	"decap_next\x18\x05 \x01(\x0e2&.ngfw.agent.descriptors.gtpu.DecapNextR\tdecapNext\"N\n" +
	"\x06Bypass\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x12\n" +
	"\x04ipv4\x18\x02 \x01(\bR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x03 \x01(\bR\x04ipv6*/\n" +
	"\tDecapNext\x12\b\n" +
	"\x04DROP\x10\x00\x12\x06\n" +
	"\x02L2\x10\x01\x12\a\n" +
	"\x03IP4\x10\x02\x12\a\n" +
	"\x03IP6\x10\x03B+Z)ngfw/agent/internal/descriptors/gtpu;gtpub\x06proto3"

var (
	file_gtpu_model_proto_rawDescOnce sync.Once
	file_gtpu_model_proto_rawDescData []byte
)

func file_gtpu_model_proto_rawDescGZIP() []byte {
	file_gtpu_model_proto_rawDescOnce.Do(func() {
		file_gtpu_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gtpu_model_proto_rawDesc), len(file_gtpu_model_proto_rawDesc)))
	})
	return file_gtpu_model_proto_rawDescData
}

var file_gtpu_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gtpu_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gtpu_model_proto_goTypes = []any{
	(DecapNext)(0),  // 0: ngfw.agent.descriptors.gtpu.DecapNext
	(*Tunnel)(nil),  // 1: ngfw.agent.descriptors.gtpu.Tunnel
	(*Forward)(nil), // 2: ngfw.agent.descriptors.gtpu.Forward
	(*Bypass)(nil),  // 3: ngfw.agent.descriptors.gtpu.Bypass
}
var file_gtpu_model_proto_depIdxs = []int32{
	0, // 0: ngfw.agent.descriptors.gtpu.Tunnel.decap_next:type_name -> ngfw.agent.descriptors.gtpu.DecapNext
	0, // 1: ngfw.agent.descriptors.gtpu.Forward.decap_next:type_name -> ngfw.agent.descriptors.gtpu.DecapNext
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gtpu_model_proto_init() }
func file_gtpu_model_proto_init() {
	if File_gtpu_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gtpu_model_proto_rawDesc), len(file_gtpu_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gtpu_model_proto_goTypes,
		DependencyIndexes: file_gtpu_model_proto_depIdxs,
		EnumInfos:         file_gtpu_model_proto_enumTypes,
		MessageInfos:      file_gtpu_model_proto_msgTypes,
	}.Build()
	File_gtpu_model_proto = out.File
	file_gtpu_model_proto_goTypes = nil
	file_gtpu_model_proto_depIdxs = nil
}
