// Desired-state model of the tapv2 descriptor (task DF-1). Agent-internal, see interface/model.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: tapv2_model.proto

package tapv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tap is tap_create_v3. id is mandatory: VPP names the interface tap<id>. Not in the model: fields
// the dump does not return (queue counts, host gateways), the VPP-side MAC (interface.mac-address)
// and the host-side MAC (VPP always generates and reports one — 02:fe:xx:xx:xx:xx — so an unset
// value could never round-trip; it is readable as state).
type Tap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	HostIfName    string                 `protobuf:"bytes,3,opt,name=host_if_name,json=hostIfName,proto3" json:"host_if_name,omitempty"`
	HostNamespace string                 `protobuf:"bytes,4,opt,name=host_namespace,json=hostNamespace,proto3" json:"host_namespace,omitempty"`
	HostBridge    string                 `protobuf:"bytes,5,opt,name=host_bridge,json=hostBridge,proto3" json:"host_bridge,omitempty"`
	HostIp4Prefix string                 `protobuf:"bytes,7,opt,name=host_ip4_prefix,json=hostIp4Prefix,proto3" json:"host_ip4_prefix,omitempty"` // "a.b.c.d/len", empty = none
	HostIp6Prefix string                 `protobuf:"bytes,8,opt,name=host_ip6_prefix,json=hostIp6Prefix,proto3" json:"host_ip6_prefix,omitempty"`
	HostMtu       uint32                 `protobuf:"varint,9,opt,name=host_mtu,json=hostMtu,proto3" json:"host_mtu,omitempty"`             // 0 = not set
	RxRingSize    uint32                 `protobuf:"varint,10,opt,name=rx_ring_size,json=rxRingSize,proto3" json:"rx_ring_size,omitempty"` // VPP default 256 — always explicit
	TxRingSize    uint32                 `protobuf:"varint,11,opt,name=tx_ring_size,json=txRingSize,proto3" json:"tx_ring_size,omitempty"`
	Gso           bool                   `protobuf:"varint,12,opt,name=gso,proto3" json:"gso,omitempty"`
	CsumOffload   bool                   `protobuf:"varint,13,opt,name=csum_offload,json=csumOffload,proto3" json:"csum_offload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tap) Reset() {
	*x = Tap{}
	mi := &file_tapv2_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tap) ProtoMessage() {}

func (x *Tap) ProtoReflect() protoreflect.Message {
	mi := &file_tapv2_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tap.ProtoReflect.Descriptor instead.
func (*Tap) Descriptor() ([]byte, []int) {
	return file_tapv2_model_proto_rawDescGZIP(), []int{0}
}

func (x *Tap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tap) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tap) GetHostIfName() string {
	if x != nil {
		return x.HostIfName
	}
	return ""
}

func (x *Tap) GetHostNamespace() string {
	if x != nil {
		return x.HostNamespace
	}
	return ""
}

func (x *Tap) GetHostBridge() string {
	if x != nil {
		return x.HostBridge
	}
	return ""
}

func (x *Tap) GetHostIp4Prefix() string {
	if x != nil {
		return x.HostIp4Prefix
	}
	return ""
}

func (x *Tap) GetHostIp6Prefix() string {
	if x != nil {
		return x.HostIp6Prefix
	}
	return ""
}

func (x *Tap) GetHostMtu() uint32 {
	if x != nil {
		return x.HostMtu
	}
	return 0
}

func (x *Tap) GetRxRingSize() uint32 {
	if x != nil {
		return x.RxRingSize
	}
	return 0
}

func (x *Tap) GetTxRingSize() uint32 {
	if x != nil {
		return x.TxRingSize
	}
	return 0
}

func (x *Tap) GetGso() bool {
	if x != nil {
		return x.Gso
	}
	return false
}

func (x *Tap) GetCsumOffload() bool {
	if x != nil {
		return x.CsumOffload
	}
	return false
}

var File_tapv2_model_proto protoreflect.FileDescriptor

const file_tapv2_model_proto_rawDesc = "" +
	"\n" +
	"\x11tapv2_model.proto\x12\x0fvrx.agent.tapv2\"\xfd\x02\n" +
	"\x03Tap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12 \n" +
	"\fhost_if_name\x18\x03 \x01(\tR\n" +
	"hostIfName\x12%\n" +
	"\x0ehost_namespace\x18\x04 \x01(\tR\rhostNamespace\x12\x1f\n" +
	"\vhost_bridge\x18\x05 \x01(\tR\n" +
	"hostBridge\x12&\n" +
	"\x0fhost_ip4_prefix\x18\a \x01(\tR\rhostIp4Prefix\x12&\n" +
	"\x0fhost_ip6_prefix\x18\b \x01(\tR\rhostIp6Prefix\x12\x19\n" +
	"\bhost_mtu\x18\t \x01(\rR\ahostMtu\x12 \n" +
	"\frx_ring_size\x18\n" +
	" \x01(\rR\n" +
	"rxRingSize\x12 \n" +
	"\ftx_ring_size\x18\v \x01(\rR\n" +
	"txRingSize\x12\x10\n" +
	"\x03gso\x18\f \x01(\bR\x03gso\x12!\n" +
	"\fcsum_offload\x18\r \x01(\bR\vcsumOffloadJ\x04\b\x06\x10\aB-Z+ngfw/agent/internal/descriptors/tapv2;tapv2b\x06proto3"

var (
	file_tapv2_model_proto_rawDescOnce sync.Once
	file_tapv2_model_proto_rawDescData []byte
)

func file_tapv2_model_proto_rawDescGZIP() []byte {
	file_tapv2_model_proto_rawDescOnce.Do(func() {
		file_tapv2_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tapv2_model_proto_rawDesc), len(file_tapv2_model_proto_rawDesc)))
	})
	return file_tapv2_model_proto_rawDescData
}

var file_tapv2_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tapv2_model_proto_goTypes = []any{
	(*Tap)(nil), // 0: vrx.agent.tapv2.Tap
}
var file_tapv2_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tapv2_model_proto_init() }
func file_tapv2_model_proto_init() {
	if File_tapv2_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tapv2_model_proto_rawDesc), len(file_tapv2_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tapv2_model_proto_goTypes,
		DependencyIndexes: file_tapv2_model_proto_depIdxs,
		MessageInfos:      file_tapv2_model_proto_msgTypes,
	}.Build()
	File_tapv2_model_proto = out.File
	file_tapv2_model_proto_goTypes = nil
	file_tapv2_model_proto_depIdxs = nil
}
