// Desired state of the gre descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: gre/model.proto

package gre

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelType mirrors gre_tunnel_type.
type TunnelType int32

const (
	TunnelType_L3     TunnelType = 0
	TunnelType_TEB    TunnelType = 1
	TunnelType_ERSPAN TunnelType = 2
)

// Enum value maps for TunnelType.
var (
	TunnelType_name = map[int32]string{
		0: "L3",
		1: "TEB",
		2: "ERSPAN",
	}
	TunnelType_value = map[string]int32{
		"L3":     0,
		"TEB":    1,
		"ERSPAN": 2,
	}
)

func (x TunnelType) Enum() *TunnelType {
	p := new(TunnelType)
	*p = x
	return p
}

func (x TunnelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelType) Descriptor() protoreflect.EnumDescriptor {
	return file_gre_model_proto_enumTypes[0].Descriptor()
}

func (TunnelType) Type() protoreflect.EnumType {
	return &file_gre_model_proto_enumTypes[0]
}

func (x TunnelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelType.Descriptor instead.
func (TunnelType) EnumDescriptor() ([]byte, []int) {
	return file_gre_model_proto_rawDescGZIP(), []int{0}
}

// TunnelMode mirrors tunnel_mode: point-to-point or multipoint (dst unset).
type TunnelMode int32

const (
	TunnelMode_P2P TunnelMode = 0
	TunnelMode_MP  TunnelMode = 1
)

// Enum value maps for TunnelMode.
var (
	TunnelMode_name = map[int32]string{
		0: "P2P",
		1: "MP",
	}
	TunnelMode_value = map[string]int32{
		"P2P": 0,
		"MP":  1,
	}
)

func (x TunnelMode) Enum() *TunnelMode {
	p := new(TunnelMode)
	*p = x
	return p
}

func (x TunnelMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gre_model_proto_enumTypes[1].Descriptor()
}

func (TunnelMode) Type() protoreflect.EnumType {
	return &file_gre_model_proto_enumTypes[1]
}

func (x TunnelMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelMode.Descriptor instead.
func (TunnelMode) EnumDescriptor() ([]byte, []int) {
	return file_gre_model_proto_rawDescGZIP(), []int{1}
}

// Tunnel is one GRE tunnel interface (gre_tunnel_add_del_v2). VPP names it gre<instance>,
// which is the object id; instance is therefore mandatory and must be unique.
type Tunnel struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Instance uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Type     TunnelType             `protobuf:"varint,2,opt,name=type,proto3,enum=ngfw.agent.descriptors.gre.TunnelType" json:"type,omitempty"`
	Mode     TunnelMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=ngfw.agent.descriptors.gre.TunnelMode" json:"mode,omitempty"`
	// Outer source address (IPv4 or IPv6).
	Src string `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	// Outer destination address; empty for MP tunnels.
	Dst string `protobuf:"bytes,5,opt,name=dst,proto3" json:"dst,omitempty"`
	// Outer FIB table id (dependency vrf/<id> unless 0).
	OuterTableId uint32 `protobuf:"varint,6,opt,name=outer_table_id,json=outerTableId,proto3" json:"outer_table_id,omitempty"`
	// ERSPAN session id (0–1023), ERSPAN tunnels only.
	SessionId uint32 `protobuf:"varint,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// tunnel_encap_decap_flags bitmask.
	Flags uint32 `protobuf:"varint,8,opt,name=flags,proto3" json:"flags,omitempty"`
	// GRE key (0 = none).
	Key           uint32 `protobuf:"varint,9,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_gre_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_gre_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_gre_model_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

func (x *Tunnel) GetType() TunnelType {
	if x != nil {
		return x.Type
	}
	return TunnelType_L3
}

func (x *Tunnel) GetMode() TunnelMode {
	if x != nil {
		return x.Mode
	}
	return TunnelMode_P2P
}

func (x *Tunnel) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Tunnel) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Tunnel) GetOuterTableId() uint32 {
	if x != nil {
		return x.OuterTableId
	}
	return 0
}

func (x *Tunnel) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Tunnel) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Tunnel) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

var File_gre_model_proto protoreflect.FileDescriptor

const file_gre_model_proto_rawDesc = "" +
	"\n" +
	"\x0fgre/model.proto\x12\x1angfw.agent.descriptors.gre\"\xad\x02\n" +
	"\x06Tunnel\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.ngfw.agent.descriptors.gre.TunnelTypeR\x04type\x12:\n" +
	"\x04mode\x18\x03 \x01(\x0e2&.ngfw.agent.descriptors.gre.TunnelModeR\x04mode\x12\x10\n" +
	"\x03src\x18\x04 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x05 \x01(\tR\x03dst\x12$\n" +
	"\x0eouter_table_id\x18\x06 \x01(\rR\fouterTableId\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\rR\tsessionId\x12\x14\n" +
	"\x05flags\x18\b \x01(\rR\x05flags\x12\x10\n" +
	"\x03key\x18\t \x01(\rR\x03key*)\n" +
	"\n" +
	"TunnelType\x12\x06\n" +
	"\x02L3\x10\x00\x12\a\n" +
	"\x03TEB\x10\x01\x12\n" +
	"\n" +
	"\x06ERSPAN\x10\x02*\x1d\n" +
	"\n" +
	"TunnelMode\x12\a\n" +
	"\x03P2P\x10\x00\x12\x06\n" +
	"\x02MP\x10\x01B)Z'ngfw/agent/internal/descriptors/gre;greb\x06proto3"

var (
	file_gre_model_proto_rawDescOnce sync.Once
	file_gre_model_proto_rawDescData []byte
)

func file_gre_model_proto_rawDescGZIP() []byte {
	file_gre_model_proto_rawDescOnce.Do(func() {
		file_gre_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gre_model_proto_rawDesc), len(file_gre_model_proto_rawDesc)))
	})
	return file_gre_model_proto_rawDescData
}

var file_gre_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gre_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gre_model_proto_goTypes = []any{
	(TunnelType)(0), // 0: ngfw.agent.descriptors.gre.TunnelType
	(TunnelMode)(0), // 1: ngfw.agent.descriptors.gre.TunnelMode
	(*Tunnel)(nil),  // 2: ngfw.agent.descriptors.gre.Tunnel
}
var file_gre_model_proto_depIdxs = []int32{
	0, // 0: ngfw.agent.descriptors.gre.Tunnel.type:type_name -> ngfw.agent.descriptors.gre.TunnelType
	1, // 1: ngfw.agent.descriptors.gre.Tunnel.mode:type_name -> ngfw.agent.descriptors.gre.TunnelMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gre_model_proto_init() }
func file_gre_model_proto_init() {
	if File_gre_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gre_model_proto_rawDesc), len(file_gre_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gre_model_proto_goTypes,
		DependencyIndexes: file_gre_model_proto_depIdxs,
		EnumInfos:         file_gre_model_proto_enumTypes,
		MessageInfos:      file_gre_model_proto_msgTypes,
	}.Build()
	File_gre_model_proto = out.File
	file_gre_model_proto_goTypes = nil
	file_gre_model_proto_depIdxs = nil
}
