// Desired-state model of the memif.* descriptors (task DF-1). Agent-internal, see interface/model.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: model.proto

package memif

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_MASTER Role = 0
	Role_ROLE_SLAVE  Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_MASTER",
		1: "ROLE_SLAVE",
	}
	Role_value = map[string]int32{
		"ROLE_MASTER": 0,
		"ROLE_SLAVE":  1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

type Mode int32

const (
	Mode_MODE_ETHERNET    Mode = 0
	Mode_MODE_IP          Mode = 1
	Mode_MODE_PUNT_INJECT Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_ETHERNET",
		1: "MODE_IP",
		2: "MODE_PUNT_INJECT",
	}
	Mode_value = map[string]int32{
		"MODE_ETHERNET":    0,
		"MODE_IP":          1,
		"MODE_PUNT_INJECT": 2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[1].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[1]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

// Socket is memif_socket_filename_add_del_v2. Ownership: filename lives in the owner's socket dir.
type Socket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Socket) Reset() {
	*x = Socket{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Socket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socket) ProtoMessage() {}

func (x *Socket) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socket.ProtoReflect.Descriptor instead.
func (*Socket) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *Socket) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Socket) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Memif is memif_create_v2. rx/tx queue counts, the secret and the hw address are not part of the
// model because memif_details does not return them (secret) or they are managed elsewhere (mac).
type Memif struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Socket        uint32                 `protobuf:"varint,3,opt,name=socket,proto3" json:"socket,omitempty"` // socket id; 0 = VPP's default socket (never owned)
	Role          Role                   `protobuf:"varint,4,opt,name=role,proto3,enum=vrx.agent.memif.Role" json:"role,omitempty"`
	Mode          Mode                   `protobuf:"varint,5,opt,name=mode,proto3,enum=vrx.agent.memif.Mode" json:"mode,omitempty"`
	RingSize      uint32                 `protobuf:"varint,6,opt,name=ring_size,json=ringSize,proto3" json:"ring_size,omitempty"`       // power of two, VPP default 1024 — always explicit
	BufferSize    uint32                 `protobuf:"varint,7,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"` // VPP default 2048 — always explicit
	ZeroCopy      bool                   `protobuf:"varint,8,opt,name=zero_copy,json=zeroCopy,proto3" json:"zero_copy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memif) Reset() {
	*x = Memif{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memif) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memif) ProtoMessage() {}

func (x *Memif) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memif.ProtoReflect.Descriptor instead.
func (*Memif) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *Memif) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Memif) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Memif) GetSocket() uint32 {
	if x != nil {
		return x.Socket
	}
	return 0
}

func (x *Memif) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_MASTER
}

func (x *Memif) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_ETHERNET
}

func (x *Memif) GetRingSize() uint32 {
	if x != nil {
		return x.RingSize
	}
	return 0
}

func (x *Memif) GetBufferSize() uint32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *Memif) GetZeroCopy() bool {
	if x != nil {
		return x.ZeroCopy
	}
	return false
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\x0fvrx.agent.memif\"4\n" +
	"\x06Socket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"\xf4\x01\n" +
	"\x05Memif\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x16\n" +
	"\x06socket\x18\x03 \x01(\rR\x06socket\x12)\n" +
	"\x04role\x18\x04 \x01(\x0e2\x15.vrx.agent.memif.RoleR\x04role\x12)\n" +
	"\x04mode\x18\x05 \x01(\x0e2\x15.vrx.agent.memif.ModeR\x04mode\x12\x1b\n" +
	"\tring_size\x18\x06 \x01(\rR\bringSize\x12\x1f\n" +
	"\vbuffer_size\x18\a \x01(\rR\n" +
	"bufferSize\x12\x1b\n" +
	"\tzero_copy\x18\b \x01(\bR\bzeroCopy*'\n" +
	"\x04Role\x12\x0f\n" +
	"\vROLE_MASTER\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_SLAVE\x10\x01*<\n" +
	"\x04Mode\x12\x11\n" +
	"\rMODE_ETHERNET\x10\x00\x12\v\n" +
	"\aMODE_IP\x10\x01\x12\x14\n" +
	"\x10MODE_PUNT_INJECT\x10\x02B-Z+ngfw/agent/internal/descriptors/memif;memifb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_proto_goTypes = []any{
	(Role)(0),      // 0: vrx.agent.memif.Role
	(Mode)(0),      // 1: vrx.agent.memif.Mode
	(*Socket)(nil), // 2: vrx.agent.memif.Socket
	(*Memif)(nil),  // 3: vrx.agent.memif.Memif
}
var file_model_proto_depIdxs = []int32{
	0, // 0: vrx.agent.memif.Memif.role:type_name -> vrx.agent.memif.Role
	1, // 1: vrx.agent.memif.Memif.mode:type_name -> vrx.agent.memif.Mode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		EnumInfos:         file_model_proto_enumTypes,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
