// Desired state of the SR-MPLS descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sr_mpls/model.proto

package sr_mpls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SegmentList is one label stack of a policy: labels[0] is the first segment (resolved in
// the MPLS table), the rest are pushed. weight 1–255.
type SegmentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []uint32               `protobuf:"varint,1,rep,packed,name=labels,proto3" json:"labels,omitempty"`
	Weight        uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentList) Reset() {
	*x = SegmentList{}
	mi := &file_sr_mpls_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentList) ProtoMessage() {}

func (x *SegmentList) ProtoReflect() protoreflect.Message {
	mi := &file_sr_mpls_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentList.ProtoReflect.Descriptor instead.
func (*SegmentList) Descriptor() ([]byte, []int) {
	return file_sr_mpls_model_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentList) GetLabels() []uint32 {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SegmentList) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// Policy is one SR-MPLS policy (sr_mpls_policy_add + sr_mpls_policy_mod for further lists /
// sr_mpls_policy_del). VPP has no SR-MPLS dump: Retrieve derives the policy from the BSID's
// local-label entry in MPLS table 0 (mpls_route_dump) — "partial". Id = bsid. Every change
// recreates. segment_lists must be in ascending order (VPP's path list does not keep the
// configured order, so Retrieve reports them sorted).
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Binding SID label (16–1048575).
	Bsid uint32 `protobuf:"varint,1,opt,name=bsid,proto3" json:"bsid,omitempty"`
	// Replicate on all lists (spray) instead of load-balancing.
	Spray         bool           `protobuf:"varint,2,opt,name=spray,proto3" json:"spray,omitempty"`
	SegmentLists  []*SegmentList `protobuf:"bytes,3,rep,name=segment_lists,json=segmentLists,proto3" json:"segment_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_sr_mpls_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_sr_mpls_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_sr_mpls_model_proto_rawDescGZIP(), []int{1}
}

func (x *Policy) GetBsid() uint32 {
	if x != nil {
		return x.Bsid
	}
	return 0
}

func (x *Policy) GetSpray() bool {
	if x != nil {
		return x.Spray
	}
	return false
}

func (x *Policy) GetSegmentLists() []*SegmentList {
	if x != nil {
		return x.SegmentLists
	}
	return nil
}

// Steering steers an IP prefix into a policy by BSID (sr_mpls_steering_add_del; the
// color/next-hop automated steering mode is not modelled). Retrieve derives it from the IP
// route that recurses via the BSID label (ip_route_v2_dump) — "partial". Id =
// "<table>/<prefix>". Every change recreates.
type Steering struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Prefix  string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	TableId uint32                 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Bsid    uint32                 `protobuf:"varint,3,opt,name=bsid,proto3" json:"bsid,omitempty"`
	// Optional VPN label pushed under the BSID (0 = none).
	VpnLabel      uint32 `protobuf:"varint,4,opt,name=vpn_label,json=vpnLabel,proto3" json:"vpn_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Steering) Reset() {
	*x = Steering{}
	mi := &file_sr_mpls_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Steering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Steering) ProtoMessage() {}

func (x *Steering) ProtoReflect() protoreflect.Message {
	mi := &file_sr_mpls_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Steering.ProtoReflect.Descriptor instead.
func (*Steering) Descriptor() ([]byte, []int) {
	return file_sr_mpls_model_proto_rawDescGZIP(), []int{2}
}

func (x *Steering) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Steering) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Steering) GetBsid() uint32 {
	if x != nil {
		return x.Bsid
	}
	return 0
}

func (x *Steering) GetVpnLabel() uint32 {
	if x != nil {
		return x.VpnLabel
	}
	return 0
}

// EndpointColor assigns an (endpoint, color) to a policy for automated steering
// (sr_mpls_policy_assign_endpoint_color). Write-only: no dump; VPP clears it only when the
// policy is deleted. Id = bsid.
type EndpointColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bsid          uint32                 `protobuf:"varint,1,opt,name=bsid,proto3" json:"bsid,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Color         uint32                 `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointColor) Reset() {
	*x = EndpointColor{}
	mi := &file_sr_mpls_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointColor) ProtoMessage() {}

func (x *EndpointColor) ProtoReflect() protoreflect.Message {
	mi := &file_sr_mpls_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointColor.ProtoReflect.Descriptor instead.
func (*EndpointColor) Descriptor() ([]byte, []int) {
	return file_sr_mpls_model_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointColor) GetBsid() uint32 {
	if x != nil {
		return x.Bsid
	}
	return 0
}

func (x *EndpointColor) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *EndpointColor) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

var File_sr_mpls_model_proto protoreflect.FileDescriptor

const file_sr_mpls_model_proto_rawDesc = "" +
	"\n" +
	"\x13sr_mpls/model.proto\x12\x1engfw.agent.descriptors.sr_mpls\"=\n" +
	"\vSegmentList\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\rR\x06labels\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\"\x84\x01\n" +
	"\x06Policy\x12\x12\n" +
	"\x04bsid\x18\x01 \x01(\rR\x04bsid\x12\x14\n" +
	"\x05spray\x18\x02 \x01(\bR\x05spray\x12P\n" +
	"\rsegment_lists\x18\x03 \x03(\v2+.ngfw.agent.descriptors.sr_mpls.SegmentListR\fsegmentLists\"n\n" +
	"\bSteering\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\rR\atableId\x12\x12\n" +
	"\x04bsid\x18\x03 \x01(\rR\x04bsid\x12\x1b\n" +
	"\tvpn_label\x18\x04 \x01(\rR\bvpnLabel\"U\n" +
	"\rEndpointColor\x12\x12\n" +
	"\x04bsid\x18\x01 \x01(\rR\x04bsid\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05color\x18\x03 \x01(\rR\x05colorB1Z/ngfw/agent/internal/descriptors/sr_mpls;sr_mplsb\x06proto3"

var (
	file_sr_mpls_model_proto_rawDescOnce sync.Once
	file_sr_mpls_model_proto_rawDescData []byte
)

func file_sr_mpls_model_proto_rawDescGZIP() []byte {
	file_sr_mpls_model_proto_rawDescOnce.Do(func() {
		file_sr_mpls_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sr_mpls_model_proto_rawDesc), len(file_sr_mpls_model_proto_rawDesc)))
	})
	return file_sr_mpls_model_proto_rawDescData
}

var file_sr_mpls_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sr_mpls_model_proto_goTypes = []any{
	(*SegmentList)(nil),   // 0: ngfw.agent.descriptors.sr_mpls.SegmentList
	(*Policy)(nil),        // 1: ngfw.agent.descriptors.sr_mpls.Policy
	(*Steering)(nil),      // 2: ngfw.agent.descriptors.sr_mpls.Steering
	(*EndpointColor)(nil), // 3: ngfw.agent.descriptors.sr_mpls.EndpointColor
}
var file_sr_mpls_model_proto_depIdxs = []int32{
	0, // 0: ngfw.agent.descriptors.sr_mpls.Policy.segment_lists:type_name -> ngfw.agent.descriptors.sr_mpls.SegmentList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sr_mpls_model_proto_init() }
func file_sr_mpls_model_proto_init() {
	if File_sr_mpls_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sr_mpls_model_proto_rawDesc), len(file_sr_mpls_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sr_mpls_model_proto_goTypes,
		DependencyIndexes: file_sr_mpls_model_proto_depIdxs,
		MessageInfos:      file_sr_mpls_model_proto_msgTypes,
	}.Build()
	File_sr_mpls_model_proto = out.File
	file_sr_mpls_model_proto_goTypes = nil
	file_sr_mpls_model_proto_depIdxs = nil
}
