// Command genschema generates Terraform plugin-framework schema code from the VRX OpenAPI document.
//
//	go run ./tools/genschema -openapi <openapi.json> -out internal/provider
//
// It writes (deterministic; `sdk/gen.sh --check` compares with the committed files — never hand-edit):
//
//	zz_interface_schema_gen.go  the attributes of `vrx_interface`, generated from components.schemas.InterfacesConfig
//	                            (a map name → interface; the item schema becomes the resource), the snake_case ↔
//	                            JSON name table and the list of attributes carrying secret references (Sensitive)
//	zz_secrets_gen.go           pointer patterns of write-only leaves (`writeOnly: true`, D-046) and secret references
//	                            (`<kind>/<name>`, D-051) in RootConfig — vrx_config refuses write-only leaves in `value`
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

type schemaT = map[string]any

var secretRefRE = regexp.MustCompile(`^\^\(\?:(?:psk|key|cert|password|token)(?:\|(?:psk|key|cert|password|token))*\)\\?/`)

type gen struct {
	comps     map[string]any
	names     map[string]string // snake → json (all levels)
	helpers   []string          // nested-object helper funcs
	helperSet map[string]bool
	sensitive []string // attribute paths (snake, dotted) holding secret refs / write-only values
	refs      []string // pointer patterns of secret refs in RootConfig
	writeOnly []string
	keyed     map[string]string // array pointer pattern → item key member
	err       error
}

func (g *gen) fail(format string, a ...any) {
	if g.err == nil {
		g.err = fmt.Errorf(format, a...)
	}
}

func main() {
	openapi := flag.String("openapi", "", "OpenAPI document (JSON)")
	out := flag.String("out", "internal/provider", "output directory")
	flag.Parse()
	raw, err := os.ReadFile(*openapi)
	if err != nil {
		log.Fatal(err)
	}
	iface, secrets, summary, err := generate(raw)
	if err != nil {
		log.Fatalf("genschema: %v", err)
	}
	for name, src := range map[string][]byte{"zz_interface_schema_gen.go": iface, "zz_secrets_gen.go": secrets} {
		if err := os.WriteFile(filepath.Join(*out, name), src, 0o644); err != nil {
			log.Fatal(err)
		}
	}
	fmt.Printf("%s → %s\n", summary, *out)
}

var identRE = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// comment makes an OpenAPI-provided string safe inside a `//` comment: printable, one line, bounded.
func comment(s string) string {
	var b strings.Builder
	for _, r := range s {
		if unicode.IsPrint(r) && r != '\u2028' && r != '\u2029' {
			b.WriteRune(r)
		} else {
			b.WriteByte(' ')
		}
	}
	out := b.String()
	if len(out) > 80 {
		out = out[:80]
	}
	return out
}

// generate renders both files from an OpenAPI document. Every string that reaches Go source is either a quoted
// literal (strconv.Quote / %q), a sanitised comment, or an identifier that matched identRE — a hostile document can
// fail generation but never inject code.
func generate(raw []byte) (iface, secrets []byte, summary string, err error) {
	var doc schemaT
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, nil, "", err
	}
	compsAny, _ := doc["components"].(schemaT)
	comps, _ := compsAny["schemas"].(schemaT)
	info, _ := doc["info"].(schemaT)
	if comps == nil || comps["InterfacesConfig"] == nil {
		return nil, nil, "", fmt.Errorf("components.schemas.InterfacesConfig missing")
	}
	g := &gen{comps: comps, names: map[string]string{}, helperSet: map[string]bool{}, keyed: map[string]string{}}
	g.walkSecrets(g.resolve(comps["RootConfig"]), "", 0, map[string]bool{})
	sort.Strings(g.refs)
	sort.Strings(g.writeOnly)

	ifc := g.resolve(comps["InterfacesConfig"])
	item := g.resolve(ifc["additionalProperties"])
	attrs := g.attributes(item, "iface", "/interfaces/*", "")
	if g.err != nil {
		return nil, nil, "", g.err
	}
	for _, reserved := range []string{"id", "name", "revision"} {
		if strings.Contains(attrs, strconv.Quote(reserved)+":") {
			return nil, nil, "", fmt.Errorf("interface schema has a property %q that collides with a provider attribute", reserved)
		}
	}

	head := fmt.Sprintf("// Code generated by tools/genschema from the VRX OpenAPI document (%s %s); DO NOT EDIT.\n\npackage provider\n\n",
		comment(fmt.Sprint(info["title"])), comment(fmt.Sprint(info["version"])))
	var b bytes.Buffer
	b.WriteString(head)
	b.WriteString(`import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ = attr.Value(nil)
	_ = booldefault.StaticBool
	_ = int64default.StaticInt64
	_ = listdefault.StaticValue
	_ = mapdefault.StaticValue
	_ = stringdefault.StaticString
	_ = types.StringType
)

// interfaceGeneratedAttributes are the attributes of one entry of /interfaces (InterfacesConfig item).
func interfaceGeneratedAttributes() map[string]schema.Attribute {
	return `)
	b.WriteString(attrs)
	b.WriteString("\n}\n\n")
	for _, h := range g.helpers {
		b.WriteString(h + "\n")
	}
	b.WriteString("// interfaceJSONNames maps attribute names (any depth) to the JSON member names of the API document.\nvar interfaceJSONNames = map[string]string{\n")
	for _, k := range sortedStrings(g.names) {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, g.names[k])
	}
	b.WriteString("}\n\n// interfaceSensitiveAttributes are the attribute paths holding secret references or write-only values.\nvar interfaceSensitiveAttributes = []string{\n")
	for _, s := range g.sensitive {
		fmt.Fprintf(&b, "\t%q,\n", s)
	}
	b.WriteString("}\n")
	if iface, err = format.Source(b.Bytes()); err != nil {
		return nil, nil, "", fmt.Errorf("interface schema: %w", err)
	}

	var s bytes.Buffer
	s.WriteString(head)
	s.WriteString("// writeOnlyPointers: write-only leaves of the configuration document (D-046); `*` = one key or index.\nvar writeOnlyPointers = []string{\n")
	for _, p := range g.writeOnly {
		fmt.Fprintf(&s, "\t%q,\n", p)
	}
	s.WriteString("}\n\n// secretRefPointers: secret references `<kind>/<name>` (D-051) — names, not values.\nvar secretRefPointers = []string{\n")
	for _, p := range g.refs {
		fmt.Fprintf(&s, "\t%q,\n", p)
	}
	s.WriteString("}\n\n// keyedArrayPointers: arrays whose elements are identified by one member (`x-vrx-ui.itemKey`) —\n// sensitive_value elements are matched by that key, never by index.\nvar keyedArrayPointers = map[string]string{\n")
	for _, k := range sortedStrings(g.keyed) {
		fmt.Fprintf(&s, "\t%q: %q,\n", k, g.keyed[k])
	}
	s.WriteString("}\n")
	if secrets, err = format.Source(s.Bytes()); err != nil {
		return nil, nil, "", fmt.Errorf("secrets: %w", err)
	}
	summary = fmt.Sprintf("terraform: vrx_interface %d JSON names, %d helpers; %d write-only + %d secret-ref pointer patterns, %d keyed arrays",
		len(g.names), len(g.helpers), len(g.writeOnly), len(g.refs), len(g.keyed))
	return iface, secrets, summary, nil
}

func sortedStrings(m map[string]string) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func (g *gen) resolve(v any) schemaT {
	s, _ := v.(schemaT)
	for s != nil {
		ref, ok := s["$ref"].(string)
		if !ok {
			return s
		}
		s, _ = g.comps[ref[strings.LastIndex(ref, "/")+1:]].(schemaT)
	}
	return s
}

func (g *gen) walkSecrets(s schemaT, ptr string, depth int, seen map[string]bool) {
	if s == nil || depth > 40 {
		return
	}
	if ref, ok := s["$ref"].(string); ok {
		name := ref[strings.LastIndex(ref, "/")+1:]
		if seen[name] {
			return
		}
		next := map[string]bool{name: true}
		for k := range seen {
			next[k] = true
		}
		g.walkSecrets(g.resolve(s), ptr, depth+1, next)
		return
	}
	if isWriteOnly(s) {
		g.writeOnly = appendUnique(g.writeOnly, ptr)
	}
	if isSecretRef(s) {
		g.refs = appendUnique(g.refs, ptr)
	}
	if ui, ok := s["x-vrx-ui"].(schemaT); ok && s["type"] == "array" {
		if keys, ok := ui["itemKey"].([]any); ok && len(keys) == 1 {
			if k, ok := keys[0].(string); ok {
				g.keyed[ptr] = k
			}
		}
	}
	for _, comb := range []string{"anyOf", "oneOf", "allOf"} {
		if alts, ok := s[comb].([]any); ok {
			for _, a := range alts {
				as, _ := a.(schemaT)
				g.walkSecrets(as, ptr, depth+1, seen)
			}
		}
	}
	if props, ok := s["properties"].(schemaT); ok {
		for _, k := range sortedKeys(props) {
			ps, _ := props[k].(schemaT)
			g.walkSecrets(ps, ptr+"/"+strings.ReplaceAll(strings.ReplaceAll(k, "~", "~0"), "/", "~1"), depth+1, seen)
		}
	}
	if ap, ok := s["additionalProperties"].(schemaT); ok {
		g.walkSecrets(ap, ptr+"/*", depth+1, seen)
	}
	if it, ok := s["items"].(schemaT); ok {
		g.walkSecrets(it, ptr+"/*", depth+1, seen)
	}
}

func isWriteOnly(s schemaT) bool {
	if wo, _ := s["writeOnly"].(bool); wo {
		return true
	}
	ui, _ := s["x-vrx-ui"].(schemaT)
	sec, _ := ui["secret"].(bool)
	return sec
}

func isSecretRef(s schemaT) bool {
	p, _ := s["pattern"].(string)
	return s["type"] == "string" && secretRefRE.MatchString(p)
}

func appendUnique(xs []string, x string) []string {
	for _, y := range xs {
		if y == x {
			return xs
		}
	}
	return append(xs, x)
}

func sortedKeys(m schemaT) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
		} else if r == '-' || r == '.' {
			b.WriteByte('_')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func pascal(s string) string {
	parts := strings.Split(snake(s), "_")
	for i, p := range parts {
		if p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func description(s schemaT) string {
	title, _ := s["title"].(string)
	ui, _ := s["x-vrx-ui"].(schemaT)
	help, _ := ui["help"].(string)
	d := strings.TrimSpace(strings.TrimSuffix(title+" — "+help, " — "))
	if title == "" {
		d = help
	}
	if enum, ok := s["enum"].([]any); ok {
		vals := make([]string, 0, len(enum))
		for _, e := range enum {
			vals = append(vals, fmt.Sprintf("`%v`", e))
		}
		d += " (one of " + strings.Join(vals, ", ") + ")"
	}
	return d
}

func typeOf(s schemaT) string {
	t, _ := s["type"].(string)
	if t == "" {
		if _, ok := s["properties"]; ok {
			return "object"
		}
	}
	return t
}

func primitiveType(s schemaT) string {
	switch typeOf(s) {
	case "string":
		return "types.StringType"
	case "integer":
		return "types.Int64Type"
	case "number":
		return "types.Float64Type"
	case "boolean":
		return "types.BoolType"
	}
	return ""
}

// attributes renders `map[string]schema.Attribute{...}` for an object schema.
func (g *gen) attributes(s schemaT, prefix, ptr, path string) string {
	props, _ := s["properties"].(schemaT)
	req := map[string]bool{}
	if r, ok := s["required"].([]any); ok {
		for _, x := range r {
			req[x.(string)] = true
		}
	}
	var b strings.Builder
	b.WriteString("map[string]schema.Attribute{\n")
	for _, k := range sortedKeys(props) {
		ps := g.resolve(props[k])
		name := snake(k)
		if !identRE.MatchString(name) || !identRE.MatchString(pascal(k)) {
			g.fail("%s/%s: property name %q does not map to a Terraform attribute / Go identifier", ptr, k, k)
			return "map[string]schema.Attribute{}"
		}
		if name != k {
			g.names[name] = k
		}
		p := name
		if path != "" {
			p = path + "." + name
		}
		expr := g.attribute(ps, req[k], prefix+pascal(k), ptr+"/"+k, p)
		fmt.Fprintf(&b, "%q: %s,\n", name, expr)
	}
	b.WriteString("}")
	return b.String()
}

func (g *gen) attribute(s schemaT, required bool, helper, ptr, path string) string {
	var f []string
	if required {
		f = append(f, "Required: true")
	} else {
		f = append(f, "Optional: true")
	}
	def, hasDef := s["default"]
	if d := description(s); d != "" {
		f = append(f, "MarkdownDescription: "+strconv.Quote(d))
	}
	if isWriteOnly(s) || isSecretRef(s) {
		f = append(f, "Sensitive: true")
		g.sensitive = append(g.sensitive, path)
	}
	computedDefault := func(expr string) {
		if hasDef && !required {
			f = append(f, "Computed: true", "Default: "+expr)
		}
	}
	join := func(kind string) string { return "schema." + kind + "{" + strings.Join(f, ", ") + "}" }

	switch typeOf(s) {
	case "boolean":
		if b, ok := def.(bool); ok {
			computedDefault(fmt.Sprintf("booldefault.StaticBool(%v)", b))
		}
		return join("BoolAttribute")
	case "string":
		if _, ok := s["anyOf"]; !ok {
			if v, ok := def.(string); ok {
				computedDefault("stringdefault.StaticString(" + strconv.Quote(v) + ")")
			}
			return join("StringAttribute")
		}
	case "integer":
		if v, ok := def.(float64); ok {
			computedDefault(fmt.Sprintf("int64default.StaticInt64(%d)", int64(v)))
		}
		return join("Int64Attribute")
	case "number":
		return join("Float64Attribute")
	case "array":
		items := g.resolve(s["items"])
		if et := primitiveType(items); et != "" {
			f = append(f, "ElementType: "+et)
			if arr, ok := def.([]any); ok && len(arr) == 0 {
				computedDefault("listdefault.StaticValue(types.ListValueMust(" + et + ", []attr.Value{}))")
			}
			return join("ListAttribute")
		}
		if typeOf(items) == "object" && items["properties"] != nil {
			fn := g.helper(items, helper+"Item", ptr+"/*", path)
			f = append(f, "NestedObject: "+fn+"()")
			if arr, ok := def.([]any); ok && len(arr) == 0 {
				computedDefault("listdefault.StaticValue(types.ListValueMust(" + fn + "().Type(), []attr.Value{}))")
			}
			return join("ListNestedAttribute")
		}
	case "object":
		if s["properties"] != nil {
			f = append(f, "Attributes: "+g.attributes(s, helper, ptr, path))
			return join("SingleNestedAttribute")
		}
		ap := g.resolve(s["additionalProperties"])
		if ap != nil {
			if et := primitiveType(ap); et != "" {
				f = append(f, "ElementType: "+et)
				if m, ok := def.(schemaT); ok && len(m) == 0 {
					computedDefault("mapdefault.StaticValue(types.MapValueMust(" + et + ", map[string]attr.Value{}))")
				}
				return join("MapAttribute")
			}
			if typeOf(ap) == "object" && ap["properties"] != nil {
				fn := g.helper(ap, helper+"Value", ptr+"/*", path)
				f = append(f, "NestedObject: "+fn+"()")
				if m, ok := def.(schemaT); ok && len(m) == 0 {
					computedDefault("mapdefault.StaticValue(types.MapValueMust(" + fn + "().Type(), map[string]attr.Value{}))")
				}
				return join("MapNestedAttribute")
			}
		}
	}
	g.fail("%s — unsupported schema shape for a typed attribute (type %v); extend tools/genschema", ptr, s["type"])
	return "schema.StringAttribute{Optional: true}"
}

func (g *gen) helper(s schemaT, name, ptr, path string) string {
	fn := "gen" + name + "Object"
	if !identRE.MatchString(fn) {
		g.fail("%s: helper name %q is not a Go identifier", ptr, fn)
		return "genInvalidObject"
	}
	if !g.helperSet[fn] {
		g.helperSet[fn] = true
		body := g.attributes(s, name, ptr, path)
		g.helpers = append(g.helpers, fmt.Sprintf("func %s() schema.NestedAttributeObject {\n\treturn schema.NestedAttributeObject{Attributes: %s}\n}\n", fn, body))
	}
	return fn
}
