#!/usr/bin/env bash
# tools/binapi-gen.sh — regenerate GoVPP bindings for ALL VPP API definitions installed on this host (D-014).
#
#   tools/binapi-gen.sh                       input /usr/share/vpp/api/{core,plugins}/*.api.json → apps/agent/binapi/
#   VPP_API_DIR=/path/to/api tools/binapi-gen.sh
#   BINAPI_SKIP_BUILD=1 tools/binapi-gen.sh   skip the `go build ./binapi/...` verification step
#
# One Go package per .api.json, import path ngfw/agent/binapi/<api>. Idempotent: rerunning against the same VPP install
# yields an empty `git diff`. Commits nothing. apps/agent/binapi/ is written ONLY by this script — run by P04, afterwards
# by the manager when VPP on the host changes; feature tasks never regenerate or hand-edit it (00-CONTEXT "Never do these").
set -euo pipefail
ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
VPP_API_DIR="${VPP_API_DIR:-/usr/share/vpp/api}"
OUT="$ROOT/apps/agent/binapi"
IMPORT_PREFIX="ngfw/agent/binapi"
export PATH="$PATH:$HOME/go/bin:/usr/local/go/bin"

GEN="${BINAPI_GENERATOR:-$(command -v binapi-generator || true)}"
[[ -n "$GEN" && -x "$GEN" ]] || { echo "binapi-gen: binapi-generator not found — go install go.fd.io/govpp/cmd/binapi-generator@v0.13.0" >&2; exit 1; }
[[ -d "$VPP_API_DIR/core" && -d "$VPP_API_DIR/plugins" ]] || { echo "binapi-gen: $VPP_API_DIR has no core/ and plugins/ — is vpp installed here? (VPP_API_DIR overrides)" >&2; exit 1; }
for t in go gofmt rsync jq; do command -v "$t" >/dev/null || { echo "binapi-gen: missing tool $t" >&2; exit 1; }; done

n_core=$(find "$VPP_API_DIR/core" -name '*.api.json' | wc -l)
n_plug=$(find "$VPP_API_DIR/plugins" -name '*.api.json' | wc -l)
gen_ver="$("$GEN" --version 2>&1 | head -1)"
echo "binapi-gen: $gen_ver · input $VPP_API_DIR ($n_core core + $n_plug plugin .api.json) · output ${OUT#"$ROOT"/}"

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
# No API_FILES argument = every .api.json under --input. --no-source-path-info keeps the output independent of VPP_API_DIR.
if ! "$GEN" --input "$VPP_API_DIR" --output-dir "$tmp/binapi" --import-prefix "$IMPORT_PREFIX" --no-source-path-info >"$tmp/gen.log" 2>&1; then
  cat "$tmp/gen.log" >&2; echo "binapi-gen: binapi-generator failed" >&2; exit 1
fi
grep -vE 'level=info' "$tmp/gen.log" || true       # warnings/errors only; the per-file info lines are noise

n_pkgs=$(find "$tmp/binapi" -mindepth 1 -maxdepth 1 -type d | wc -l)
(( n_pkgs == n_core + n_plug )) || echo "binapi-gen: warning: $n_pkgs packages generated for $((n_core + n_plug)) API files"
unformatted="$(gofmt -l "$tmp/binapi" || true)"
[[ -z "$unformatted" ]] || { echo "binapi-gen: generator output is not gofmt-clean:" >&2; echo "$unformatted" >&2; exit 1; }

# provenance: one line per API file with its vl_api_version CRC — a compact review signal when VPP changes
{
  echo "# generated by tools/binapi-gen.sh — do not edit. <api> <vl_api_version crc>"
  echo "# generator: $gen_ver"
  for f in "$VPP_API_DIR"/core/*.api.json "$VPP_API_DIR"/plugins/*.api.json; do
    printf '%s %s\n' "$(basename "$f" .api.json)" "$(jq -r '.vl_api_version // "?"' "$f")"
  done | sort
} > "$tmp/binapi/MANIFEST"

mkdir -p "$OUT"
rsync -a --delete --exclude README.md "$tmp/binapi/" "$OUT/"

mod_ver="$(grep -oE 'go\.fd\.io/govpp v[0-9.]+' "$ROOT/apps/agent/go.mod" | awk '{print $2}' || true)"
gen_semver="$(grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' <<<"$gen_ver" | head -1)"
if [[ "$mod_ver" != "$gen_semver" ]]; then
  echo "binapi-gen: warning: apps/agent/go.mod has govpp '${mod_ver:-none}' but the generator is $gen_semver →" \
       "cd apps/agent && go get go.fd.io/govpp@$gen_semver && go mod tidy"
fi
if [[ "${BINAPI_SKIP_BUILD:-0}" != 1 ]]; then
  if (cd "$ROOT/apps/agent" && go build ./binapi/...); then echo "binapi-gen: go build ./binapi/... ok"
  else echo "binapi-gen: go build ./binapi/... FAILED — is go.fd.io/govpp $gen_semver in apps/agent/go.mod? (go mod tidy)" >&2; exit 1; fi
fi
echo "binapi-gen: $n_pkgs packages in ${OUT#"$ROOT"/} (import $IMPORT_PREFIX/<api>) · review: git status --short apps/agent/binapi"
