// Values of the F-vrf-static-ecmp source-VRF-select descriptors (VPP svs plugin; scheduler.KV.Value).
// Agent-internal: internal/desired/vrf_static_ecmp.go projects `vrfs.<name>.sourceSelect` onto these
// objects and back. proto.Equal on these messages is the scheduler's diff.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: svs_model.proto

package svs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Table is one source-VRF-select table: an IPv4 and an IPv6 FIB table with the same id, named
// "<owner>:svs:<id>" in VPP (ip_table_add_del) and locked by the svs source (svs_table_add_del).
// One per ingress interface. Key: "svs.table/<id>".
type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Set by Retrieve only (partial loss): the IPv4 / IPv6 table does not exist; never in desired state.
	MissingIp4    bool `protobuf:"varint,2,opt,name=missing_ip4,json=missingIp4,proto3" json:"missing_ip4,omitempty"`
	MissingIp6    bool `protobuf:"varint,3,opt,name=missing_ip6,json=missingIp6,proto3" json:"missing_ip6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_svs_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_svs_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_svs_model_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Table) GetMissingIp4() bool {
	if x != nil {
		return x.MissingIp4
	}
	return false
}

func (x *Table) GetMissingIp6() bool {
	if x != nil {
		return x.MissingIp6
	}
	return false
}

// Route is one source prefix → VRF entry of an svs table (svs_route_add_del): a packet whose source
// address matches `prefix` is looked up (destination) in `source_table_id`. Key:
// "svs.route/<table id>/<prefix>".
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The svs table (Table.id).
	TableId uint32 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Source prefix, canonical netip form with host bits cleared; never /0 (that entry belongs to the
	// interface enablement).
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// FIB table of the selected VRF (0 = default). VPP's dump does not expose it (the entry is an exclusive
	// lookup DPO): Retrieve takes it from the applied-once record of the running VPP instance (D-076/D-080),
	// or reports UnknownTable when there is none, so the diff re-programs the entry.
	SourceTableId uint32 `protobuf:"varint,3,opt,name=source_table_id,json=sourceTableId,proto3" json:"source_table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_svs_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_svs_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_svs_model_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Route) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Route) GetSourceTableId() uint32 {
	if x != nil {
		return x.SourceTableId
	}
	return 0
}

// Interface enables source VRF select on one interface for IPv4 and IPv6 (svs_enable_disable), with
// its svs table. Key: "svs.interface/<interface>".
type Interface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical interface name (D-069).
	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// The svs table (Table.id).
	TableId uint32 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Set by Retrieve only: the IPv4 / IPv6 enablement is missing; never in desired state.
	MissingIp4    bool `protobuf:"varint,3,opt,name=missing_ip4,json=missingIp4,proto3" json:"missing_ip4,omitempty"`
	MissingIp6    bool `protobuf:"varint,4,opt,name=missing_ip6,json=missingIp6,proto3" json:"missing_ip6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_svs_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_svs_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_svs_model_proto_rawDescGZIP(), []int{2}
}

func (x *Interface) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Interface) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Interface) GetMissingIp4() bool {
	if x != nil {
		return x.MissingIp4
	}
	return false
}

func (x *Interface) GetMissingIp6() bool {
	if x != nil {
		return x.MissingIp6
	}
	return false
}

var File_svs_model_proto protoreflect.FileDescriptor

const file_svs_model_proto_rawDesc = "" +
	"\n" +
	"\x0fsvs_model.proto\x12\rvrx.agent.svs\"Y\n" +
	"\x05Table\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vmissing_ip4\x18\x02 \x01(\bR\n" +
	"missingIp4\x12\x1f\n" +
	"\vmissing_ip6\x18\x03 \x01(\bR\n" +
	"missingIp6\"b\n" +
	"\x05Route\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\rR\atableId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12&\n" +
	"\x0fsource_table_id\x18\x03 \x01(\rR\rsourceTableId\"\x86\x01\n" +
	"\tInterface\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\rR\atableId\x12\x1f\n" +
	"\vmissing_ip4\x18\x03 \x01(\bR\n" +
	"missingIp4\x12\x1f\n" +
	"\vmissing_ip6\x18\x04 \x01(\bR\n" +
	"missingIp6B)Z'ngfw/agent/internal/descriptors/svs;svsb\x06proto3"

var (
	file_svs_model_proto_rawDescOnce sync.Once
	file_svs_model_proto_rawDescData []byte
)

func file_svs_model_proto_rawDescGZIP() []byte {
	file_svs_model_proto_rawDescOnce.Do(func() {
		file_svs_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svs_model_proto_rawDesc), len(file_svs_model_proto_rawDesc)))
	})
	return file_svs_model_proto_rawDescData
}

var file_svs_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_svs_model_proto_goTypes = []any{
	(*Table)(nil),     // 0: vrx.agent.svs.Table
	(*Route)(nil),     // 1: vrx.agent.svs.Route
	(*Interface)(nil), // 2: vrx.agent.svs.Interface
}
var file_svs_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svs_model_proto_init() }
func file_svs_model_proto_init() {
	if File_svs_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svs_model_proto_rawDesc), len(file_svs_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svs_model_proto_goTypes,
		DependencyIndexes: file_svs_model_proto_depIdxs,
		MessageInfos:      file_svs_model_proto_msgTypes,
	}.Build()
	File_svs_model_proto = out.File
	file_svs_model_proto_goTypes = nil
	file_svs_model_proto_depIdxs = nil
}
