[Unit]
Requires=ngfw-firewall-bootstrap.service
After=ngfw-firewall-bootstrap.service

[Service]
ExecStart=
ExecStart=/usr/sbin/nft -f /etc/nftables.d/ngfw-base.nft
ExecReload=
ExecReload=/usr/sbin/nft -f /etc/nftables.d/ngfw-base.nft
ExecStop=
