// Desired state of the vxlan descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: vxlan/model.proto

package vxlan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tunnel is one VXLAN tunnel interface (vxlan_add_del_tunnel_v3 / vxlan_tunnel_v2_dump). VPP
// names it vxlan_tunnel<instance>, which is the object id; instance is mandatory and unique.
type Tunnel struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Instance uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Outer source address (IPv4 or IPv6).
	Src string `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// Outer destination, unicast or multicast group.
	Dst string `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	// Interface for the multicast group (mandatory iff dst is multicast).
	McastInterface string `protobuf:"bytes,4,opt,name=mcast_interface,json=mcastInterface,proto3" json:"mcast_interface,omitempty"`
	Vni            uint32 `protobuf:"varint,5,opt,name=vni,proto3" json:"vni,omitempty"`
	// Encap FIB table id (dependency vrf/<id> unless 0).
	EncapVrfId uint32 `protobuf:"varint,6,opt,name=encap_vrf_id,json=encapVrfId,proto3" json:"encap_vrf_id,omitempty"`
	// UDP ports; 0 = VXLAN default 4789 (Retrieve canonicalises 4789 back to 0).
	SrcPort uint32 `protobuf:"varint,7,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort uint32 `protobuf:"varint,8,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// L3 tunnel (routed, no MAC) instead of the default L2 tunnel.
	IsL3          bool `protobuf:"varint,9,opt,name=is_l3,json=isL3,proto3" json:"is_l3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_vxlan_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_vxlan_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_vxlan_model_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

func (x *Tunnel) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Tunnel) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Tunnel) GetMcastInterface() string {
	if x != nil {
		return x.McastInterface
	}
	return ""
}

func (x *Tunnel) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

func (x *Tunnel) GetEncapVrfId() uint32 {
	if x != nil {
		return x.EncapVrfId
	}
	return 0
}

func (x *Tunnel) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Tunnel) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Tunnel) GetIsL3() bool {
	if x != nil {
		return x.IsL3
	}
	return false
}

// Bypass enables the ip4/ip6-vxlan-bypass features on an interface
// (sw_interface_set_vxlan_bypass). Write-only: VPP has no dump for it.
type Bypass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Ipv4          bool                   `protobuf:"varint,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          bool                   `protobuf:"varint,3,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bypass) Reset() {
	*x = Bypass{}
	mi := &file_vxlan_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bypass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bypass) ProtoMessage() {}

func (x *Bypass) ProtoReflect() protoreflect.Message {
	mi := &file_vxlan_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bypass.ProtoReflect.Descriptor instead.
func (*Bypass) Descriptor() ([]byte, []int) {
	return file_vxlan_model_proto_rawDescGZIP(), []int{1}
}

func (x *Bypass) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Bypass) GetIpv4() bool {
	if x != nil {
		return x.Ipv4
	}
	return false
}

func (x *Bypass) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

var File_vxlan_model_proto protoreflect.FileDescriptor

const file_vxlan_model_proto_rawDesc = "" +
	"\n" +
	"\x11vxlan/model.proto\x12\x1cngfw.agent.descriptors.vxlan\"\xf0\x01\n" +
	"\x06Tunnel\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\tR\x03dst\x12'\n" +
	"\x0fmcast_interface\x18\x04 \x01(\tR\x0emcastInterface\x12\x10\n" +
	"\x03vni\x18\x05 \x01(\rR\x03vni\x12 \n" +
	"\fencap_vrf_id\x18\x06 \x01(\rR\n" +
	"encapVrfId\x12\x19\n" +
	"\bsrc_port\x18\a \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\b \x01(\rR\adstPort\x12\x13\n" +
	"\x05is_l3\x18\t \x01(\bR\x04isL3\"N\n" +
	"\x06Bypass\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x12\n" +
	"\x04ipv4\x18\x02 \x01(\bR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x03 \x01(\bR\x04ipv6B-Z+ngfw/agent/internal/descriptors/vxlan;vxlanb\x06proto3"

var (
	file_vxlan_model_proto_rawDescOnce sync.Once
	file_vxlan_model_proto_rawDescData []byte
)

func file_vxlan_model_proto_rawDescGZIP() []byte {
	file_vxlan_model_proto_rawDescOnce.Do(func() {
		file_vxlan_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vxlan_model_proto_rawDesc), len(file_vxlan_model_proto_rawDesc)))
	})
	return file_vxlan_model_proto_rawDescData
}

var file_vxlan_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vxlan_model_proto_goTypes = []any{
	(*Tunnel)(nil), // 0: ngfw.agent.descriptors.vxlan.Tunnel
	(*Bypass)(nil), // 1: ngfw.agent.descriptors.vxlan.Bypass
}
var file_vxlan_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vxlan_model_proto_init() }
func file_vxlan_model_proto_init() {
	if File_vxlan_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vxlan_model_proto_rawDesc), len(file_vxlan_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vxlan_model_proto_goTypes,
		DependencyIndexes: file_vxlan_model_proto_depIdxs,
		MessageInfos:      file_vxlan_model_proto_msgTypes,
	}.Build()
	File_vxlan_model_proto = out.File
	file_vxlan_model_proto_goTypes = nil
	file_vxlan_model_proto_depIdxs = nil
}
