// Desired state of the SRv6 descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: sr/model.proto

package sr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Behavior mirrors sr_types.sr_behavior (the classic, non-uSID behaviours).
type Behavior int32

const (
	Behavior_BEHAVIOR_UNSPECIFIED Behavior = 0
	Behavior_END                  Behavior = 1
	Behavior_END_X                Behavior = 2
	Behavior_END_T                Behavior = 3
	Behavior_END_DX2              Behavior = 5
	Behavior_END_DX6              Behavior = 6
	Behavior_END_DX4              Behavior = 7
	Behavior_END_DT6              Behavior = 8
	Behavior_END_DT4              Behavior = 9
)

// Enum value maps for Behavior.
var (
	Behavior_name = map[int32]string{
		0: "BEHAVIOR_UNSPECIFIED",
		1: "END",
		2: "END_X",
		3: "END_T",
		5: "END_DX2",
		6: "END_DX6",
		7: "END_DX4",
		8: "END_DT6",
		9: "END_DT4",
	}
	Behavior_value = map[string]int32{
		"BEHAVIOR_UNSPECIFIED": 0,
		"END":                  1,
		"END_X":                2,
		"END_T":                3,
		"END_DX2":              5,
		"END_DX6":              6,
		"END_DX4":              7,
		"END_DT6":              8,
		"END_DT4":              9,
	}
)

func (x Behavior) Enum() *Behavior {
	p := new(Behavior)
	*p = x
	return p
}

func (x Behavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Behavior) Descriptor() protoreflect.EnumDescriptor {
	return file_sr_model_proto_enumTypes[0].Descriptor()
}

func (Behavior) Type() protoreflect.EnumType {
	return &file_sr_model_proto_enumTypes[0]
}

func (x Behavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Behavior.Descriptor instead.
func (Behavior) EnumDescriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{0}
}

// PolicyType mirrors sr.sr_policy_type.
type PolicyType int32

const (
	PolicyType_DEFAULT PolicyType = 0
	PolicyType_SPRAY   PolicyType = 1
	PolicyType_TEF     PolicyType = 2
)

// Enum value maps for PolicyType.
var (
	PolicyType_name = map[int32]string{
		0: "DEFAULT",
		1: "SPRAY",
		2: "TEF",
	}
	PolicyType_value = map[string]int32{
		"DEFAULT": 0,
		"SPRAY":   1,
		"TEF":     2,
	}
)

func (x PolicyType) Enum() *PolicyType {
	p := new(PolicyType)
	*p = x
	return p
}

func (x PolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_sr_model_proto_enumTypes[1].Descriptor()
}

func (PolicyType) Type() protoreflect.EnumType {
	return &file_sr_model_proto_enumTypes[1]
}

func (x PolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyType.Descriptor instead.
func (PolicyType) EnumDescriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{1}
}

// SteerType mirrors sr_types.sr_steer.
type SteerType int32

const (
	SteerType_STEER_UNSPECIFIED SteerType = 0
	SteerType_L2                SteerType = 2
	SteerType_IPV4              SteerType = 4
	SteerType_IPV6              SteerType = 6
)

// Enum value maps for SteerType.
var (
	SteerType_name = map[int32]string{
		0: "STEER_UNSPECIFIED",
		2: "L2",
		4: "IPV4",
		6: "IPV6",
	}
	SteerType_value = map[string]int32{
		"STEER_UNSPECIFIED": 0,
		"L2":                2,
		"IPV4":              4,
		"IPV6":              6,
	}
)

func (x SteerType) Enum() *SteerType {
	p := new(SteerType)
	*p = x
	return p
}

func (x SteerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SteerType) Descriptor() protoreflect.EnumDescriptor {
	return file_sr_model_proto_enumTypes[2].Descriptor()
}

func (SteerType) Type() protoreflect.EnumType {
	return &file_sr_model_proto_enumTypes[2]
}

func (x SteerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SteerType.Descriptor instead.
func (SteerType) EnumDescriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{2}
}

// LocalSid is one SRv6 local SID (sr_localsid_add_del / sr_localsids_dump). Id = sid.
// Everything recreates on change.
type LocalSid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The /128 local SID (IPv6 address).
	Sid      string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Behavior Behavior `protobuf:"varint,2,opt,name=behavior,proto3,enum=ngfw.agent.descriptors.sr.Behavior" json:"behavior,omitempty"`
	// Penultimate segment pop (END, END_X, END_T).
	EndPsp bool `protobuf:"varint,3,opt,name=end_psp,json=endPsp,proto3" json:"end_psp,omitempty"`
	// IPv6 table the SID is installed in (dependency vrf/<id> unless 0).
	FibTable uint32 `protobuf:"varint,4,opt,name=fib_table,json=fibTable,proto3" json:"fib_table,omitempty"`
	// Cross-connect interface: END_X, END_DX2, END_DX4, END_DX6 (dependency interface/<name>).
	Interface string `protobuf:"bytes,5,opt,name=interface,proto3" json:"interface,omitempty"`
	// Next hop: END_X and END_DX6 (IPv6), END_DX4 (IPv4).
	NextHop string `protobuf:"bytes,6,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	// Lookup table: END_T and END_DT6 (IPv6 table), END_DT4 (IPv4 table) (dependency vrf/<id>).
	LookupTable   uint32 `protobuf:"varint,7,opt,name=lookup_table,json=lookupTable,proto3" json:"lookup_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalSid) Reset() {
	*x = LocalSid{}
	mi := &file_sr_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalSid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSid) ProtoMessage() {}

func (x *LocalSid) ProtoReflect() protoreflect.Message {
	mi := &file_sr_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSid.ProtoReflect.Descriptor instead.
func (*LocalSid) Descriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{0}
}

func (x *LocalSid) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *LocalSid) GetBehavior() Behavior {
	if x != nil {
		return x.Behavior
	}
	return Behavior_BEHAVIOR_UNSPECIFIED
}

func (x *LocalSid) GetEndPsp() bool {
	if x != nil {
		return x.EndPsp
	}
	return false
}

func (x *LocalSid) GetFibTable() uint32 {
	if x != nil {
		return x.FibTable
	}
	return 0
}

func (x *LocalSid) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *LocalSid) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *LocalSid) GetLookupTable() uint32 {
	if x != nil {
		return x.LookupTable
	}
	return 0
}

// SidList is one segment list of a policy (at most 16 SIDs).
type SidList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sids          []string               `protobuf:"bytes,1,rep,name=sids,proto3" json:"sids,omitempty"`
	Weight        uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidList) Reset() {
	*x = SidList{}
	mi := &file_sr_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidList) ProtoMessage() {}

func (x *SidList) ProtoReflect() protoreflect.Message {
	mi := &file_sr_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidList.ProtoReflect.Descriptor instead.
func (*SidList) Descriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{1}
}

func (x *SidList) GetSids() []string {
	if x != nil {
		return x.Sids
	}
	return nil
}

func (x *SidList) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// Policy is one SRv6 policy (sr_policy_add_v2 + sr_policy_mod_v2 for the 2nd… sid lists /
// sr_policy_del / sr_policies_v2_dump). Id = bsid. Everything recreates on change.
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Binding SID (IPv6 address).
	Bsid string     `protobuf:"bytes,1,opt,name=bsid,proto3" json:"bsid,omitempty"`
	Type PolicyType `protobuf:"varint,2,opt,name=type,proto3,enum=ngfw.agent.descriptors.sr.PolicyType" json:"type,omitempty"`
	// true = encapsulation (H.Encaps), false = SRH insertion (H.Insert).
	Encap bool `protobuf:"varint,3,opt,name=encap,proto3" json:"encap,omitempty"`
	// IPv6 table of the BSID FIB entry (dependency vrf/<id> unless 0).
	FibTable uint32 `protobuf:"varint,4,opt,name=fib_table,json=fibTable,proto3" json:"fib_table,omitempty"`
	// Segment lists in order; at least one.
	SidLists []*SidList `protobuf:"bytes,5,rep,name=sid_lists,json=sidLists,proto3" json:"sid_lists,omitempty"`
	// Outer source address for encap policies (mandatory when encap; must be empty for insert
	// policies — VPP would substitute the global encap source, which cannot be read back).
	EncapSrc      string `protobuf:"bytes,6,opt,name=encap_src,json=encapSrc,proto3" json:"encap_src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_sr_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_sr_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{2}
}

func (x *Policy) GetBsid() string {
	if x != nil {
		return x.Bsid
	}
	return ""
}

func (x *Policy) GetType() PolicyType {
	if x != nil {
		return x.Type
	}
	return PolicyType_DEFAULT
}

func (x *Policy) GetEncap() bool {
	if x != nil {
		return x.Encap
	}
	return false
}

func (x *Policy) GetFibTable() uint32 {
	if x != nil {
		return x.FibTable
	}
	return 0
}

func (x *Policy) GetSidLists() []*SidList {
	if x != nil {
		return x.SidLists
	}
	return nil
}

func (x *Policy) GetEncapSrc() string {
	if x != nil {
		return x.EncapSrc
	}
	return ""
}

// Steering steers traffic into a policy (sr_steering_add_del / sr_steering_pol_dump).
// Id = "<l2>/<interface>" or "<ipv4|ipv6>/<table>/<prefix>". Only the policy (bsid) changes
// in place (VPP re-points an existing steering entry).
type Steering struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TrafficType SteerType              `protobuf:"varint,1,opt,name=traffic_type,json=trafficType,proto3,enum=ngfw.agent.descriptors.sr.SteerType" json:"traffic_type,omitempty"`
	// L3 steering: prefix and table (dependency vrf/<id> unless 0).
	Prefix  string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	TableId uint32 `protobuf:"varint,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// L2 steering: the incoming interface (dependency interface/<name>).
	Interface string `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	// The policy to steer into (dependency sr.policy/<bsid>).
	Bsid          string `protobuf:"bytes,5,opt,name=bsid,proto3" json:"bsid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Steering) Reset() {
	*x = Steering{}
	mi := &file_sr_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Steering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Steering) ProtoMessage() {}

func (x *Steering) ProtoReflect() protoreflect.Message {
	mi := &file_sr_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Steering.ProtoReflect.Descriptor instead.
func (*Steering) Descriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{3}
}

func (x *Steering) GetTrafficType() SteerType {
	if x != nil {
		return x.TrafficType
	}
	return SteerType_STEER_UNSPECIFIED
}

func (x *Steering) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Steering) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Steering) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Steering) GetBsid() string {
	if x != nil {
		return x.Bsid
	}
	return ""
}

// EncapSource is the global SRv6 encapsulation source (sr_set_encap_source). Write-only
// singleton: VPP has no getter. Delete resets it to ::.
type EncapSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncapSource) Reset() {
	*x = EncapSource{}
	mi := &file_sr_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncapSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncapSource) ProtoMessage() {}

func (x *EncapSource) ProtoReflect() protoreflect.Message {
	mi := &file_sr_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncapSource.ProtoReflect.Descriptor instead.
func (*EncapSource) Descriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{4}
}

func (x *EncapSource) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// EncapHopLimit is the global hop limit of the outer IPv6 header (sr_set_encap_hop_limit).
// Write-only singleton; Delete resets it to VPP's default 64.
type EncapHopLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HopLimit      uint32                 `protobuf:"varint,1,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncapHopLimit) Reset() {
	*x = EncapHopLimit{}
	mi := &file_sr_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncapHopLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncapHopLimit) ProtoMessage() {}

func (x *EncapHopLimit) ProtoReflect() protoreflect.Message {
	mi := &file_sr_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncapHopLimit.ProtoReflect.Descriptor instead.
func (*EncapHopLimit) Descriptor() ([]byte, []int) {
	return file_sr_model_proto_rawDescGZIP(), []int{5}
}

func (x *EncapHopLimit) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

var File_sr_model_proto protoreflect.FileDescriptor

const file_sr_model_proto_rawDesc = "" +
	"\n" +
	"\x0esr/model.proto\x12\x19ngfw.agent.descriptors.sr\"\xef\x01\n" +
	"\bLocalSid\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12?\n" +
	"\bbehavior\x18\x02 \x01(\x0e2#.ngfw.agent.descriptors.sr.BehaviorR\bbehavior\x12\x17\n" +
	"\aend_psp\x18\x03 \x01(\bR\x06endPsp\x12\x1b\n" +
	"\tfib_table\x18\x04 \x01(\rR\bfibTable\x12\x1c\n" +
	"\tinterface\x18\x05 \x01(\tR\tinterface\x12\x19\n" +
	"\bnext_hop\x18\x06 \x01(\tR\anextHop\x12!\n" +
	"\flookup_table\x18\a \x01(\rR\vlookupTable\"5\n" +
	"\aSidList\x12\x12\n" +
	"\x04sids\x18\x01 \x03(\tR\x04sids\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\"\xe8\x01\n" +
	"\x06Policy\x12\x12\n" +
	"\x04bsid\x18\x01 \x01(\tR\x04bsid\x129\n" +
	"\x04type\x18\x02 \x01(\x0e2%.ngfw.agent.descriptors.sr.PolicyTypeR\x04type\x12\x14\n" +
	"\x05encap\x18\x03 \x01(\bR\x05encap\x12\x1b\n" +
	"\tfib_table\x18\x04 \x01(\rR\bfibTable\x12?\n" +
	"\tsid_lists\x18\x05 \x03(\v2\".ngfw.agent.descriptors.sr.SidListR\bsidLists\x12\x1b\n" +
	"\tencap_src\x18\x06 \x01(\tR\bencapSrc\"\xb8\x01\n" +
	"\bSteering\x12G\n" +
	"\ftraffic_type\x18\x01 \x01(\x0e2$.ngfw.agent.descriptors.sr.SteerTypeR\vtrafficType\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\rR\atableId\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterface\x12\x12\n" +
	"\x04bsid\x18\x05 \x01(\tR\x04bsid\"'\n" +
	"\vEncapSource\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\",\n" +
	"\rEncapHopLimit\x12\x1b\n" +
	"\thop_limit\x18\x01 \x01(\rR\bhopLimit*\x84\x01\n" +
	"\bBehavior\x12\x18\n" +
	"\x14BEHAVIOR_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03END\x10\x01\x12\t\n" +
	"\x05END_X\x10\x02\x12\t\n" +
	"\x05END_T\x10\x03\x12\v\n" +
	"\aEND_DX2\x10\x05\x12\v\n" +
	"\aEND_DX6\x10\x06\x12\v\n" +
	"\aEND_DX4\x10\a\x12\v\n" +
	"\aEND_DT6\x10\b\x12\v\n" +
	"\aEND_DT4\x10\t*-\n" +
	"\n" +
	"PolicyType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\t\n" +
	"\x05SPRAY\x10\x01\x12\a\n" +
	"\x03TEF\x10\x02*>\n" +
	"\tSteerType\x12\x15\n" +
	"\x11STEER_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02L2\x10\x02\x12\b\n" +
	"\x04IPV4\x10\x04\x12\b\n" +
	"\x04IPV6\x10\x06B'Z%ngfw/agent/internal/descriptors/sr;srb\x06proto3"

var (
	file_sr_model_proto_rawDescOnce sync.Once
	file_sr_model_proto_rawDescData []byte
)

func file_sr_model_proto_rawDescGZIP() []byte {
	file_sr_model_proto_rawDescOnce.Do(func() {
		file_sr_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sr_model_proto_rawDesc), len(file_sr_model_proto_rawDesc)))
	})
	return file_sr_model_proto_rawDescData
}

var file_sr_model_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sr_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sr_model_proto_goTypes = []any{
	(Behavior)(0),         // 0: ngfw.agent.descriptors.sr.Behavior
	(PolicyType)(0),       // 1: ngfw.agent.descriptors.sr.PolicyType
	(SteerType)(0),        // 2: ngfw.agent.descriptors.sr.SteerType
	(*LocalSid)(nil),      // 3: ngfw.agent.descriptors.sr.LocalSid
	(*SidList)(nil),       // 4: ngfw.agent.descriptors.sr.SidList
	(*Policy)(nil),        // 5: ngfw.agent.descriptors.sr.Policy
	(*Steering)(nil),      // 6: ngfw.agent.descriptors.sr.Steering
	(*EncapSource)(nil),   // 7: ngfw.agent.descriptors.sr.EncapSource
	(*EncapHopLimit)(nil), // 8: ngfw.agent.descriptors.sr.EncapHopLimit
}
var file_sr_model_proto_depIdxs = []int32{
	0, // 0: ngfw.agent.descriptors.sr.LocalSid.behavior:type_name -> ngfw.agent.descriptors.sr.Behavior
	1, // 1: ngfw.agent.descriptors.sr.Policy.type:type_name -> ngfw.agent.descriptors.sr.PolicyType
	4, // 2: ngfw.agent.descriptors.sr.Policy.sid_lists:type_name -> ngfw.agent.descriptors.sr.SidList
	2, // 3: ngfw.agent.descriptors.sr.Steering.traffic_type:type_name -> ngfw.agent.descriptors.sr.SteerType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sr_model_proto_init() }
func file_sr_model_proto_init() {
	if File_sr_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sr_model_proto_rawDesc), len(file_sr_model_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sr_model_proto_goTypes,
		DependencyIndexes: file_sr_model_proto_depIdxs,
		EnumInfos:         file_sr_model_proto_enumTypes,
		MessageInfos:      file_sr_model_proto_msgTypes,
	}.Build()
	File_sr_model_proto = out.File
	file_sr_model_proto_goTypes = nil
	file_sr_model_proto_depIdxs = nil
}
