// Desired state of the ipip descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ipip/model.proto

package ipip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelMode mirrors tunnel_mode: point-to-point or multipoint (dst unset).
type TunnelMode int32

const (
	TunnelMode_P2P TunnelMode = 0
	TunnelMode_MP  TunnelMode = 1
)

// Enum value maps for TunnelMode.
var (
	TunnelMode_name = map[int32]string{
		0: "P2P",
		1: "MP",
	}
	TunnelMode_value = map[string]int32{
		"P2P": 0,
		"MP":  1,
	}
)

func (x TunnelMode) Enum() *TunnelMode {
	p := new(TunnelMode)
	*p = x
	return p
}

func (x TunnelMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ipip_model_proto_enumTypes[0].Descriptor()
}

func (TunnelMode) Type() protoreflect.EnumType {
	return &file_ipip_model_proto_enumTypes[0]
}

func (x TunnelMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelMode.Descriptor instead.
func (TunnelMode) EnumDescriptor() ([]byte, []int) {
	return file_ipip_model_proto_rawDescGZIP(), []int{0}
}

// Tunnel is one IP-in-IP tunnel interface (ipip_add_tunnel / ipip_del_tunnel). VPP names it
// ipip<instance>, which is the object id; instance is mandatory and unique.
type Tunnel struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Instance uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Outer source address (IPv4 or IPv6).
	Src string `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// Outer destination address; empty for MP tunnels.
	Dst string `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	// Outer FIB table id (dependency vrf/<id> unless 0).
	TableId uint32 `protobuf:"varint,4,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// tunnel_encap_decap_flags bitmask.
	Flags uint32     `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	Mode  TunnelMode `protobuf:"varint,6,opt,name=mode,proto3,enum=ngfw.agent.descriptors.ipip.TunnelMode" json:"mode,omitempty"`
	// Outer DSCP (ip_dscp value, 0 = CS0).
	Dscp          uint32 `protobuf:"varint,7,opt,name=dscp,proto3" json:"dscp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_ipip_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_ipip_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_ipip_model_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

func (x *Tunnel) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Tunnel) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Tunnel) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Tunnel) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Tunnel) GetMode() TunnelMode {
	if x != nil {
		return x.Mode
	}
	return TunnelMode_P2P
}

func (x *Tunnel) GetDscp() uint32 {
	if x != nil {
		return x.Dscp
	}
	return 0
}

// Tunnel6rd is one 6rd tunnel (ipip_6rd_add_tunnel / ipip_6rd_del_tunnel). The name is the
// object id and the owner tag; VPP has no dump that exposes the 6rd parameters, so the
// descriptor is write-only (docs/agent/descriptors/ipip.md).
type Tunnel6Rd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 6rd IPv6 delegated prefix.
	Ip6Prefix string `protobuf:"bytes,2,opt,name=ip6_prefix,json=ip6Prefix,proto3" json:"ip6_prefix,omitempty"`
	// IPv4 prefix (common bits) of the 6rd domain.
	Ip4Prefix string `protobuf:"bytes,3,opt,name=ip4_prefix,json=ip4Prefix,proto3" json:"ip4_prefix,omitempty"`
	// IPv4 source (border relay) address.
	Ip4Src        string `protobuf:"bytes,4,opt,name=ip4_src,json=ip4Src,proto3" json:"ip4_src,omitempty"`
	SecurityCheck bool   `protobuf:"varint,5,opt,name=security_check,json=securityCheck,proto3" json:"security_check,omitempty"`
	Ip6TableId    uint32 `protobuf:"varint,6,opt,name=ip6_table_id,json=ip6TableId,proto3" json:"ip6_table_id,omitempty"`
	Ip4TableId    uint32 `protobuf:"varint,7,opt,name=ip4_table_id,json=ip4TableId,proto3" json:"ip4_table_id,omitempty"`
	// Outer traffic class / TOS.
	TcTos         uint32 `protobuf:"varint,8,opt,name=tc_tos,json=tcTos,proto3" json:"tc_tos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel6Rd) Reset() {
	*x = Tunnel6Rd{}
	mi := &file_ipip_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel6Rd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel6Rd) ProtoMessage() {}

func (x *Tunnel6Rd) ProtoReflect() protoreflect.Message {
	mi := &file_ipip_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel6Rd.ProtoReflect.Descriptor instead.
func (*Tunnel6Rd) Descriptor() ([]byte, []int) {
	return file_ipip_model_proto_rawDescGZIP(), []int{1}
}

func (x *Tunnel6Rd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel6Rd) GetIp6Prefix() string {
	if x != nil {
		return x.Ip6Prefix
	}
	return ""
}

func (x *Tunnel6Rd) GetIp4Prefix() string {
	if x != nil {
		return x.Ip4Prefix
	}
	return ""
}

func (x *Tunnel6Rd) GetIp4Src() string {
	if x != nil {
		return x.Ip4Src
	}
	return ""
}

func (x *Tunnel6Rd) GetSecurityCheck() bool {
	if x != nil {
		return x.SecurityCheck
	}
	return false
}

func (x *Tunnel6Rd) GetIp6TableId() uint32 {
	if x != nil {
		return x.Ip6TableId
	}
	return 0
}

func (x *Tunnel6Rd) GetIp4TableId() uint32 {
	if x != nil {
		return x.Ip4TableId
	}
	return 0
}

func (x *Tunnel6Rd) GetTcTos() uint32 {
	if x != nil {
		return x.TcTos
	}
	return 0
}

var File_ipip_model_proto protoreflect.FileDescriptor

const file_ipip_model_proto_rawDesc = "" +
	"\n" +
	"\x10ipip/model.proto\x12\x1bngfw.agent.descriptors.ipip\"\xca\x01\n" +
	"\x06Tunnel\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\tR\x03dst\x12\x19\n" +
	"\btable_id\x18\x04 \x01(\rR\atableId\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x12;\n" +
	"\x04mode\x18\x06 \x01(\x0e2'.ngfw.agent.descriptors.ipip.TunnelModeR\x04mode\x12\x12\n" +
	"\x04dscp\x18\a \x01(\rR\x04dscp\"\xf8\x01\n" +
	"\tTunnel6rd\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip6_prefix\x18\x02 \x01(\tR\tip6Prefix\x12\x1d\n" +
	"\n" +
	"ip4_prefix\x18\x03 \x01(\tR\tip4Prefix\x12\x17\n" +
	"\aip4_src\x18\x04 \x01(\tR\x06ip4Src\x12%\n" +
	"\x0esecurity_check\x18\x05 \x01(\bR\rsecurityCheck\x12 \n" +
	"\fip6_table_id\x18\x06 \x01(\rR\n" +
	"ip6TableId\x12 \n" +
	"\fip4_table_id\x18\a \x01(\rR\n" +
	"ip4TableId\x12\x15\n" +
	"\x06tc_tos\x18\b \x01(\rR\x05tcTos*\x1d\n" +
	"\n" +
	"TunnelMode\x12\a\n" +
	"\x03P2P\x10\x00\x12\x06\n" +
	"\x02MP\x10\x01B+Z)ngfw/agent/internal/descriptors/ipip;ipipb\x06proto3"

var (
	file_ipip_model_proto_rawDescOnce sync.Once
	file_ipip_model_proto_rawDescData []byte
)

func file_ipip_model_proto_rawDescGZIP() []byte {
	file_ipip_model_proto_rawDescOnce.Do(func() {
		file_ipip_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipip_model_proto_rawDesc), len(file_ipip_model_proto_rawDesc)))
	})
	return file_ipip_model_proto_rawDescData
}

var file_ipip_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ipip_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ipip_model_proto_goTypes = []any{
	(TunnelMode)(0),   // 0: ngfw.agent.descriptors.ipip.TunnelMode
	(*Tunnel)(nil),    // 1: ngfw.agent.descriptors.ipip.Tunnel
	(*Tunnel6Rd)(nil), // 2: ngfw.agent.descriptors.ipip.Tunnel6rd
}
var file_ipip_model_proto_depIdxs = []int32{
	0, // 0: ngfw.agent.descriptors.ipip.Tunnel.mode:type_name -> ngfw.agent.descriptors.ipip.TunnelMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ipip_model_proto_init() }
func file_ipip_model_proto_init() {
	if File_ipip_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipip_model_proto_rawDesc), len(file_ipip_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipip_model_proto_goTypes,
		DependencyIndexes: file_ipip_model_proto_depIdxs,
		EnumInfos:         file_ipip_model_proto_enumTypes,
		MessageInfos:      file_ipip_model_proto_msgTypes,
	}.Build()
	File_ipip_model_proto = out.File
	file_ipip_model_proto_goTypes = nil
	file_ipip_model_proto_depIdxs = nil
}
