// Desired state of the l2tp (L2TPv3) descriptors (agent-internal until moved to packages/proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: l2tp/model.proto

package l2tp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LookupKeyType mirrors l2t_lookup_key.
type LookupKeyType int32

const (
	LookupKeyType_SRC_ADDR   LookupKeyType = 0
	LookupKeyType_DST_ADDR   LookupKeyType = 1
	LookupKeyType_SESSION_ID LookupKeyType = 2
)

// Enum value maps for LookupKeyType.
var (
	LookupKeyType_name = map[int32]string{
		0: "SRC_ADDR",
		1: "DST_ADDR",
		2: "SESSION_ID",
	}
	LookupKeyType_value = map[string]int32{
		"SRC_ADDR":   0,
		"DST_ADDR":   1,
		"SESSION_ID": 2,
	}
)

func (x LookupKeyType) Enum() *LookupKeyType {
	p := new(LookupKeyType)
	*p = x
	return p
}

func (x LookupKeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LookupKeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_l2tp_model_proto_enumTypes[0].Descriptor()
}

func (LookupKeyType) Type() protoreflect.EnumType {
	return &file_l2tp_model_proto_enumTypes[0]
}

func (x LookupKeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LookupKeyType.Descriptor instead.
func (LookupKeyType) EnumDescriptor() ([]byte, []int) {
	return file_l2tp_model_proto_rawDescGZIP(), []int{0}
}

// Tunnel is one L2TPv3 tunnel interface (l2tpv3_create_tunnel / sw_if_l2tpv3_tunnel_dump).
// name is the object id and owner tag. VPP has no delete message: Delete returns
// df6.ErrNoDelete (docs/agent/descriptors/l2tp.md). Cookies change in place
// (l2tpv3_set_tunnel_cookies); everything else is immutable.
type Tunnel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Remote (client) IPv6 address.
	ClientAddress string `protobuf:"bytes,2,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	// Local IPv6 address.
	OurAddress        string `protobuf:"bytes,3,opt,name=our_address,json=ourAddress,proto3" json:"our_address,omitempty"`
	LocalSessionId    uint32 `protobuf:"varint,4,opt,name=local_session_id,json=localSessionId,proto3" json:"local_session_id,omitempty"`
	RemoteSessionId   uint32 `protobuf:"varint,5,opt,name=remote_session_id,json=remoteSessionId,proto3" json:"remote_session_id,omitempty"`
	LocalCookie       uint64 `protobuf:"varint,6,opt,name=local_cookie,json=localCookie,proto3" json:"local_cookie,omitempty"`
	RemoteCookie      uint64 `protobuf:"varint,7,opt,name=remote_cookie,json=remoteCookie,proto3" json:"remote_cookie,omitempty"`
	L2SublayerPresent bool   `protobuf:"varint,8,opt,name=l2_sublayer_present,json=l2SublayerPresent,proto3" json:"l2_sublayer_present,omitempty"`
	// Encap FIB table id. Not reported by the dump, so only 0 round-trips; non-zero is rejected
	// until VPP exposes it (DF-6-questions.md).
	EncapVrfId    uint32 `protobuf:"varint,9,opt,name=encap_vrf_id,json=encapVrfId,proto3" json:"encap_vrf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_l2tp_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_l2tp_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_l2tp_model_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *Tunnel) GetOurAddress() string {
	if x != nil {
		return x.OurAddress
	}
	return ""
}

func (x *Tunnel) GetLocalSessionId() uint32 {
	if x != nil {
		return x.LocalSessionId
	}
	return 0
}

func (x *Tunnel) GetRemoteSessionId() uint32 {
	if x != nil {
		return x.RemoteSessionId
	}
	return 0
}

func (x *Tunnel) GetLocalCookie() uint64 {
	if x != nil {
		return x.LocalCookie
	}
	return 0
}

func (x *Tunnel) GetRemoteCookie() uint64 {
	if x != nil {
		return x.RemoteCookie
	}
	return 0
}

func (x *Tunnel) GetL2SublayerPresent() bool {
	if x != nil {
		return x.L2SublayerPresent
	}
	return false
}

func (x *Tunnel) GetEncapVrfId() uint32 {
	if x != nil {
		return x.EncapVrfId
	}
	return 0
}

// InterfaceEnable enables L2TPv3 decapsulation on an interface
// (l2tpv3_interface_enable_disable). Write-only: VPP has no dump for it.
type InterfaceEnable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceEnable) Reset() {
	*x = InterfaceEnable{}
	mi := &file_l2tp_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceEnable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceEnable) ProtoMessage() {}

func (x *InterfaceEnable) ProtoReflect() protoreflect.Message {
	mi := &file_l2tp_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceEnable.ProtoReflect.Descriptor instead.
func (*InterfaceEnable) Descriptor() ([]byte, []int) {
	return file_l2tp_model_proto_rawDescGZIP(), []int{1}
}

func (x *InterfaceEnable) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

// LookupKey is the VPP-global session lookup key (l2tpv3_set_lookup_key). Singleton,
// write-only, Delete is a no-op (VPP has neither a getter nor a documented reset).
type LookupKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           LookupKeyType          `protobuf:"varint,1,opt,name=key,proto3,enum=ngfw.agent.descriptors.l2tp.LookupKeyType" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupKey) Reset() {
	*x = LookupKey{}
	mi := &file_l2tp_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupKey) ProtoMessage() {}

func (x *LookupKey) ProtoReflect() protoreflect.Message {
	mi := &file_l2tp_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupKey.ProtoReflect.Descriptor instead.
func (*LookupKey) Descriptor() ([]byte, []int) {
	return file_l2tp_model_proto_rawDescGZIP(), []int{2}
}

func (x *LookupKey) GetKey() LookupKeyType {
	if x != nil {
		return x.Key
	}
	return LookupKeyType_SRC_ADDR
}

var File_l2tp_model_proto protoreflect.FileDescriptor

const file_l2tp_model_proto_rawDesc = "" +
	"\n" +
	"\x10l2tp/model.proto\x12\x1bngfw.agent.descriptors.l2tp\"\xd4\x02\n" +
	"\x06Tunnel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eclient_address\x18\x02 \x01(\tR\rclientAddress\x12\x1f\n" +
	"\vour_address\x18\x03 \x01(\tR\n" +
	"ourAddress\x12(\n" +
	"\x10local_session_id\x18\x04 \x01(\rR\x0elocalSessionId\x12*\n" +
	"\x11remote_session_id\x18\x05 \x01(\rR\x0fremoteSessionId\x12!\n" +
	"\flocal_cookie\x18\x06 \x01(\x04R\vlocalCookie\x12#\n" +
	"\rremote_cookie\x18\a \x01(\x04R\fremoteCookie\x12.\n" +
	"\x13l2_sublayer_present\x18\b \x01(\bR\x11l2SublayerPresent\x12 \n" +
	"\fencap_vrf_id\x18\t \x01(\rR\n" +
	"encapVrfId\"/\n" +
	"\x0fInterfaceEnable\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\"I\n" +
	"\tLookupKey\x12<\n" +
	"\x03key\x18\x01 \x01(\x0e2*.ngfw.agent.descriptors.l2tp.LookupKeyTypeR\x03key*;\n" +
	"\rLookupKeyType\x12\f\n" +
	"\bSRC_ADDR\x10\x00\x12\f\n" +
	"\bDST_ADDR\x10\x01\x12\x0e\n" +
	"\n" +
	"SESSION_ID\x10\x02B+Z)ngfw/agent/internal/descriptors/l2tp;l2tpb\x06proto3"

var (
	file_l2tp_model_proto_rawDescOnce sync.Once
	file_l2tp_model_proto_rawDescData []byte
)

func file_l2tp_model_proto_rawDescGZIP() []byte {
	file_l2tp_model_proto_rawDescOnce.Do(func() {
		file_l2tp_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l2tp_model_proto_rawDesc), len(file_l2tp_model_proto_rawDesc)))
	})
	return file_l2tp_model_proto_rawDescData
}

var file_l2tp_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_l2tp_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_l2tp_model_proto_goTypes = []any{
	(LookupKeyType)(0),      // 0: ngfw.agent.descriptors.l2tp.LookupKeyType
	(*Tunnel)(nil),          // 1: ngfw.agent.descriptors.l2tp.Tunnel
	(*InterfaceEnable)(nil), // 2: ngfw.agent.descriptors.l2tp.InterfaceEnable
	(*LookupKey)(nil),       // 3: ngfw.agent.descriptors.l2tp.LookupKey
}
var file_l2tp_model_proto_depIdxs = []int32{
	0, // 0: ngfw.agent.descriptors.l2tp.LookupKey.key:type_name -> ngfw.agent.descriptors.l2tp.LookupKeyType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_l2tp_model_proto_init() }
func file_l2tp_model_proto_init() {
	if File_l2tp_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l2tp_model_proto_rawDesc), len(file_l2tp_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l2tp_model_proto_goTypes,
		DependencyIndexes: file_l2tp_model_proto_depIdxs,
		EnumInfos:         file_l2tp_model_proto_enumTypes,
		MessageInfos:      file_l2tp_model_proto_msgTypes,
	}.Build()
	File_l2tp_model_proto = out.File
	file_l2tp_model_proto_goTypes = nil
	file_l2tp_model_proto_depIdxs = nil
}
