// Desired state of the classify descriptors (agent-internal until moved to packages/proto).
// Mask and match are opaque bytes: (skip_n_vectors + match_n_vectors) * 16 bytes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: classify/model.proto

package classify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action mirrors classify.classify_action.
type Session_Action int32

const (
	Session_NONE              Session_Action = 0
	Session_SET_IP4_FIB_INDEX Session_Action = 1
	Session_SET_IP6_FIB_INDEX Session_Action = 2
	Session_SET_METADATA      Session_Action = 3
)

// Enum value maps for Session_Action.
var (
	Session_Action_name = map[int32]string{
		0: "NONE",
		1: "SET_IP4_FIB_INDEX",
		2: "SET_IP6_FIB_INDEX",
		3: "SET_METADATA",
	}
	Session_Action_value = map[string]int32{
		"NONE":              0,
		"SET_IP4_FIB_INDEX": 1,
		"SET_IP6_FIB_INDEX": 2,
		"SET_METADATA":      3,
	}
)

func (x Session_Action) Enum() *Session_Action {
	p := new(Session_Action)
	*p = x
	return p
}

func (x Session_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Session_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_classify_model_proto_enumTypes[0].Descriptor()
}

func (Session_Action) Type() protoreflect.EnumType {
	return &file_classify_model_proto_enumTypes[0]
}

func (x Session_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Session_Action.Descriptor instead.
func (Session_Action) EnumDescriptor() ([]byte, []int) {
	return file_classify_model_proto_rawDescGZIP(), []int{1, 0}
}

// Table is one classifier table (classify_add_del_table). VPP has no tag field: the owner's
// name ↔ table index mapping lives in the Store (see docs/agent/descriptors/classify.md).
type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owner-unique name; the key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Hash buckets; VPP rounds up to a power of two (Normalize does the same). Default 2.
	Nbuckets uint32 `protobuf:"varint,2,opt,name=nbuckets,proto3" json:"nbuckets,omitempty"`
	// Heap size in bytes; default 2097152. Not reported by VPP (kept in the Store).
	MemorySize   uint32 `protobuf:"varint,3,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	SkipNVectors uint32 `protobuf:"varint,4,opt,name=skip_n_vectors,json=skipNVectors,proto3" json:"skip_n_vectors,omitempty"`
	// Default 1.
	MatchNVectors uint32 `protobuf:"varint,5,opt,name=match_n_vectors,json=matchNVectors,proto3" json:"match_n_vectors,omitempty"`
	// (skip_n_vectors + match_n_vectors) * 16 bytes; shorter masks are zero-padded.
	Mask []byte `protobuf:"bytes,6,opt,name=mask,proto3" json:"mask,omitempty"`
	// Name of the next table in the chain; empty = none.
	NextTable string `protobuf:"bytes,7,opt,name=next_table,json=nextTable,proto3" json:"next_table,omitempty"`
	// Next node on miss; 4294967295 = table default.
	MissNextIndex uint32 `protobuf:"varint,8,opt,name=miss_next_index,json=missNextIndex,proto3" json:"miss_next_index,omitempty"`
	// Not reported by VPP (kept in the Store).
	CurrentDataFlag   bool  `protobuf:"varint,9,opt,name=current_data_flag,json=currentDataFlag,proto3" json:"current_data_flag,omitempty"`
	CurrentDataOffset int32 `protobuf:"varint,10,opt,name=current_data_offset,json=currentDataOffset,proto3" json:"current_data_offset,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_classify_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_classify_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_classify_model_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetNbuckets() uint32 {
	if x != nil {
		return x.Nbuckets
	}
	return 0
}

func (x *Table) GetMemorySize() uint32 {
	if x != nil {
		return x.MemorySize
	}
	return 0
}

func (x *Table) GetSkipNVectors() uint32 {
	if x != nil {
		return x.SkipNVectors
	}
	return 0
}

func (x *Table) GetMatchNVectors() uint32 {
	if x != nil {
		return x.MatchNVectors
	}
	return 0
}

func (x *Table) GetMask() []byte {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *Table) GetNextTable() string {
	if x != nil {
		return x.NextTable
	}
	return ""
}

func (x *Table) GetMissNextIndex() uint32 {
	if x != nil {
		return x.MissNextIndex
	}
	return 0
}

func (x *Table) GetCurrentDataFlag() bool {
	if x != nil {
		return x.CurrentDataFlag
	}
	return false
}

func (x *Table) GetCurrentDataOffset() int32 {
	if x != nil {
		return x.CurrentDataOffset
	}
	return 0
}

// Session is one entry of a table (classify_add_del_session).
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Table string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// (skip_n_vectors + match_n_vectors) * 16 bytes; the skipped bytes are normalised to zero.
	Match []byte `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	// 4294967295 = table default.
	HitNextIndex uint32 `protobuf:"varint,3,opt,name=hit_next_index,json=hitNextIndex,proto3" json:"hit_next_index,omitempty"`
	OpaqueIndex  uint32 `protobuf:"varint,4,opt,name=opaque_index,json=opaqueIndex,proto3" json:"opaque_index,omitempty"`
	Advance      int32  `protobuf:"varint,5,opt,name=advance,proto3" json:"advance,omitempty"`
	// Action and metadata are not reported by VPP (kept in the Store).
	Action        Session_Action `protobuf:"varint,6,opt,name=action,proto3,enum=ngfw.agent.descriptors.classify.Session_Action" json:"action,omitempty"`
	Metadata      uint32         `protobuf:"varint,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_classify_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_classify_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_classify_model_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Session) GetMatch() []byte {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *Session) GetHitNextIndex() uint32 {
	if x != nil {
		return x.HitNextIndex
	}
	return 0
}

func (x *Session) GetOpaqueIndex() uint32 {
	if x != nil {
		return x.OpaqueIndex
	}
	return 0
}

func (x *Session) GetAdvance() int32 {
	if x != nil {
		return x.Advance
	}
	return 0
}

func (x *Session) GetAction() Session_Action {
	if x != nil {
		return x.Action
	}
	return Session_NONE
}

func (x *Session) GetMetadata() uint32 {
	if x != nil {
		return x.Metadata
	}
	return 0
}

// InterfaceIpTable binds a table to the ip4-classify / ip6-classify lookup of an interface
// (classify_set_interface_ip_table). Write-only: VPP has no readback.
type InterfaceIpTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Ipv6          bool                   `protobuf:"varint,2,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceIpTable) Reset() {
	*x = InterfaceIpTable{}
	mi := &file_classify_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceIpTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceIpTable) ProtoMessage() {}

func (x *InterfaceIpTable) ProtoReflect() protoreflect.Message {
	mi := &file_classify_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceIpTable.ProtoReflect.Descriptor instead.
func (*InterfaceIpTable) Descriptor() ([]byte, []int) {
	return file_classify_model_proto_rawDescGZIP(), []int{2}
}

func (x *InterfaceIpTable) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *InterfaceIpTable) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

func (x *InterfaceIpTable) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

// InterfaceL2Tables binds the L2 input or output classifier tables of an interface
// (classify_set_interface_l2_tables). Write-only: VPP has no readback.
type InterfaceL2Tables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Input         bool                   `protobuf:"varint,2,opt,name=input,proto3" json:"input,omitempty"`
	Ip4Table      string                 `protobuf:"bytes,3,opt,name=ip4_table,json=ip4Table,proto3" json:"ip4_table,omitempty"`
	Ip6Table      string                 `protobuf:"bytes,4,opt,name=ip6_table,json=ip6Table,proto3" json:"ip6_table,omitempty"`
	OtherTable    string                 `protobuf:"bytes,5,opt,name=other_table,json=otherTable,proto3" json:"other_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceL2Tables) Reset() {
	*x = InterfaceL2Tables{}
	mi := &file_classify_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceL2Tables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceL2Tables) ProtoMessage() {}

func (x *InterfaceL2Tables) ProtoReflect() protoreflect.Message {
	mi := &file_classify_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceL2Tables.ProtoReflect.Descriptor instead.
func (*InterfaceL2Tables) Descriptor() ([]byte, []int) {
	return file_classify_model_proto_rawDescGZIP(), []int{3}
}

func (x *InterfaceL2Tables) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *InterfaceL2Tables) GetInput() bool {
	if x != nil {
		return x.Input
	}
	return false
}

func (x *InterfaceL2Tables) GetIp4Table() string {
	if x != nil {
		return x.Ip4Table
	}
	return ""
}

func (x *InterfaceL2Tables) GetIp6Table() string {
	if x != nil {
		return x.Ip6Table
	}
	return ""
}

func (x *InterfaceL2Tables) GetOtherTable() string {
	if x != nil {
		return x.OtherTable
	}
	return ""
}

// InputAcl binds the input ACL classifier tables of an interface (input_acl_set_interface).
// Retrieved with classify_table_by_interface.
type InputAcl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Ip4Table      string                 `protobuf:"bytes,2,opt,name=ip4_table,json=ip4Table,proto3" json:"ip4_table,omitempty"`
	Ip6Table      string                 `protobuf:"bytes,3,opt,name=ip6_table,json=ip6Table,proto3" json:"ip6_table,omitempty"`
	L2Table       string                 `protobuf:"bytes,4,opt,name=l2_table,json=l2Table,proto3" json:"l2_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputAcl) Reset() {
	*x = InputAcl{}
	mi := &file_classify_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputAcl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputAcl) ProtoMessage() {}

func (x *InputAcl) ProtoReflect() protoreflect.Message {
	mi := &file_classify_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputAcl.ProtoReflect.Descriptor instead.
func (*InputAcl) Descriptor() ([]byte, []int) {
	return file_classify_model_proto_rawDescGZIP(), []int{4}
}

func (x *InputAcl) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *InputAcl) GetIp4Table() string {
	if x != nil {
		return x.Ip4Table
	}
	return ""
}

func (x *InputAcl) GetIp6Table() string {
	if x != nil {
		return x.Ip6Table
	}
	return ""
}

func (x *InputAcl) GetL2Table() string {
	if x != nil {
		return x.L2Table
	}
	return ""
}

// OutputAcl binds the output ACL classifier tables of an interface
// (output_acl_set_interface). Write-only: VPP has no readback.
type OutputAcl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Ip4Table      string                 `protobuf:"bytes,2,opt,name=ip4_table,json=ip4Table,proto3" json:"ip4_table,omitempty"`
	Ip6Table      string                 `protobuf:"bytes,3,opt,name=ip6_table,json=ip6Table,proto3" json:"ip6_table,omitempty"`
	L2Table       string                 `protobuf:"bytes,4,opt,name=l2_table,json=l2Table,proto3" json:"l2_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputAcl) Reset() {
	*x = OutputAcl{}
	mi := &file_classify_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputAcl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputAcl) ProtoMessage() {}

func (x *OutputAcl) ProtoReflect() protoreflect.Message {
	mi := &file_classify_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputAcl.ProtoReflect.Descriptor instead.
func (*OutputAcl) Descriptor() ([]byte, []int) {
	return file_classify_model_proto_rawDescGZIP(), []int{5}
}

func (x *OutputAcl) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *OutputAcl) GetIp4Table() string {
	if x != nil {
		return x.Ip4Table
	}
	return ""
}

func (x *OutputAcl) GetIp6Table() string {
	if x != nil {
		return x.Ip6Table
	}
	return ""
}

func (x *OutputAcl) GetL2Table() string {
	if x != nil {
		return x.L2Table
	}
	return ""
}

var File_classify_model_proto protoreflect.FileDescriptor

const file_classify_model_proto_rawDesc = "" +
	"\n" +
	"\x14classify/model.proto\x12\x1fngfw.agent.descriptors.classify\"\xdd\x02\n" +
	"\x05Table\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bnbuckets\x18\x02 \x01(\rR\bnbuckets\x12\x1f\n" +
	"\vmemory_size\x18\x03 \x01(\rR\n" +
	"memorySize\x12$\n" +
	"\x0eskip_n_vectors\x18\x04 \x01(\rR\fskipNVectors\x12&\n" +
	"\x0fmatch_n_vectors\x18\x05 \x01(\rR\rmatchNVectors\x12\x12\n" +
	"\x04mask\x18\x06 \x01(\fR\x04mask\x12\x1d\n" +
	"\n" +
	"next_table\x18\a \x01(\tR\tnextTable\x12&\n" +
	"\x0fmiss_next_index\x18\b \x01(\rR\rmissNextIndex\x12*\n" +
	"\x11current_data_flag\x18\t \x01(\bR\x0fcurrentDataFlag\x12.\n" +
	"\x13current_data_offset\x18\n" +
	" \x01(\x05R\x11currentDataOffset\"\xd1\x02\n" +
	"\aSession\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x14\n" +
	"\x05match\x18\x02 \x01(\fR\x05match\x12$\n" +
	"\x0ehit_next_index\x18\x03 \x01(\rR\fhitNextIndex\x12!\n" +
	"\fopaque_index\x18\x04 \x01(\rR\vopaqueIndex\x12\x18\n" +
	"\aadvance\x18\x05 \x01(\x05R\aadvance\x12G\n" +
	"\x06action\x18\x06 \x01(\x0e2/.ngfw.agent.descriptors.classify.Session.ActionR\x06action\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\rR\bmetadata\"R\n" +
	"\x06Action\x12\b\n" +
	"\x04NONE\x10\x00\x12\x15\n" +
	"\x11SET_IP4_FIB_INDEX\x10\x01\x12\x15\n" +
	"\x11SET_IP6_FIB_INDEX\x10\x02\x12\x10\n" +
	"\fSET_METADATA\x10\x03\"Z\n" +
	"\x10InterfaceIpTable\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x12\n" +
	"\x04ipv6\x18\x02 \x01(\bR\x04ipv6\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\"\xa2\x01\n" +
	"\x11InterfaceL2Tables\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x14\n" +
	"\x05input\x18\x02 \x01(\bR\x05input\x12\x1b\n" +
	"\tip4_table\x18\x03 \x01(\tR\bip4Table\x12\x1b\n" +
	"\tip6_table\x18\x04 \x01(\tR\bip6Table\x12\x1f\n" +
	"\vother_table\x18\x05 \x01(\tR\n" +
	"otherTable\"}\n" +
	"\bInputAcl\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1b\n" +
	"\tip4_table\x18\x02 \x01(\tR\bip4Table\x12\x1b\n" +
	"\tip6_table\x18\x03 \x01(\tR\bip6Table\x12\x19\n" +
	"\bl2_table\x18\x04 \x01(\tR\al2Table\"~\n" +
	"\tOutputAcl\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1b\n" +
	"\tip4_table\x18\x02 \x01(\tR\bip4Table\x12\x1b\n" +
	"\tip6_table\x18\x03 \x01(\tR\bip6Table\x12\x19\n" +
	"\bl2_table\x18\x04 \x01(\tR\al2TableB3Z1ngfw/agent/internal/descriptors/classify;classifyb\x06proto3"

var (
	file_classify_model_proto_rawDescOnce sync.Once
	file_classify_model_proto_rawDescData []byte
)

func file_classify_model_proto_rawDescGZIP() []byte {
	file_classify_model_proto_rawDescOnce.Do(func() {
		file_classify_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classify_model_proto_rawDesc), len(file_classify_model_proto_rawDesc)))
	})
	return file_classify_model_proto_rawDescData
}

var file_classify_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_classify_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_classify_model_proto_goTypes = []any{
	(Session_Action)(0),       // 0: ngfw.agent.descriptors.classify.Session.Action
	(*Table)(nil),             // 1: ngfw.agent.descriptors.classify.Table
	(*Session)(nil),           // 2: ngfw.agent.descriptors.classify.Session
	(*InterfaceIpTable)(nil),  // 3: ngfw.agent.descriptors.classify.InterfaceIpTable
	(*InterfaceL2Tables)(nil), // 4: ngfw.agent.descriptors.classify.InterfaceL2Tables
	(*InputAcl)(nil),          // 5: ngfw.agent.descriptors.classify.InputAcl
	(*OutputAcl)(nil),         // 6: ngfw.agent.descriptors.classify.OutputAcl
}
var file_classify_model_proto_depIdxs = []int32{
	0, // 0: ngfw.agent.descriptors.classify.Session.action:type_name -> ngfw.agent.descriptors.classify.Session.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_classify_model_proto_init() }
func file_classify_model_proto_init() {
	if File_classify_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classify_model_proto_rawDesc), len(file_classify_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_classify_model_proto_goTypes,
		DependencyIndexes: file_classify_model_proto_depIdxs,
		EnumInfos:         file_classify_model_proto_enumTypes,
		MessageInfos:      file_classify_model_proto_msgTypes,
	}.Build()
	File_classify_model_proto = out.File
	file_classify_model_proto_goTypes = nil
	file_classify_model_proto_depIdxs = nil
}
